// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: api_keys.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addAPIKeySpentTotal = `-- name: AddAPIKeySpentTotal :exec
UPDATE api_keys
SET spent_total = spent_total + $1, updated_at = now()
WHERE id = $2
`

type AddAPIKeySpentTotalParams struct {
	Amount pgtype.Numeric
	ID     int64
}

// AddAPIKeySpentTotal 在 settlement capture 时累加该 Key 的累计花费（M7 费用上限计数器）。
func (q *Queries) AddAPIKeySpentTotal(ctx context.Context, arg AddAPIKeySpentTotalParams) error {
	_, err := q.db.Exec(ctx, addAPIKeySpentTotal, arg.Amount, arg.ID)
	return err
}

const countAPIKeysByUser = `-- name: CountAPIKeysByUser :one
SELECT COUNT(*) FROM api_keys WHERE user_id = $1
`

// CountAPIKeysByUser 供 admin API Key 列表分页统计总数。
func (q *Queries) CountAPIKeysByUser(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countAPIKeysByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAPIKey = `-- name: CreateAPIKey :one
INSERT INTO api_keys (user_id, name, key_prefix, key_hash, key_plaintext, expires_at, route_id)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
RETURNING id, name, key_prefix, key_hash, key_plaintext, last_used_at, expires_at, disabled_at, revoked_at, created_at, updated_at, spend_limit, spent_total, route_id, rpm_limit, tpm_limit, rpd_limit, user_id
`

type CreateAPIKeyParams struct {
	UserID       int64
	Name         string
	KeyPrefix    string
	KeyHash      string
	KeyPlaintext pgtype.Text
	ExpiresAt    pgtype.Timestamptz
	RouteID      int64
}

// CreateAPIKey 创建用户 API Key，保存 key hash（认证用）、展示前缀与完整明文（供多次复制）；route_id 必填（线路必须显式绑定，无默认回落）。
func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, createAPIKey,
		arg.UserID,
		arg.Name,
		arg.KeyPrefix,
		arg.KeyHash,
		arg.KeyPlaintext,
		arg.ExpiresAt,
		arg.RouteID,
	)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.KeyPrefix,
		&i.KeyHash,
		&i.KeyPlaintext,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.DisabledAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SpendLimit,
		&i.SpentTotal,
		&i.RouteID,
		&i.RpmLimit,
		&i.TpmLimit,
		&i.RpdLimit,
		&i.UserID,
	)
	return i, err
}

const getAPIKeyByHash = `-- name: GetAPIKeyByHash :one
SELECT k.id, k.user_id, k.name, k.key_prefix, k.key_hash, k.last_used_at, k.expires_at, k.disabled_at, k.revoked_at, k.created_at, k.updated_at,
       (k.spend_limit IS NOT NULL AND k.spent_total >= k.spend_limit) AS spend_limit_reached,
       k.route_id,
       k.rpm_limit, k.tpm_limit, k.rpd_limit
FROM api_keys k
WHERE key_hash = $1
LIMIT 1
`

type GetAPIKeyByHashRow struct {
	ID                int64
	UserID            int64
	Name              string
	KeyPrefix         string
	KeyHash           string
	LastUsedAt        pgtype.Timestamptz
	ExpiresAt         pgtype.Timestamptz
	DisabledAt        pgtype.Timestamptz
	RevokedAt         pgtype.Timestamptz
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
	SpendLimitReached pgtype.Bool
	RouteID           int64
	RpmLimit          pgtype.Int4
	TpmLimit          pgtype.Int4
	RpdLimit          pgtype.Int4
}

// GetAPIKeyByHash 按 key hash 读取 API Key，带出所属用户 ID 与 Key 绑定线路，并计算是否已达费用上限。
// spend_limit_reached 在 SQL 层判定，避免认证路径在 Go 里做 NUMERIC 比较（M7 费用上限闸门）。
// route_id 是运行时线路解析的唯一依据（线路必填，无默认回落；线路缺失/停用则拒绝请求）。
func (q *Queries) GetAPIKeyByHash(ctx context.Context, keyHash string) (GetAPIKeyByHashRow, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByHash, keyHash)
	var i GetAPIKeyByHashRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.KeyPrefix,
		&i.KeyHash,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.DisabledAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SpendLimitReached,
		&i.RouteID,
		&i.RpmLimit,
		&i.TpmLimit,
		&i.RpdLimit,
	)
	return i, err
}

const getAPIKeyByID = `-- name: GetAPIKeyByID :one
SELECT k.id, k.user_id, k.name, k.key_prefix, k.key_plaintext, k.last_used_at, k.expires_at, k.disabled_at, k.revoked_at, k.spend_limit, k.spent_total, k.route_id, k.rpm_limit, k.tpm_limit, k.rpd_limit, k.created_at, k.updated_at
FROM api_keys k
WHERE k.id = $1
LIMIT 1
`

type GetAPIKeyByIDRow struct {
	ID           int64
	UserID       int64
	Name         string
	KeyPrefix    string
	KeyPlaintext pgtype.Text
	LastUsedAt   pgtype.Timestamptz
	ExpiresAt    pgtype.Timestamptz
	DisabledAt   pgtype.Timestamptz
	RevokedAt    pgtype.Timestamptz
	SpendLimit   pgtype.Numeric
	SpentTotal   pgtype.Numeric
	RouteID      int64
	RpmLimit     pgtype.Int4
	TpmLimit     pgtype.Int4
	RpdLimit     pgtype.Int4
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

// GetAPIKeyByID 供 admin 按 id 读取单把 API Key（带所属用户 ID 与 Key 绑定线路；返回明文 key 供复制）。
func (q *Queries) GetAPIKeyByID(ctx context.Context, id int64) (GetAPIKeyByIDRow, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByID, id)
	var i GetAPIKeyByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.KeyPrefix,
		&i.KeyPlaintext,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.DisabledAt,
		&i.RevokedAt,
		&i.SpendLimit,
		&i.SpentTotal,
		&i.RouteID,
		&i.RpmLimit,
		&i.TpmLimit,
		&i.RpdLimit,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAPIKeysByUserPage = `-- name: ListAPIKeysByUserPage :many
SELECT id, user_id, name, key_prefix, key_plaintext, last_used_at, expires_at, disabled_at, revoked_at, spend_limit, spent_total, route_id, rpm_limit, tpm_limit, rpd_limit, created_at, updated_at
FROM api_keys
WHERE user_id = $1
ORDER BY created_at DESC, id DESC
LIMIT $3 OFFSET $2
`

type ListAPIKeysByUserPageParams struct {
	UserID     int64
	PageOffset int32
	PageLimit  int32
}

type ListAPIKeysByUserPageRow struct {
	ID           int64
	UserID       int64
	Name         string
	KeyPrefix    string
	KeyPlaintext pgtype.Text
	LastUsedAt   pgtype.Timestamptz
	ExpiresAt    pgtype.Timestamptz
	DisabledAt   pgtype.Timestamptz
	RevokedAt    pgtype.Timestamptz
	SpendLimit   pgtype.Numeric
	SpentTotal   pgtype.Numeric
	RouteID      int64
	RpmLimit     pgtype.Int4
	TpmLimit     pgtype.Int4
	RpdLimit     pgtype.Int4
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

// ListAPIKeysByUserPage 供 admin 按用户分页倒序列出 API Key（返回明文 key 供复制，不返回 key_hash）。
func (q *Queries) ListAPIKeysByUserPage(ctx context.Context, arg ListAPIKeysByUserPageParams) ([]ListAPIKeysByUserPageRow, error) {
	rows, err := q.db.Query(ctx, listAPIKeysByUserPage, arg.UserID, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAPIKeysByUserPageRow
	for rows.Next() {
		var i ListAPIKeysByUserPageRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.KeyPrefix,
			&i.KeyPlaintext,
			&i.LastUsedAt,
			&i.ExpiresAt,
			&i.DisabledAt,
			&i.RevokedAt,
			&i.SpendLimit,
			&i.SpentTotal,
			&i.RouteID,
			&i.RpmLimit,
			&i.TpmLimit,
			&i.RpdLimit,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAPIKey = `-- name: RevokeAPIKey :one
UPDATE api_keys
SET revoked_at = now(), updated_at = now()
WHERE id = $1 AND revoked_at IS NULL
RETURNING id, user_id, name, key_prefix, key_plaintext, last_used_at, expires_at, disabled_at, revoked_at, spend_limit, spent_total, route_id, rpm_limit, tpm_limit, rpd_limit, created_at, updated_at
`

type RevokeAPIKeyRow struct {
	ID           int64
	UserID       int64
	Name         string
	KeyPrefix    string
	KeyPlaintext pgtype.Text
	LastUsedAt   pgtype.Timestamptz
	ExpiresAt    pgtype.Timestamptz
	DisabledAt   pgtype.Timestamptz
	RevokedAt    pgtype.Timestamptz
	SpendLimit   pgtype.Numeric
	SpentTotal   pgtype.Numeric
	RouteID      int64
	RpmLimit     pgtype.Int4
	TpmLimit     pgtype.Int4
	RpdLimit     pgtype.Int4
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

// RevokeAPIKey 永久吊销 API Key（revoked_at 置 now()，不可逆）。
func (q *Queries) RevokeAPIKey(ctx context.Context, id int64) (RevokeAPIKeyRow, error) {
	row := q.db.QueryRow(ctx, revokeAPIKey, id)
	var i RevokeAPIKeyRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.KeyPrefix,
		&i.KeyPlaintext,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.DisabledAt,
		&i.RevokedAt,
		&i.SpendLimit,
		&i.SpentTotal,
		&i.RouteID,
		&i.RpmLimit,
		&i.TpmLimit,
		&i.RpdLimit,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setAPIKeyDisabled = `-- name: SetAPIKeyDisabled :one
UPDATE api_keys
SET disabled_at = $1, updated_at = now()
WHERE id = $2
RETURNING id, user_id, name, key_prefix, key_plaintext, last_used_at, expires_at, disabled_at, revoked_at, spend_limit, spent_total, route_id, rpm_limit, tpm_limit, rpd_limit, created_at, updated_at
`

type SetAPIKeyDisabledParams struct {
	DisabledAt pgtype.Timestamptz
	ID         int64
}

type SetAPIKeyDisabledRow struct {
	ID           int64
	UserID       int64
	Name         string
	KeyPrefix    string
	KeyPlaintext pgtype.Text
	LastUsedAt   pgtype.Timestamptz
	ExpiresAt    pgtype.Timestamptz
	DisabledAt   pgtype.Timestamptz
	RevokedAt    pgtype.Timestamptz
	SpendLimit   pgtype.Numeric
	SpentTotal   pgtype.Numeric
	RouteID      int64
	RpmLimit     pgtype.Int4
	TpmLimit     pgtype.Int4
	RpdLimit     pgtype.Int4
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

// SetAPIKeyDisabled 启停 API Key：disabled_at 置 now() 为停用，置 NULL 为启用。
func (q *Queries) SetAPIKeyDisabled(ctx context.Context, arg SetAPIKeyDisabledParams) (SetAPIKeyDisabledRow, error) {
	row := q.db.QueryRow(ctx, setAPIKeyDisabled, arg.DisabledAt, arg.ID)
	var i SetAPIKeyDisabledRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.KeyPrefix,
		&i.KeyPlaintext,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.DisabledAt,
		&i.RevokedAt,
		&i.SpendLimit,
		&i.SpentTotal,
		&i.RouteID,
		&i.RpmLimit,
		&i.TpmLimit,
		&i.RpdLimit,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setAPIKeyRateLimits = `-- name: SetAPIKeyRateLimits :one
UPDATE api_keys
SET rpm_limit = $1, tpm_limit = $2, rpd_limit = $3, updated_at = now()
WHERE id = $4
RETURNING id, user_id, name, key_prefix, key_plaintext, last_used_at, expires_at, disabled_at, revoked_at, spend_limit, spent_total, route_id, rpm_limit, tpm_limit, rpd_limit, created_at, updated_at
`

type SetAPIKeyRateLimitsParams struct {
	RpmLimit pgtype.Int4
	TpmLimit pgtype.Int4
	RpdLimit pgtype.Int4
	ID       int64
}

type SetAPIKeyRateLimitsRow struct {
	ID           int64
	UserID       int64
	Name         string
	KeyPrefix    string
	KeyPlaintext pgtype.Text
	LastUsedAt   pgtype.Timestamptz
	ExpiresAt    pgtype.Timestamptz
	DisabledAt   pgtype.Timestamptz
	RevokedAt    pgtype.Timestamptz
	SpendLimit   pgtype.Numeric
	SpentTotal   pgtype.Numeric
	RouteID      int64
	RpmLimit     pgtype.Int4
	TpmLimit     pgtype.Int4
	RpdLimit     pgtype.Int4
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

// SetAPIKeyRateLimits 设置/清除 API Key 的令牌级限流上限（P2-8）；各列 NULL=继承全局默认，0=不限，>0=具体上限。
func (q *Queries) SetAPIKeyRateLimits(ctx context.Context, arg SetAPIKeyRateLimitsParams) (SetAPIKeyRateLimitsRow, error) {
	row := q.db.QueryRow(ctx, setAPIKeyRateLimits,
		arg.RpmLimit,
		arg.TpmLimit,
		arg.RpdLimit,
		arg.ID,
	)
	var i SetAPIKeyRateLimitsRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.KeyPrefix,
		&i.KeyPlaintext,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.DisabledAt,
		&i.RevokedAt,
		&i.SpendLimit,
		&i.SpentTotal,
		&i.RouteID,
		&i.RpmLimit,
		&i.TpmLimit,
		&i.RpdLimit,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setAPIKeyRoute = `-- name: SetAPIKeyRoute :one
UPDATE api_keys
SET route_id = $1, updated_at = now()
WHERE id = $2
RETURNING id, user_id, name, key_prefix, key_plaintext, last_used_at, expires_at, disabled_at, revoked_at, spend_limit, spent_total, route_id, rpm_limit, tpm_limit, rpd_limit, created_at, updated_at
`

type SetAPIKeyRouteParams struct {
	RouteID int64
	ID      int64
}

type SetAPIKeyRouteRow struct {
	ID           int64
	UserID       int64
	Name         string
	KeyPrefix    string
	KeyPlaintext pgtype.Text
	LastUsedAt   pgtype.Timestamptz
	ExpiresAt    pgtype.Timestamptz
	DisabledAt   pgtype.Timestamptz
	RevokedAt    pgtype.Timestamptz
	SpendLimit   pgtype.Numeric
	SpentTotal   pgtype.Numeric
	RouteID      int64
	RpmLimit     pgtype.Int4
	TpmLimit     pgtype.Int4
	RpdLimit     pgtype.Int4
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

// SetAPIKeyRoute 改绑 API Key 的线路；route_id 必填（线路不可清空，必须指向一条线路）。
func (q *Queries) SetAPIKeyRoute(ctx context.Context, arg SetAPIKeyRouteParams) (SetAPIKeyRouteRow, error) {
	row := q.db.QueryRow(ctx, setAPIKeyRoute, arg.RouteID, arg.ID)
	var i SetAPIKeyRouteRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.KeyPrefix,
		&i.KeyPlaintext,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.DisabledAt,
		&i.RevokedAt,
		&i.SpendLimit,
		&i.SpentTotal,
		&i.RouteID,
		&i.RpmLimit,
		&i.TpmLimit,
		&i.RpdLimit,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setAPIKeySpendLimit = `-- name: SetAPIKeySpendLimit :one
UPDATE api_keys
SET spend_limit = $1, updated_at = now()
WHERE id = $2
RETURNING id, user_id, name, key_prefix, key_plaintext, last_used_at, expires_at, disabled_at, revoked_at, spend_limit, spent_total, route_id, rpm_limit, tpm_limit, rpd_limit, created_at, updated_at
`

type SetAPIKeySpendLimitParams struct {
	SpendLimit pgtype.Numeric
	ID         int64
}

type SetAPIKeySpendLimitRow struct {
	ID           int64
	UserID       int64
	Name         string
	KeyPrefix    string
	KeyPlaintext pgtype.Text
	LastUsedAt   pgtype.Timestamptz
	ExpiresAt    pgtype.Timestamptz
	DisabledAt   pgtype.Timestamptz
	RevokedAt    pgtype.Timestamptz
	SpendLimit   pgtype.Numeric
	SpentTotal   pgtype.Numeric
	RouteID      int64
	RpmLimit     pgtype.Int4
	TpmLimit     pgtype.Int4
	RpdLimit     pgtype.Int4
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

// SetAPIKeySpendLimit 设置/清除 API Key 费用上限；spend_limit 为 NULL 表示不限额。
func (q *Queries) SetAPIKeySpendLimit(ctx context.Context, arg SetAPIKeySpendLimitParams) (SetAPIKeySpendLimitRow, error) {
	row := q.db.QueryRow(ctx, setAPIKeySpendLimit, arg.SpendLimit, arg.ID)
	var i SetAPIKeySpendLimitRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.KeyPrefix,
		&i.KeyPlaintext,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.DisabledAt,
		&i.RevokedAt,
		&i.SpendLimit,
		&i.SpentTotal,
		&i.RouteID,
		&i.RpmLimit,
		&i.TpmLimit,
		&i.RpdLimit,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAPIKeyLastUsedAt = `-- name: UpdateAPIKeyLastUsedAt :exec
UPDATE api_keys
SET last_used_at = $1, updated_at = now()
WHERE id = $2
`

type UpdateAPIKeyLastUsedAtParams struct {
	LastUsedAt pgtype.Timestamptz
	ID         int64
}

// UpdateAPIKeyLastUsedAt 更新 API Key 最近使用时间。
func (q *Queries) UpdateAPIKeyLastUsedAt(ctx context.Context, arg UpdateAPIKeyLastUsedAtParams) error {
	_, err := q.db.Exec(ctx, updateAPIKeyLastUsedAt, arg.LastUsedAt, arg.ID)
	return err
}
