// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: channel_prices.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const findActiveChannelPrice = `-- name: FindActiveChannelPrice :one
SELECT id, channel_id, model_id, currency, pricing_unit, uncached_input_cost, cache_read_input_cost, cache_write_5m_input_cost, cache_write_1h_input_cost, output_cost, reasoning_output_cost, status, effective_from, effective_to, created_at, updated_at, cache_write_30m_input_cost
FROM channel_prices
WHERE channel_id = $1
    AND model_id = $2
    AND status = 'enabled'
    AND effective_from <= $3
    AND (
        effective_to IS NULL
        OR effective_to > $3
    )
ORDER BY effective_from DESC, id DESC
LIMIT 1
`

type FindActiveChannelPriceParams struct {
	ChannelID int64
	ModelID   int64
	AtTime    pgtype.Timestamptz
}

// FindActiveChannelPrice 查找指定 channel/model 在指定时间生效的渠道-模型价，一次取回售价 + 成本（阶段 15 计费同源）。
func (q *Queries) FindActiveChannelPrice(ctx context.Context, arg FindActiveChannelPriceParams) (ChannelPrice, error) {
	row := q.db.QueryRow(ctx, findActiveChannelPrice, arg.ChannelID, arg.ModelID, arg.AtTime)
	var i ChannelPrice
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.ModelID,
		&i.Currency,
		&i.PricingUnit,
		&i.UncachedInputCost,
		&i.CacheReadInputCost,
		&i.CacheWrite5mInputCost,
		&i.CacheWrite1hInputCost,
		&i.OutputCost,
		&i.ReasoningOutputCost,
		&i.Status,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CacheWrite30mInputCost,
	)
	return i, err
}

const getChannelPrice = `-- name: GetChannelPrice :one
SELECT id, channel_id, model_id, currency, pricing_unit, uncached_input_cost, cache_read_input_cost, cache_write_5m_input_cost, cache_write_1h_input_cost, output_cost, reasoning_output_cost, status, effective_from, effective_to, created_at, updated_at, cache_write_30m_input_cost FROM channel_prices WHERE id = $1 LIMIT 1
`

// GetChannelPrice 按主键读取单条渠道-模型价。
func (q *Queries) GetChannelPrice(ctx context.Context, id int64) (ChannelPrice, error) {
	row := q.db.QueryRow(ctx, getChannelPrice, id)
	var i ChannelPrice
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.ModelID,
		&i.Currency,
		&i.PricingUnit,
		&i.UncachedInputCost,
		&i.CacheReadInputCost,
		&i.CacheWrite5mInputCost,
		&i.CacheWrite1hInputCost,
		&i.OutputCost,
		&i.ReasoningOutputCost,
		&i.Status,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CacheWrite30mInputCost,
	)
	return i, err
}
