// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: channels.sql

package sqlc

import (
	"context"
)

const listChannelsForCredentialTest = `-- name: ListChannelsForCredentialTest :many
SELECT id, provider_id, name, protocol, adapter_key, base_url, credential, status, priority, timeout_ms, created_at, updated_at, rpm_limit, tpm_limit, rpd_limit, last_tested_at, last_test_ok, last_test_latency_ms, last_test_error, credential_valid, archived_at, concurrency_limit, upstream_bills_on_disconnect
FROM channels
WHERE status = 'enabled'
ORDER BY credential_valid ASC, priority, id
`

// ListChannelsForCredentialTest 供渠道自动检测 worker 巡检：所有启用渠道（含 credential_valid=false 以便恢复），
// 失效的排在前面（优先复检以尽快恢复），再按 priority、id。
func (q *Queries) ListChannelsForCredentialTest(ctx context.Context) ([]Channel, error) {
	rows, err := q.db.Query(ctx, listChannelsForCredentialTest)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Channel
	for rows.Next() {
		var i Channel
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.Name,
			&i.Protocol,
			&i.AdapterKey,
			&i.BaseUrl,
			&i.Credential,
			&i.Status,
			&i.Priority,
			&i.TimeoutMs,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RpmLimit,
			&i.TpmLimit,
			&i.RpdLimit,
			&i.LastTestedAt,
			&i.LastTestOk,
			&i.LastTestLatencyMs,
			&i.LastTestError,
			&i.CredentialValid,
			&i.ArchivedAt,
			&i.ConcurrencyLimit,
			&i.UpstreamBillsOnDisconnect,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnabledChannelAdapters = `-- name: ListEnabledChannelAdapters :many
SELECT
    c.id AS channel_id,
    c.protocol,
    c.adapter_key,
    p.slug AS provider_slug
FROM channels c
JOIN providers p ON p.id = c.provider_id
WHERE c.status = 'enabled'
  AND p.status = 'enabled'
ORDER BY c.id
`

type ListEnabledChannelAdaptersRow struct {
	ChannelID    int64
	Protocol     string
	AdapterKey   string
	ProviderSlug string
}

// ListEnabledChannelAdapters 列出启用 provider 下启用 channel 的协议与 adapter 注册键，供启动期 preflight 校验 channel 运行时绑定是否被当前进程支持。
func (q *Queries) ListEnabledChannelAdapters(ctx context.Context) ([]ListEnabledChannelAdaptersRow, error) {
	rows, err := q.db.Query(ctx, listEnabledChannelAdapters)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEnabledChannelAdaptersRow
	for rows.Next() {
		var i ListEnabledChannelAdaptersRow
		if err := rows.Scan(
			&i.ChannelID,
			&i.Protocol,
			&i.AdapterKey,
			&i.ProviderSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setChannelCredentialInvalid = `-- name: SetChannelCredentialInvalid :execrows
UPDATE channels
SET credential_valid = FALSE
WHERE id = $1 AND credential_valid = TRUE
`

// SetChannelCredentialInvalid 将渠道标记为「凭据失效」（阶段二闸门）。幂等：仅在 true→false 跳变时
// 写入并返回受影响行数=1，供调用方据此决定是否补写一条 channel_test_logs（避免重复写日志）。
// 不改 status（与管理员启停正交），不改 updated_at（这是系统遥测，非配置变更）。
func (q *Queries) SetChannelCredentialInvalid(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, setChannelCredentialInvalid, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
