// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: channel.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const applyChannelProbeResult = `-- name: ApplyChannelProbeResult :one
WITH matching AS MATERIALIZED (
    SELECT c.id, c.credential_valid
    FROM channels c
    JOIN provider_endpoints pe ON pe.id = c.provider_endpoint_id
    WHERE c.id = $1
      AND c.config_revision = $2
      AND pe.base_url_revision = $3
      AND pe.status_revision = $4
    FOR UPDATE OF c
), applied AS (
    UPDATE channels AS c
    SET last_tested_at = now(),
        last_test_ok = $5,
        last_test_latency_ms = $6,
        last_test_error = $7,
        credential_valid = COALESCE($8::boolean, c.credential_valid),
        config_revision = c.config_revision + CASE
            WHEN $8::boolean IS NOT NULL
             AND c.credential_valid IS DISTINCT FROM $8::boolean
            THEN 1 ELSE 0
        END,
        updated_at = CASE
            WHEN $8::boolean IS NOT NULL
             AND c.credential_valid IS DISTINCT FROM $8::boolean
            THEN now() ELSE c.updated_at
        END
    FROM matching
    WHERE c.id = matching.id
    RETURNING
        c.id,
        c.credential_valid,
        c.config_revision,
        (matching.credential_valid IS DISTINCT FROM c.credential_valid)::boolean AS state_change_applied
), current_state AS (
    SELECT
        applied.id,
        applied.credential_valid,
        applied.config_revision,
        TRUE AS result_applied,
        applied.state_change_applied
    FROM applied
    UNION ALL
    SELECT
        c.id,
        c.credential_valid,
        c.config_revision,
        FALSE AS result_applied,
        FALSE AS state_change_applied
    FROM channels c
    WHERE c.id = $1
      AND NOT EXISTS (SELECT 1 FROM applied)
    LIMIT 1
), logged AS (
    INSERT INTO channel_test_logs (
        channel_id,
        source,
        success,
        error_code,
        http_status,
        latency_ms,
        tested_model,
        credential_valid_after,
        message,
        upstream_error,
        tested_endpoint_base_url_revision,
        tested_endpoint_status_revision,
        tested_config_revision,
        state_change_applied
    )
    SELECT
        current_state.id,
        $9,
        $5,
        $10,
        $11,
        $6,
        $12,
        current_state.credential_valid,
        $7,
        $13,
        $3,
        $4,
        $2,
        current_state.state_change_applied
    FROM current_state
    RETURNING channel_id, credential_valid_after, state_change_applied
)
SELECT
    current_state.result_applied,
    logged.state_change_applied,
    logged.credential_valid_after,
    current_state.config_revision AS current_config_revision
FROM current_state
JOIN logged ON logged.channel_id = current_state.id
`

type ApplyChannelProbeResultParams struct {
	ChannelID                       int64
	ExpectedConfigRevision          int64
	ExpectedEndpointBaseUrlRevision int64
	ExpectedEndpointStatusRevision  int64
	Success                         pgtype.Bool
	LastTestLatencyMs               pgtype.Int4
	LastTestError                   pgtype.Text
	NextCredentialValid             pgtype.Bool
	Source                          string
	ErrorCode                       pgtype.Text
	HttpStatus                      pgtype.Int4
	TestedModel                     pgtype.Text
	UpstreamError                   pgtype.Text
}

type ApplyChannelProbeResultRow struct {
	ResultApplied         bool
	StateChangeApplied    bool
	CredentialValidAfter  bool
	CurrentConfigRevision int64
}

// ApplyChannelProbeResult 按 Channel config + Endpoint BaseURL/status 三类 expected revision 原子应用检测摘要与 credential_valid，
// 并无论 current/stale 都写一条带 tested revisions 的历史日志；stale 结果不覆盖当前摘要或凭据状态。
func (q *Queries) ApplyChannelProbeResult(ctx context.Context, arg ApplyChannelProbeResultParams) (ApplyChannelProbeResultRow, error) {
	row := q.db.QueryRow(ctx, applyChannelProbeResult,
		arg.ChannelID,
		arg.ExpectedConfigRevision,
		arg.ExpectedEndpointBaseUrlRevision,
		arg.ExpectedEndpointStatusRevision,
		arg.Success,
		arg.LastTestLatencyMs,
		arg.LastTestError,
		arg.NextCredentialValid,
		arg.Source,
		arg.ErrorCode,
		arg.HttpStatus,
		arg.TestedModel,
		arg.UpstreamError,
	)
	var i ApplyChannelProbeResultRow
	err := row.Scan(
		&i.ResultApplied,
		&i.StateChangeApplied,
		&i.CredentialValidAfter,
		&i.CurrentConfigRevision,
	)
	return i, err
}

const archiveChannelCascade = `-- name: ArchiveChannelCascade :execrows
WITH cleared_pools AS (
    DELETE FROM route_channels WHERE channel_id = $1
)
UPDATE channels
SET status = 'archived', archived_at = now(), name = name || '__archived_' || id::text,
    config_revision = config_revision + 1, updated_at = now()
WHERE channels.id = $1 AND channels.status <> 'archived'
`

// ArchiveChannelCascade 归档单个渠道：从所有线路候选池移除（删 route_channels 行）、置 archived、
// 释放渠道名（追加 __archived_<id> 后缀释放 (provider_id, name) 槽位供复用）。不动 provider。
// 返回 channels 受影响行数（0 = 渠道不存在或已归档）。恢复保持后缀名、不自动重加线路池。
func (q *Queries) ArchiveChannelCascade(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, archiveChannelCascade, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const archiveChannelWithReplacement = `-- name: ArchiveChannelWithReplacement :one
WITH replacement AS (
    SELECT c.id
    FROM channels c
    JOIN providers p ON p.id = c.provider_id
    JOIN provider_endpoints pe ON pe.id = c.provider_endpoint_id
    WHERE c.id = $1
      AND c.id <> $2
      AND c.status = 'enabled'
      AND c.credential_valid
      AND c.credential <> ''
      AND pe.base_url <> ''
      AND pe.status = 'enabled'
      AND p.status = 'enabled'
),
affected_routes AS (
    SELECT route_id FROM route_channels WHERE channel_id = $2
),
added AS (
    INSERT INTO route_channels (route_id, channel_id)
    SELECT ar.route_id, replacement.id
    FROM affected_routes ar CROSS JOIN replacement
    ON CONFLICT (route_id, channel_id) DO NOTHING
    RETURNING route_id
),
archived AS (
    UPDATE channels
    SET status = 'archived', archived_at = now(), name = name || '__archived_' || id::text,
        config_revision = config_revision + 1, updated_at = now()
    WHERE channels.id = $2
      AND channels.status <> 'archived'
      AND EXISTS (SELECT 1 FROM replacement)
      AND (SELECT COUNT(*) FROM added) >= 0
    RETURNING id
),
cleared AS (
    DELETE FROM route_channels WHERE channel_id IN (SELECT id FROM archived)
    RETURNING route_id
)
SELECT COUNT(*)::bigint FROM archived WHERE (SELECT COUNT(*) FROM cleared) >= 0
`

type ArchiveChannelWithReplacementParams struct {
	ReplacementChannelID int64
	ID                   int64
}

// Atomically add one healthy replacement to every affected route, then archive/remove the target.
func (q *Queries) ArchiveChannelWithReplacement(ctx context.Context, arg ArchiveChannelWithReplacementParams) (int64, error) {
	row := q.db.QueryRow(ctx, archiveChannelWithReplacement, arg.ReplacementChannelID, arg.ID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const channelOpsDetail = `-- name: ChannelOpsDetail :one
SELECT
    COUNT(*) FILTER (WHERE status = 'succeeded' OR fault_party = 'upstream') AS attempt_total,
    COUNT(*) FILTER (WHERE status = 'succeeded') AS attempt_succeeded,
    COUNT(*) FILTER (WHERE status = 'failed' AND (error_code ILIKE '%timeout%' OR error_code = 'context_deadline_exceeded')) AS timeout_total,
    COUNT(*) FILTER (WHERE status = 'succeeded' AND completed_at IS NOT NULL) AS latency_sample,
    COALESCE(AVG(CASE WHEN status = 'succeeded' AND completed_at IS NOT NULL
        THEN (EXTRACT(EPOCH FROM (completed_at - started_at)) * 1000)::float8 END), 0)::float8 AS latency_avg,
    COALESCE(percentile_cont(0.5) WITHIN GROUP (ORDER BY
        CASE WHEN status = 'succeeded' AND completed_at IS NOT NULL
             THEN (EXTRACT(EPOCH FROM (completed_at - started_at)) * 1000)::float8 END), 0)::float8 AS latency_p50,
    COALESCE(percentile_cont(0.9) WITHIN GROUP (ORDER BY
        CASE WHEN status = 'succeeded' AND completed_at IS NOT NULL
             THEN (EXTRACT(EPOCH FROM (completed_at - started_at)) * 1000)::float8 END), 0)::float8 AS latency_p90,
    COALESCE(percentile_cont(0.95) WITHIN GROUP (ORDER BY
        CASE WHEN status = 'succeeded' AND completed_at IS NOT NULL
             THEN (EXTRACT(EPOCH FROM (completed_at - started_at)) * 1000)::float8 END), 0)::float8 AS latency_p95,
    COALESCE(percentile_cont(0.99) WITHIN GROUP (ORDER BY
        CASE WHEN status = 'succeeded' AND completed_at IS NOT NULL
             THEN (EXTRACT(EPOCH FROM (completed_at - started_at)) * 1000)::float8 END), 0)::float8 AS latency_p99,
    (MAX(completed_at) FILTER (WHERE status = 'succeeded'))::timestamptz AS last_success_at,
    (MAX(completed_at) FILTER (WHERE status = 'failed' AND fault_party = 'upstream'))::timestamptz AS last_failure_at
FROM request_attempts
WHERE channel_id = $1
  AND ($2::timestamptz IS NULL OR created_at >= $2::timestamptz)
  AND ($3::timestamptz IS NULL OR created_at < $3::timestamptz)
`

type ChannelOpsDetailParams struct {
	ChannelID int64
	FromTime  pgtype.Timestamptz
	ToTime    pgtype.Timestamptz
}

type ChannelOpsDetailRow struct {
	AttemptTotal     int64
	AttemptSucceeded int64
	TimeoutTotal     int64
	LatencySample    int64
	LatencyAvg       float64
	LatencyP50       float64
	LatencyP90       float64
	LatencyP95       float64
	LatencyP99       float64
	LastSuccessAt    pgtype.Timestamptz
	LastFailureAt    pgtype.Timestamptz
}

// ChannelOpsDetail 单渠道（抽屉概览）attempt 指标。attempt_total 口径同上：合格 attempt（succeeded+failed）。
func (q *Queries) ChannelOpsDetail(ctx context.Context, arg ChannelOpsDetailParams) (ChannelOpsDetailRow, error) {
	row := q.db.QueryRow(ctx, channelOpsDetail, arg.ChannelID, arg.FromTime, arg.ToTime)
	var i ChannelOpsDetailRow
	err := row.Scan(
		&i.AttemptTotal,
		&i.AttemptSucceeded,
		&i.TimeoutTotal,
		&i.LatencySample,
		&i.LatencyAvg,
		&i.LatencyP50,
		&i.LatencyP90,
		&i.LatencyP95,
		&i.LatencyP99,
		&i.LastSuccessAt,
		&i.LastFailureAt,
	)
	return i, err
}

const channelOpsErrors = `-- name: ChannelOpsErrors :many
SELECT
    a.created_at,
    a.upstream_model,
    a.error_code,
    a.upstream_status_code,
    a.error_message,
    r.request_id
FROM request_attempts a
JOIN request_records r ON r.id = a.request_record_id
WHERE a.channel_id = $1
  AND a.status = 'failed'
  AND ($2::timestamptz IS NULL OR a.created_at >= $2::timestamptz)
  AND ($3::timestamptz IS NULL OR a.created_at < $3::timestamptz)
ORDER BY a.created_at DESC
LIMIT $5 OFFSET $4
`

type ChannelOpsErrorsParams struct {
	ChannelID  int64
	FromTime   pgtype.Timestamptz
	ToTime     pgtype.Timestamptz
	PageOffset int32
	PageLimit  int32
}

type ChannelOpsErrorsRow struct {
	CreatedAt          pgtype.Timestamptz
	UpstreamModel      string
	ErrorCode          pgtype.Text
	UpstreamStatusCode pgtype.Int4
	ErrorMessage       pgtype.Text
	RequestID          string
}

// ChannelOpsErrors 单渠道错误明细（抽屉错误 Tab，分页）。携带 request_id 便于跳证据中心。
func (q *Queries) ChannelOpsErrors(ctx context.Context, arg ChannelOpsErrorsParams) ([]ChannelOpsErrorsRow, error) {
	rows, err := q.db.Query(ctx, channelOpsErrors,
		arg.ChannelID,
		arg.FromTime,
		arg.ToTime,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChannelOpsErrorsRow
	for rows.Next() {
		var i ChannelOpsErrorsRow
		if err := rows.Scan(
			&i.CreatedAt,
			&i.UpstreamModel,
			&i.ErrorCode,
			&i.UpstreamStatusCode,
			&i.ErrorMessage,
			&i.RequestID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const channelOpsErrorsCount = `-- name: ChannelOpsErrorsCount :one
SELECT COUNT(*) AS total
FROM request_attempts a
WHERE a.channel_id = $1
  AND a.status = 'failed'
  AND ($2::timestamptz IS NULL OR a.created_at >= $2::timestamptz)
  AND ($3::timestamptz IS NULL OR a.created_at < $3::timestamptz)
`

type ChannelOpsErrorsCountParams struct {
	ChannelID int64
	FromTime  pgtype.Timestamptz
	ToTime    pgtype.Timestamptz
}

func (q *Queries) ChannelOpsErrorsCount(ctx context.Context, arg ChannelOpsErrorsCountParams) (int64, error) {
	row := q.db.QueryRow(ctx, channelOpsErrorsCount, arg.ChannelID, arg.FromTime, arg.ToTime)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const channelOpsModels = `-- name: ChannelOpsModels :many
SELECT
    cm.model_id,
    m.model_id AS model_ref,
    m.display_name,
    cm.upstream_model,
    cm.status,
    COUNT(a.id) FILTER (WHERE a.status = 'succeeded' OR a.fault_party = 'upstream') AS attempt_total,
    COUNT(a.id) FILTER (WHERE a.status = 'succeeded') AS attempt_succeeded,
    COUNT(a.id) FILTER (WHERE a.status = 'succeeded' AND a.completed_at IS NOT NULL) AS latency_sample,
    COALESCE(AVG(CASE WHEN a.status = 'succeeded' AND a.completed_at IS NOT NULL
        THEN (EXTRACT(EPOCH FROM (a.completed_at - a.started_at)) * 1000)::float8 END), 0)::float8 AS latency_avg,
    COALESCE(percentile_cont(0.5) WITHIN GROUP (ORDER BY
        CASE WHEN a.status = 'succeeded' AND a.completed_at IS NOT NULL
             THEN (EXTRACT(EPOCH FROM (a.completed_at - a.started_at)) * 1000)::float8 END), 0)::float8 AS latency_p50,
    COALESCE(percentile_cont(0.9) WITHIN GROUP (ORDER BY
        CASE WHEN a.status = 'succeeded' AND a.completed_at IS NOT NULL
             THEN (EXTRACT(EPOCH FROM (a.completed_at - a.started_at)) * 1000)::float8 END), 0)::float8 AS latency_p90,
    COALESCE(percentile_cont(0.95) WITHIN GROUP (ORDER BY
        CASE WHEN a.status = 'succeeded' AND a.completed_at IS NOT NULL
             THEN (EXTRACT(EPOCH FROM (a.completed_at - a.started_at)) * 1000)::float8 END), 0)::float8 AS latency_p95,
    COALESCE(percentile_cont(0.99) WITHIN GROUP (ORDER BY
        CASE WHEN a.status = 'succeeded' AND a.completed_at IS NOT NULL
             THEN (EXTRACT(EPOCH FROM (a.completed_at - a.started_at)) * 1000)::float8 END), 0)::float8 AS latency_p99,
    -- has_price（DEC-031）：该 (渠道,模型) 可解析成本——绝对覆盖 OR （模型有生效基准价 AND 渠道对本模型有生效价格倍率，含默认）；与路由「可卖」对齐。
    -- 用单一顶层 EXISTS (SELECT 1 WHERE <条件>) 让 sqlc 推断为非空 bool（复合布尔/COALESCE 会被推断为可空或 interface{}）。
    EXISTS (
        SELECT 1 WHERE
            EXISTS (
                SELECT 1 FROM channel_prices p
                WHERE p.channel_id = $1 AND p.model_id = cm.model_id AND p.status = 'enabled'
                  AND p.effective_from <= now() AND (p.effective_to IS NULL OR p.effective_to > now())
            )
            OR (
                EXISTS (
                    SELECT 1 FROM model_prices mp
                    WHERE mp.model_id = cm.model_id AND mp.status = 'enabled'
                      AND mp.effective_from <= now() AND (mp.effective_to IS NULL OR mp.effective_to > now())
                )
                AND EXISTS (
                    SELECT 1 FROM channel_cost_multipliers ccm
                    WHERE ccm.channel_id = $1
                      AND (ccm.model_id = cm.model_id OR ccm.model_id IS NULL)
                      AND ccm.status = 'enabled'
                      AND ccm.effective_from <= now() AND (ccm.effective_to IS NULL OR ccm.effective_to > now())
                )
            )
    ) AS has_price
FROM channel_models cm
JOIN models m ON m.id = cm.model_id
LEFT JOIN request_attempts a
    ON a.channel_id = cm.channel_id
    AND a.upstream_model = cm.upstream_model
    AND ($2::timestamptz IS NULL OR a.created_at >= $2::timestamptz)
    AND ($3::timestamptz IS NULL OR a.created_at < $3::timestamptz)
WHERE cm.channel_id = $1
GROUP BY cm.model_id, m.model_id, m.display_name, cm.upstream_model, cm.status
ORDER BY attempt_total DESC, m.model_id
`

type ChannelOpsModelsParams struct {
	ChannelID int64
	FromTime  pgtype.Timestamptz
	ToTime    pgtype.Timestamptz
}

type ChannelOpsModelsRow struct {
	ModelID          int64
	ModelRef         string
	DisplayName      string
	UpstreamModel    string
	Status           string
	AttemptTotal     int64
	AttemptSucceeded int64
	LatencySample    int64
	LatencyAvg       float64
	LatencyP50       float64
	LatencyP90       float64
	LatencyP95       float64
	LatencyP99       float64
	HasPrice         bool
}

// ChannelOpsModels 单渠道绑定模型 + attempt 指标（抽屉模型 Tab，完整列 §1.8）。
// attempt 无 model_id，按 upstream_model 关联绑定。
func (q *Queries) ChannelOpsModels(ctx context.Context, arg ChannelOpsModelsParams) ([]ChannelOpsModelsRow, error) {
	rows, err := q.db.Query(ctx, channelOpsModels, arg.ChannelID, arg.FromTime, arg.ToTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChannelOpsModelsRow
	for rows.Next() {
		var i ChannelOpsModelsRow
		if err := rows.Scan(
			&i.ModelID,
			&i.ModelRef,
			&i.DisplayName,
			&i.UpstreamModel,
			&i.Status,
			&i.AttemptTotal,
			&i.AttemptSucceeded,
			&i.LatencySample,
			&i.LatencyAvg,
			&i.LatencyP50,
			&i.LatencyP90,
			&i.LatencyP95,
			&i.LatencyP99,
			&i.HasPrice,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const channelOpsPerformanceTimeseries = `-- name: ChannelOpsPerformanceTimeseries :many
SELECT
    date_trunc($1::text, created_at)::timestamptz AS bucket,
    COUNT(*) FILTER (WHERE status = 'succeeded' OR fault_party = 'upstream') AS attempt_total,
    COUNT(*) FILTER (WHERE status = 'succeeded') AS attempt_succeeded,
    COALESCE(AVG(CASE WHEN status = 'succeeded' AND completed_at IS NOT NULL
        THEN (EXTRACT(EPOCH FROM (completed_at - started_at)) * 1000)::float8 END), 0)::float8 AS latency_avg
FROM request_attempts
WHERE channel_id = $2
  AND ($3::timestamptz IS NULL OR created_at >= $3::timestamptz)
  AND ($4::timestamptz IS NULL OR created_at < $4::timestamptz)
GROUP BY bucket
ORDER BY bucket
`

type ChannelOpsPerformanceTimeseriesParams struct {
	Unit      string
	ChannelID int64
	FromTime  pgtype.Timestamptz
	ToTime    pgtype.Timestamptz
}

type ChannelOpsPerformanceTimeseriesRow struct {
	Bucket           pgtype.Timestamptz
	AttemptTotal     int64
	AttemptSucceeded int64
	LatencyAvg       float64
}

// ChannelOpsPerformanceTimeseries 单渠道按时间桶的 attempt 量/成功/平均延迟（抽屉性能 Tab）。
func (q *Queries) ChannelOpsPerformanceTimeseries(ctx context.Context, arg ChannelOpsPerformanceTimeseriesParams) ([]ChannelOpsPerformanceTimeseriesRow, error) {
	rows, err := q.db.Query(ctx, channelOpsPerformanceTimeseries,
		arg.Unit,
		arg.ChannelID,
		arg.FromTime,
		arg.ToTime,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChannelOpsPerformanceTimeseriesRow
	for rows.Next() {
		var i ChannelOpsPerformanceTimeseriesRow
		if err := rows.Scan(
			&i.Bucket,
			&i.AttemptTotal,
			&i.AttemptSucceeded,
			&i.LatencyAvg,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const channelOpsRoutes = `-- name: ChannelOpsRoutes :many
SELECT rt.id, rt.name, rt.mode, rt.status, rt.price_ratio
FROM route_channels rc
JOIN routes rt ON rt.id = rc.route_id
WHERE rc.channel_id = $1
ORDER BY rt.id
`

type ChannelOpsRoutesRow struct {
	ID         int64
	Name       string
	Mode       string
	Status     string
	PriceRatio pgtype.Numeric
}

// ChannelOpsRoutes 引用该渠道的线路池（抽屉线路 Tab）。
func (q *Queries) ChannelOpsRoutes(ctx context.Context, channelID int64) ([]ChannelOpsRoutesRow, error) {
	rows, err := q.db.Query(ctx, channelOpsRoutes, channelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChannelOpsRoutesRow
	for rows.Next() {
		var i ChannelOpsRoutesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Mode,
			&i.Status,
			&i.PriceRatio,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const channelsOpsTable = `-- name: ChannelsOpsTable :many

SELECT
    c.id,
    c.name,
    c.status,
    c.protocol,
    c.adapter_key,
    pe.base_url,
    c.priority,
    c.timeout_ms,
    c.credential,
    c.rpm_limit,
    c.tpm_limit,
    c.rpd_limit,
    c.created_at,
    c.last_tested_at,
    c.last_test_ok,
    c.last_test_latency_ms,
    c.last_test_error,
    c.credential_valid,
    (
        SELECT ccm.multiplier
        FROM channel_cost_multipliers ccm
        WHERE ccm.channel_id = c.id
          AND ccm.model_id IS NULL
          AND ccm.status = 'enabled'
          AND ccm.effective_from <= now()
          AND (ccm.effective_to IS NULL OR ccm.effective_to > now())
        ORDER BY ccm.effective_from DESC, ccm.id DESC
        LIMIT 1
    ) AS cost_multiplier,
    (
        SELECT COUNT(*)::bigint
        FROM channel_cost_multipliers ccm
        WHERE ccm.channel_id = c.id
          AND ccm.model_id IS NOT NULL
          AND ccm.status = 'enabled'
          AND ccm.effective_from <= now()
          AND (ccm.effective_to IS NULL OR ccm.effective_to > now())
    ) AS cost_multiplier_overrides,
    (
        SELECT crf.factor
        FROM channel_recharge_factors crf
        WHERE crf.channel_id = c.id
          AND crf.status = 'enabled'
          AND crf.effective_from <= now()
          AND (crf.effective_to IS NULL OR crf.effective_to > now())
        ORDER BY crf.effective_from DESC, crf.id DESC
        LIMIT 1
    ) AS recharge_factor,
    pr.name AS provider_name,
    COUNT(a.id) FILTER (WHERE a.status = 'succeeded' OR a.fault_party = 'upstream') AS attempt_total,
    COUNT(a.id) FILTER (WHERE a.status = 'succeeded') AS attempt_succeeded,
    COUNT(a.id) FILTER (WHERE a.status = 'failed' AND (a.error_code ILIKE '%timeout%' OR a.error_code = 'context_deadline_exceeded')) AS timeout_total,
    COUNT(a.id) FILTER (WHERE a.status = 'succeeded' AND a.completed_at IS NOT NULL) AS latency_sample,
    COALESCE(AVG(CASE WHEN a.status = 'succeeded' AND a.completed_at IS NOT NULL
        THEN (EXTRACT(EPOCH FROM (a.completed_at - a.started_at)) * 1000)::float8 END), 0)::float8 AS latency_avg,
    COALESCE(percentile_cont(0.5) WITHIN GROUP (ORDER BY
        CASE WHEN a.status = 'succeeded' AND a.completed_at IS NOT NULL
             THEN (EXTRACT(EPOCH FROM (a.completed_at - a.started_at)) * 1000)::float8 END), 0)::float8 AS latency_p50,
    COALESCE(percentile_cont(0.9) WITHIN GROUP (ORDER BY
        CASE WHEN a.status = 'succeeded' AND a.completed_at IS NOT NULL
             THEN (EXTRACT(EPOCH FROM (a.completed_at - a.started_at)) * 1000)::float8 END), 0)::float8 AS latency_p90,
    COALESCE(percentile_cont(0.95) WITHIN GROUP (ORDER BY
        CASE WHEN a.status = 'succeeded' AND a.completed_at IS NOT NULL
             THEN (EXTRACT(EPOCH FROM (a.completed_at - a.started_at)) * 1000)::float8 END), 0)::float8 AS latency_p95,
    COALESCE(percentile_cont(0.99) WITHIN GROUP (ORDER BY
        CASE WHEN a.status = 'succeeded' AND a.completed_at IS NOT NULL
             THEN (EXTRACT(EPOCH FROM (a.completed_at - a.started_at)) * 1000)::float8 END), 0)::float8 AS latency_p99,
    (SELECT COUNT(*) FROM channel_models cm WHERE cm.channel_id = c.id AND cm.status = 'enabled') AS bound_models,
    (SELECT COUNT(*) FROM route_channels rc WHERE rc.channel_id = c.id) AS bound_routes,
    (
        SELECT a2.error_code FROM request_attempts a2
        WHERE a2.channel_id = c.id AND a2.status = 'failed' AND a2.fault_party = 'upstream' AND a2.error_code IS NOT NULL
          AND ($1::timestamptz IS NULL OR a2.created_at >= $1::timestamptz)
          AND ($2::timestamptz IS NULL OR a2.created_at < $2::timestamptz)
        ORDER BY a2.created_at DESC LIMIT 1
    ) AS recent_error_code
FROM channels c
JOIN providers pr ON pr.id = c.provider_id
JOIN provider_endpoints pe ON pe.id = c.provider_endpoint_id
LEFT JOIN request_attempts a
    ON a.channel_id = c.id
    AND ($1::timestamptz IS NULL OR a.created_at >= $1::timestamptz)
    AND ($2::timestamptz IS NULL OR a.created_at < $2::timestamptz)
WHERE ($3::text IS NULL OR c.status = $3::text)
  AND ($4::bigint IS NULL OR c.provider_id = $4::bigint)
  AND ($5::text IS NULL OR c.name ILIKE '%' || $5::text || '%')
GROUP BY c.id, c.name, c.status, c.protocol, c.adapter_key, pe.base_url, c.priority, c.timeout_ms, c.credential, c.rpm_limit, c.tpm_limit, c.rpd_limit, c.created_at, c.last_tested_at, c.last_test_ok, c.last_test_latency_ms, c.last_test_error, c.credential_valid, pr.name
ORDER BY
  CASE WHEN COALESCE($6::text, 'success_rate') IN ('', 'success_rate') AND COALESCE($7::bool, false) THEN (COUNT(a.id) FILTER (WHERE a.status = 'succeeded')::float8 / NULLIF(COUNT(a.id) FILTER (WHERE a.status = 'succeeded' OR a.fault_party = 'upstream'), 0)) END DESC NULLS LAST,
  CASE WHEN COALESCE($6::text, 'success_rate') IN ('', 'success_rate') AND NOT COALESCE($7::bool, false) THEN (COUNT(a.id) FILTER (WHERE a.status = 'succeeded')::float8 / NULLIF(COUNT(a.id) FILTER (WHERE a.status = 'succeeded' OR a.fault_party = 'upstream'), 0)) END ASC NULLS LAST,
  CASE WHEN $6::text = 'name' AND COALESCE($7::bool, false) THEN c.name END DESC NULLS LAST,
  CASE WHEN $6::text = 'name' AND NOT COALESCE($7::bool, false) THEN c.name END ASC NULLS LAST,
  CASE WHEN $6::text = 'requests' AND COALESCE($7::bool, false) THEN COUNT(a.id) FILTER (WHERE a.status = 'succeeded' OR a.fault_party = 'upstream') END DESC NULLS LAST,
  CASE WHEN $6::text = 'requests' AND NOT COALESCE($7::bool, false) THEN COUNT(a.id) FILTER (WHERE a.status = 'succeeded' OR a.fault_party = 'upstream') END ASC NULLS LAST,
  CASE WHEN $6::text = 'status' AND COALESCE($7::bool, false) THEN c.status END DESC NULLS LAST,
  CASE WHEN $6::text = 'status' AND NOT COALESCE($7::bool, false) THEN c.status END ASC NULLS LAST,
  CASE WHEN $6::text = 'credential_valid' AND COALESCE($7::bool, false) THEN c.credential_valid END DESC NULLS LAST,
  CASE WHEN $6::text = 'credential_valid' AND NOT COALESCE($7::bool, false) THEN c.credential_valid END ASC NULLS LAST,
  CASE WHEN $6::text = 'created_at' AND COALESCE($7::bool, false) THEN c.created_at END DESC NULLS LAST,
  CASE WHEN $6::text = 'created_at' AND NOT COALESCE($7::bool, false) THEN c.created_at END ASC NULLS LAST,
  CASE WHEN $6::text = 'latency' AND COALESCE($7::bool, false) THEN COALESCE(AVG(CASE WHEN a.status = 'succeeded' AND a.completed_at IS NOT NULL THEN (EXTRACT(EPOCH FROM (a.completed_at - a.started_at)) * 1000)::float8 END), 0) END DESC NULLS LAST,
  CASE WHEN $6::text = 'latency' AND NOT COALESCE($7::bool, false) THEN COALESCE(AVG(CASE WHEN a.status = 'succeeded' AND a.completed_at IS NOT NULL THEN (EXTRACT(EPOCH FROM (a.completed_at - a.started_at)) * 1000)::float8 END), 0) END ASC NULLS LAST,
  CASE WHEN $6::text = 'timeout' AND COALESCE($7::bool, false) THEN COUNT(a.id) FILTER (WHERE a.status = 'failed' AND (a.error_code ILIKE '%timeout%' OR a.error_code = 'context_deadline_exceeded')) END DESC NULLS LAST,
  CASE WHEN $6::text = 'timeout' AND NOT COALESCE($7::bool, false) THEN COUNT(a.id) FILTER (WHERE a.status = 'failed' AND (a.error_code ILIKE '%timeout%' OR a.error_code = 'context_deadline_exceeded')) END ASC NULLS LAST,
  CASE WHEN $6::text = 'bound_models' AND COALESCE($7::bool, false) THEN (SELECT COUNT(*) FROM channel_models cm WHERE cm.channel_id = c.id AND cm.status = 'enabled') END DESC NULLS LAST,
  CASE WHEN $6::text = 'bound_models' AND NOT COALESCE($7::bool, false) THEN (SELECT COUNT(*) FROM channel_models cm WHERE cm.channel_id = c.id AND cm.status = 'enabled') END ASC NULLS LAST,
  c.id
LIMIT $9 OFFSET $8
`

type ChannelsOpsTableParams struct {
	FromTime   pgtype.Timestamptz
	ToTime     pgtype.Timestamptz
	Status     pgtype.Text
	ProviderID pgtype.Int8
	Search     pgtype.Text
	SortField  pgtype.Text
	SortDesc   pgtype.Bool
	PageOffset int32
	PageLimit  int32
}

type ChannelsOpsTableRow struct {
	ID                      int64
	Name                    string
	Status                  string
	Protocol                string
	AdapterKey              string
	BaseUrl                 string
	Priority                int32
	TimeoutMs               pgtype.Int4
	Credential              string
	RpmLimit                pgtype.Int4
	TpmLimit                pgtype.Int4
	RpdLimit                pgtype.Int4
	CreatedAt               pgtype.Timestamptz
	LastTestedAt            pgtype.Timestamptz
	LastTestOk              pgtype.Bool
	LastTestLatencyMs       pgtype.Int4
	LastTestError           pgtype.Text
	CredentialValid         bool
	CostMultiplier          pgtype.Numeric
	CostMultiplierOverrides int64
	RechargeFactor          pgtype.Numeric
	ProviderName            string
	AttemptTotal            int64
	AttemptSucceeded        int64
	TimeoutTotal            int64
	LatencySample           int64
	LatencyAvg              float64
	LatencyP50              float64
	LatencyP90              float64
	LatencyP95              float64
	LatencyP99              float64
	BoundModels             int64
	BoundRoutes             int64
	RecentErrorCode         pgtype.Text
}

// §3.3 渠道作战台只读运维聚合。全部只读。
// 口径：渠道性能/成功率/错误以 request_attempts（attempt 粒度，每次尝试命中一条渠道）为准；
// TPS/token 因无 per-attempt usage，按 request_records.final_channel_id 归因（最终成功渠道）。
// 区间 [from,to) 半开；narg 可空（NULL 不过滤）。延迟由 completed_at-started_at 推导（毫秒）。
// ChannelsOpsTable 渠道运维主表（分页）：每渠道 attempt 指标 + 绑定模型数 + 最近错误，默认最需处理优先。
func (q *Queries) ChannelsOpsTable(ctx context.Context, arg ChannelsOpsTableParams) ([]ChannelsOpsTableRow, error) {
	rows, err := q.db.Query(ctx, channelsOpsTable,
		arg.FromTime,
		arg.ToTime,
		arg.Status,
		arg.ProviderID,
		arg.Search,
		arg.SortField,
		arg.SortDesc,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChannelsOpsTableRow
	for rows.Next() {
		var i ChannelsOpsTableRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Status,
			&i.Protocol,
			&i.AdapterKey,
			&i.BaseUrl,
			&i.Priority,
			&i.TimeoutMs,
			&i.Credential,
			&i.RpmLimit,
			&i.TpmLimit,
			&i.RpdLimit,
			&i.CreatedAt,
			&i.LastTestedAt,
			&i.LastTestOk,
			&i.LastTestLatencyMs,
			&i.LastTestError,
			&i.CredentialValid,
			&i.CostMultiplier,
			&i.CostMultiplierOverrides,
			&i.RechargeFactor,
			&i.ProviderName,
			&i.AttemptTotal,
			&i.AttemptSucceeded,
			&i.TimeoutTotal,
			&i.LatencySample,
			&i.LatencyAvg,
			&i.LatencyP50,
			&i.LatencyP90,
			&i.LatencyP95,
			&i.LatencyP99,
			&i.BoundModels,
			&i.BoundRoutes,
			&i.RecentErrorCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const channelsOpsTableCount = `-- name: ChannelsOpsTableCount :one
SELECT COUNT(*) AS total
FROM channels c
WHERE ($1::text IS NULL OR c.status = $1::text)
  AND ($2::bigint IS NULL OR c.provider_id = $2::bigint)
  AND ($3::text IS NULL OR c.name ILIKE '%' || $3::text || '%')
`

type ChannelsOpsTableCountParams struct {
	Status     pgtype.Text
	ProviderID pgtype.Int8
	Search     pgtype.Text
}

// ChannelsOpsTableCount 与 ChannelsOpsTable 同过滤条件下的渠道总数。
func (q *Queries) ChannelsOpsTableCount(ctx context.Context, arg ChannelsOpsTableCountParams) (int64, error) {
	row := q.db.QueryRow(ctx, channelsOpsTableCount, arg.Status, arg.ProviderID, arg.Search)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const commitChannelAdmissionLimitsAtRevision = `-- name: CommitChannelAdmissionLimitsAtRevision :one
UPDATE channels
SET rpm_limit = $1,
    tpm_limit = $2,
    rpd_limit = $3,
    concurrency_limit = $4,
    admission_limits_revision = $5,
    updated_at = now()
WHERE id = $6
  AND admission_limits_revision = $7
  AND $5 = $7 + 1
  AND ROW(rpm_limit, tpm_limit, rpd_limit, concurrency_limit) IS DISTINCT FROM ROW(
      $1, $2, $3, $4
  )
RETURNING id, provider_id, provider_endpoint_id, name, protocol, adapter_key, credential, config_revision, admission_limits_revision, status, priority, timeout_ms, created_at, updated_at, rpm_limit, tpm_limit, rpd_limit, last_tested_at, last_test_ok, last_test_latency_ms, last_test_error, credential_valid, archived_at, concurrency_limit, upstream_bills_on_disconnect
`

type CommitChannelAdmissionLimitsAtRevisionParams struct {
	RpmLimit         pgtype.Int4
	TpmLimit         pgtype.Int4
	RpdLimit         pgtype.Int4
	ConcurrencyLimit pgtype.Int4
	NextRevision     int64
	ID               int64
	CurrentRevision  int64
}

// CommitChannelAdmissionLimitsAtRevision 只供 runtimecontrol.Publisher 的 BusinessCommit 事务调用：
// 在 expected revision 仍匹配且四维语义真变化时一次写值并推进 admission_limits_revision。
// 普通 Channel 更新不得调用无 revision 的直接覆盖查询。
func (q *Queries) CommitChannelAdmissionLimitsAtRevision(ctx context.Context, arg CommitChannelAdmissionLimitsAtRevisionParams) (Channel, error) {
	row := q.db.QueryRow(ctx, commitChannelAdmissionLimitsAtRevision,
		arg.RpmLimit,
		arg.TpmLimit,
		arg.RpdLimit,
		arg.ConcurrencyLimit,
		arg.NextRevision,
		arg.ID,
		arg.CurrentRevision,
	)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.ProviderEndpointID,
		&i.Name,
		&i.Protocol,
		&i.AdapterKey,
		&i.Credential,
		&i.ConfigRevision,
		&i.AdmissionLimitsRevision,
		&i.Status,
		&i.Priority,
		&i.TimeoutMs,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RpmLimit,
		&i.TpmLimit,
		&i.RpdLimit,
		&i.LastTestedAt,
		&i.LastTestOk,
		&i.LastTestLatencyMs,
		&i.LastTestError,
		&i.CredentialValid,
		&i.ArchivedAt,
		&i.ConcurrencyLimit,
		&i.UpstreamBillsOnDisconnect,
	)
	return i, err
}

const countChannelTestLogsByChannel = `-- name: CountChannelTestLogsByChannel :one
SELECT COUNT(*) AS total
FROM channel_test_logs
WHERE channel_id = $1
`

// CountChannelTestLogsByChannel 返回某渠道检测日志总数（分页用）。
func (q *Queries) CountChannelTestLogsByChannel(ctx context.Context, channelID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countChannelTestLogsByChannel, channelID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countChannels = `-- name: CountChannels :one
SELECT COUNT(*) AS total
FROM channels c
JOIN provider_endpoints pe ON pe.id = c.provider_endpoint_id
WHERE ($1::bigint IS NULL OR c.provider_id = $1::bigint)
  AND ($2::text IS NULL OR c.status = $2::text)
  AND (
    $3::text IS NULL
    OR c.name ILIKE '%' || $3::text || '%'
    OR pe.base_url ILIKE '%' || $3::text || '%'
  )
`

type CountChannelsParams struct {
	ProviderID pgtype.Int8
	Status     pgtype.Text
	Q          pgtype.Text
}

// CountChannels 返回与 ListChannelsPage 相同过滤条件下的总条数。
func (q *Queries) CountChannels(ctx context.Context, arg CountChannelsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countChannels, arg.ProviderID, arg.Status, arg.Q)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const createChannel = `-- name: CreateChannel :one
INSERT INTO channels (
    provider_id, provider_endpoint_id, name, protocol, adapter_key, credential, status, priority, timeout_ms,
    rpm_limit, tpm_limit, rpd_limit, concurrency_limit, upstream_bills_on_disconnect
)
VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9,
    $10, $11, $12, $13,
    $14
)
RETURNING id, provider_id, provider_endpoint_id, name, protocol, adapter_key, credential, config_revision, admission_limits_revision, status, priority, timeout_ms, created_at, updated_at, rpm_limit, tpm_limit, rpd_limit, last_tested_at, last_test_ok, last_test_latency_ms, last_test_error, credential_valid, archived_at, concurrency_limit, upstream_bills_on_disconnect
`

type CreateChannelParams struct {
	ProviderID                int64
	ProviderEndpointID        int64
	Name                      string
	Protocol                  string
	AdapterKey                string
	Credential                string
	Status                    string
	Priority                  int32
	TimeoutMs                 pgtype.Int4
	RpmLimit                  pgtype.Int4
	TpmLimit                  pgtype.Int4
	RpdLimit                  pgtype.Int4
	ConcurrencyLimit          pgtype.Int4
	UpstreamBillsOnDisconnect bool
}

// CreateChannel 创建 channel；credential 为明文上游凭据，protocol+adapter_key 复合键须先在 adapter registry 校验存在。
// 四维限额随业务行一次写入，初始 admission_limits_revision 固定使用表默认值 1；随后同步安装 revision=1 Redis control。
func (q *Queries) CreateChannel(ctx context.Context, arg CreateChannelParams) (Channel, error) {
	row := q.db.QueryRow(ctx, createChannel,
		arg.ProviderID,
		arg.ProviderEndpointID,
		arg.Name,
		arg.Protocol,
		arg.AdapterKey,
		arg.Credential,
		arg.Status,
		arg.Priority,
		arg.TimeoutMs,
		arg.RpmLimit,
		arg.TpmLimit,
		arg.RpdLimit,
		arg.ConcurrencyLimit,
		arg.UpstreamBillsOnDisconnect,
	)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.ProviderEndpointID,
		&i.Name,
		&i.Protocol,
		&i.AdapterKey,
		&i.Credential,
		&i.ConfigRevision,
		&i.AdmissionLimitsRevision,
		&i.Status,
		&i.Priority,
		&i.TimeoutMs,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RpmLimit,
		&i.TpmLimit,
		&i.RpdLimit,
		&i.LastTestedAt,
		&i.LastTestOk,
		&i.LastTestLatencyMs,
		&i.LastTestError,
		&i.CredentialValid,
		&i.ArchivedAt,
		&i.ConcurrencyLimit,
		&i.UpstreamBillsOnDisconnect,
	)
	return i, err
}

const createChannelCostMultiplier = `-- name: CreateChannelCostMultiplier :one
INSERT INTO channel_cost_multipliers (
    channel_id,
    model_id,
    multiplier,
    status,
    effective_from,
    effective_to
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id, channel_id, model_id, multiplier, status, effective_from, effective_to, created_at, updated_at, model_key
`

type CreateChannelCostMultiplierParams struct {
	ChannelID     int64
	ModelID       pgtype.Int8
	Multiplier    pgtype.Numeric
	Status        string
	EffectiveFrom pgtype.Timestamptz
	EffectiveTo   pgtype.Timestamptz
}

// CreateChannelCostMultiplier 创建一条渠道价格倍率（DEC-027）。model_id 为空=渠道默认；非空=对该模型的覆盖。
// 启用窗口重叠（同 channel + 同 model_key）由 ex_channel_cost_multipliers_enabled_window 保证，违反报 23P01。
func (q *Queries) CreateChannelCostMultiplier(ctx context.Context, arg CreateChannelCostMultiplierParams) (ChannelCostMultiplier, error) {
	row := q.db.QueryRow(ctx, createChannelCostMultiplier,
		arg.ChannelID,
		arg.ModelID,
		arg.Multiplier,
		arg.Status,
		arg.EffectiveFrom,
		arg.EffectiveTo,
	)
	var i ChannelCostMultiplier
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.ModelID,
		&i.Multiplier,
		&i.Status,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ModelKey,
	)
	return i, err
}

const createChannelModel = `-- name: CreateChannelModel :one
INSERT INTO channel_models (channel_id, model_id, upstream_model, status)
VALUES ($1, $2, $3, $4)
RETURNING id, channel_id, model_id, upstream_model, status, created_at, updated_at
`

type CreateChannelModelParams struct {
	ChannelID     int64
	ModelID       int64
	UpstreamModel string
	Status        string
}

// CreateChannelModel 创建 channel↔model 绑定；同一 channel 对同一 model 只能绑定一次（唯一约束）。
func (q *Queries) CreateChannelModel(ctx context.Context, arg CreateChannelModelParams) (ChannelModel, error) {
	row := q.db.QueryRow(ctx, createChannelModel,
		arg.ChannelID,
		arg.ModelID,
		arg.UpstreamModel,
		arg.Status,
	)
	var i ChannelModel
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.ModelID,
		&i.UpstreamModel,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createChannelPrice = `-- name: CreateChannelPrice :one
INSERT INTO channel_prices (
    channel_id,
    model_id,
    currency,
    pricing_unit,
    uncached_input_cost,
    cache_read_input_cost,
    cache_write_5m_input_cost,
    cache_write_1h_input_cost,
    cache_write_30m_input_cost,
    output_cost,
    reasoning_output_cost,
    status,
    effective_from,
    effective_to
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14
)
RETURNING id, channel_id, model_id, currency, pricing_unit, uncached_input_cost, cache_read_input_cost, cache_write_5m_input_cost, cache_write_1h_input_cost, output_cost, reasoning_output_cost, status, effective_from, effective_to, created_at, updated_at, cache_write_30m_input_cost
`

type CreateChannelPriceParams struct {
	ChannelID              int64
	ModelID                int64
	Currency               string
	PricingUnit            string
	UncachedInputCost      pgtype.Numeric
	CacheReadInputCost     pgtype.Numeric
	CacheWrite5mInputCost  pgtype.Numeric
	CacheWrite1hInputCost  pgtype.Numeric
	CacheWrite30mInputCost pgtype.Numeric
	OutputCost             pgtype.Numeric
	ReasoningOutputCost    pgtype.Numeric
	Status                 string
	EffectiveFrom          pgtype.Timestamptz
	EffectiveTo            pgtype.Timestamptz
}

// CreateChannelPrice 创建一条渠道-模型成本价（DEC-026：渠道只录成本，售价取 model_prices × 线路倍率）。
// 启用窗口重叠由 ex_channel_prices_enabled_window 保证，违反报 23P01。
func (q *Queries) CreateChannelPrice(ctx context.Context, arg CreateChannelPriceParams) (ChannelPrice, error) {
	row := q.db.QueryRow(ctx, createChannelPrice,
		arg.ChannelID,
		arg.ModelID,
		arg.Currency,
		arg.PricingUnit,
		arg.UncachedInputCost,
		arg.CacheReadInputCost,
		arg.CacheWrite5mInputCost,
		arg.CacheWrite1hInputCost,
		arg.CacheWrite30mInputCost,
		arg.OutputCost,
		arg.ReasoningOutputCost,
		arg.Status,
		arg.EffectiveFrom,
		arg.EffectiveTo,
	)
	var i ChannelPrice
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.ModelID,
		&i.Currency,
		&i.PricingUnit,
		&i.UncachedInputCost,
		&i.CacheReadInputCost,
		&i.CacheWrite5mInputCost,
		&i.CacheWrite1hInputCost,
		&i.OutputCost,
		&i.ReasoningOutputCost,
		&i.Status,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CacheWrite30mInputCost,
	)
	return i, err
}

const createChannelRechargeFactor = `-- name: CreateChannelRechargeFactor :one
INSERT INTO channel_recharge_factors (
    channel_id,
    factor,
    status,
    effective_from,
    effective_to
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING id, channel_id, factor, status, effective_from, effective_to, created_at, updated_at
`

type CreateChannelRechargeFactorParams struct {
	ChannelID     int64
	Factor        pgtype.Numeric
	Status        string
	EffectiveFrom pgtype.Timestamptz
	EffectiveTo   pgtype.Timestamptz
}

// CreateChannelRechargeFactor 创建一条渠道充值倍率（DEC-027）。渠道真实成本 = 上游名义成本 × 本充值倍率。
// 启用窗口重叠由 ex_channel_recharge_factors_enabled_window 保证，违反报 23P01。
func (q *Queries) CreateChannelRechargeFactor(ctx context.Context, arg CreateChannelRechargeFactorParams) (ChannelRechargeFactor, error) {
	row := q.db.QueryRow(ctx, createChannelRechargeFactor,
		arg.ChannelID,
		arg.Factor,
		arg.Status,
		arg.EffectiveFrom,
		arg.EffectiveTo,
	)
	var i ChannelRechargeFactor
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.Factor,
		&i.Status,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteChannelCascade = `-- name: DeleteChannelCascade :execrows
WITH deleted_channel_prices AS (
    DELETE FROM channel_prices WHERE channel_prices.channel_id = $1
),
deleted_channel_models AS (
    DELETE FROM channel_models WHERE channel_models.channel_id = $1
),
deleted_channel_cost_multipliers AS (
    DELETE FROM channel_cost_multipliers WHERE channel_cost_multipliers.channel_id = $1
),
deleted_channel_recharge_factors AS (
    DELETE FROM channel_recharge_factors WHERE channel_recharge_factors.channel_id = $1
)
DELETE FROM channels WHERE channels.id = $1
`

// DeleteChannelCascade 物理删除 channel，用于清理录错且从未使用的脏数据，并在同一条语句内
// 级联清理 channel 自身的全部配置子表：channel_models（模型绑定）、channel_prices（渠道-模型价，
// 绝对成本覆盖）、channel_cost_multipliers（价格倍率，DEC-027）、channel_recharge_factors（充值倍率，DEC-027）。
// 这四张都是「渠道自身配置」（无请求/账务事实），随渠道硬删一并清理；channel_test_logs 走 ON DELETE CASCADE 自动清。
// 外键均为默认 NO ACTION（约束在语句末校验），故 CTE 删子表 + 删主体在单条语句内原子完成：
// 子配置先删除，语句末 channels 的删除不会留下悬挂引用。若 channel 仍被请求/账务历史
// （request_attempts/request_records/cost_snapshots/settlement_recovery_jobs/channel_cost_exposures）引用，
// 整条语句报 23503 全部回滚，上层降级为 conflict，提示改用停用/保持归档。返回值为 channels 行的受影响数（0 表示 channel 不存在）。
// 注：归档时已从 route_channels 线路池移除（ArchiveChannelCascade），故此处无需再清线路池。
func (q *Queries) DeleteChannelCascade(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteChannelCascade, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteChannelModel = `-- name: DeleteChannelModel :execrows
WITH deleted_channel_prices AS (
    DELETE FROM channel_prices
    WHERE channel_prices.channel_id = $1
      AND channel_prices.model_id = $2
)
DELETE FROM channel_models
WHERE channel_models.channel_id = $1
  AND channel_models.model_id = $2
`

type DeleteChannelModelParams struct {
	ChannelID int64
	ModelID   int64
}

// DeleteChannelModel 删除绑定，并在同一条语句内级联清理该 (channel_id, model_id) 边自身的
// channel_prices（渠道-模型成本价，追加式配置、无删除接口，只能停用）——否则只要该边配过成本价，
// 就会被自身配置行永久挡住解绑。channel_prices 仅被账务历史（cost_snapshots/price_snapshots/
// settlement_recovery_jobs）以 NO ACTION 外键引用：若该边确有计费历史，删 channel_prices 触发
// 23503 使整条语句回滚，上层降级为 conflict，提示改用停用——保住计费/审计链路。
// 无历史时（仅配置行）则干净解绑。返回值为 channel_models 行的受影响数（0 表示绑定不存在）。
func (q *Queries) DeleteChannelModel(ctx context.Context, arg DeleteChannelModelParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteChannelModel, arg.ChannelID, arg.ModelID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getChannel = `-- name: GetChannel :one
SELECT id, provider_id, provider_endpoint_id, name, protocol, adapter_key, credential, config_revision, admission_limits_revision, status, priority, timeout_ms, created_at, updated_at, rpm_limit, tpm_limit, rpd_limit, last_tested_at, last_test_ok, last_test_latency_ms, last_test_error, credential_valid, archived_at, concurrency_limit, upstream_bills_on_disconnect
FROM channels
WHERE id = $1
LIMIT 1
`

// GetChannel 按 id 读取单个 channel。
func (q *Queries) GetChannel(ctx context.Context, id int64) (Channel, error) {
	row := q.db.QueryRow(ctx, getChannel, id)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.ProviderEndpointID,
		&i.Name,
		&i.Protocol,
		&i.AdapterKey,
		&i.Credential,
		&i.ConfigRevision,
		&i.AdmissionLimitsRevision,
		&i.Status,
		&i.Priority,
		&i.TimeoutMs,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RpmLimit,
		&i.TpmLimit,
		&i.RpdLimit,
		&i.LastTestedAt,
		&i.LastTestOk,
		&i.LastTestLatencyMs,
		&i.LastTestError,
		&i.CredentialValid,
		&i.ArchivedAt,
		&i.ConcurrencyLimit,
		&i.UpstreamBillsOnDisconnect,
	)
	return i, err
}

const getChannelModel = `-- name: GetChannelModel :one
SELECT id, channel_id, model_id, upstream_model, status, created_at, updated_at
FROM channel_models
WHERE channel_id = $1 AND model_id = $2
LIMIT 1
`

type GetChannelModelParams struct {
	ChannelID int64
	ModelID   int64
}

// GetChannelModel 按 (channel_id, model_id) 读取单条绑定。
func (q *Queries) GetChannelModel(ctx context.Context, arg GetChannelModelParams) (ChannelModel, error) {
	row := q.db.QueryRow(ctx, getChannelModel, arg.ChannelID, arg.ModelID)
	var i ChannelModel
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.ModelID,
		&i.UpstreamModel,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getChannelProbeSnapshot = `-- name: GetChannelProbeSnapshot :one
SELECT
    c.id AS channel_id,
    c.provider_id,
    c.provider_endpoint_id,
    c.protocol,
    c.adapter_key,
    c.credential,
    c.credential_valid,
    c.config_revision,
    p.slug AS provider_slug,
    pe.base_url AS endpoint_base_url,
    pe.base_url_revision AS endpoint_base_url_revision,
    pe.status_revision AS endpoint_status_revision
FROM channels c
JOIN providers p ON p.id = c.provider_id
JOIN provider_endpoints pe ON pe.id = c.provider_endpoint_id
WHERE c.id = $1
LIMIT 1
`

type GetChannelProbeSnapshotRow struct {
	ChannelID               int64
	ProviderID              int64
	ProviderEndpointID      int64
	Protocol                string
	AdapterKey              string
	Credential              string
	CredentialValid         bool
	ConfigRevision          int64
	ProviderSlug            string
	EndpointBaseUrl         string
	EndpointBaseUrlRevision int64
	EndpointStatusRevision  int64
}

// GetChannelProbeSnapshot 一次读取主动检测所需的 Channel、Provider 与 Endpoint 冻结事实；检测结果只允许按三类 revision CAS 回写。
func (q *Queries) GetChannelProbeSnapshot(ctx context.Context, channelID int64) (GetChannelProbeSnapshotRow, error) {
	row := q.db.QueryRow(ctx, getChannelProbeSnapshot, channelID)
	var i GetChannelProbeSnapshotRow
	err := row.Scan(
		&i.ChannelID,
		&i.ProviderID,
		&i.ProviderEndpointID,
		&i.Protocol,
		&i.AdapterKey,
		&i.Credential,
		&i.CredentialValid,
		&i.ConfigRevision,
		&i.ProviderSlug,
		&i.EndpointBaseUrl,
		&i.EndpointBaseUrlRevision,
		&i.EndpointStatusRevision,
	)
	return i, err
}

const listChannelCostMultipliersByChannel = `-- name: ListChannelCostMultipliersByChannel :many
SELECT
    ccm.id,
    ccm.channel_id,
    ccm.model_id,
    ccm.multiplier,
    ccm.status,
    ccm.effective_from,
    ccm.effective_to,
    ccm.created_at,
    ccm.updated_at,
    m.model_id AS model_external_id,
    m.display_name AS model_display_name
FROM channel_cost_multipliers ccm
LEFT JOIN models m ON m.id = ccm.model_id
WHERE ccm.channel_id = $1
ORDER BY (ccm.model_id IS NULL) DESC, ccm.model_id, ccm.effective_from DESC, ccm.id DESC
`

type ListChannelCostMultipliersByChannelRow struct {
	ID               int64
	ChannelID        int64
	ModelID          pgtype.Int8
	Multiplier       pgtype.Numeric
	Status           string
	EffectiveFrom    pgtype.Timestamptz
	EffectiveTo      pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	ModelExternalID  pgtype.Text
	ModelDisplayName pgtype.Text
}

// ListChannelCostMultipliersByChannel 列出某 channel 的全部价格倍率（默认 + 逐模型覆盖，含历史与停用），
// 逐模型覆盖连带模型对外 ID/展示名（默认行 model 相关列为 NULL），供 admin 管理台展示。
func (q *Queries) ListChannelCostMultipliersByChannel(ctx context.Context, channelID int64) ([]ListChannelCostMultipliersByChannelRow, error) {
	rows, err := q.db.Query(ctx, listChannelCostMultipliersByChannel, channelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChannelCostMultipliersByChannelRow
	for rows.Next() {
		var i ListChannelCostMultipliersByChannelRow
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.ModelID,
			&i.Multiplier,
			&i.Status,
			&i.EffectiveFrom,
			&i.EffectiveTo,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ModelExternalID,
			&i.ModelDisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChannelModelsByChannel = `-- name: ListChannelModelsByChannel :many
SELECT
    cm.id,
    cm.channel_id,
    cm.model_id,
    cm.upstream_model,
    cm.status,
    cm.created_at,
    cm.updated_at,
    m.model_id AS model_external_id,
    m.display_name AS model_display_name
FROM channel_models cm
JOIN models m ON m.id = cm.model_id
WHERE cm.channel_id = $1
ORDER BY m.model_id
`

type ListChannelModelsByChannelRow struct {
	ID               int64
	ChannelID        int64
	ModelID          int64
	UpstreamModel    string
	Status           string
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	ModelExternalID  string
	ModelDisplayName string
}

// ListChannelModelsByChannel 列出某 channel 的全部模型绑定，连带 Unio 侧模型的对外 ID 与展示名，供 admin 管理台展示。
func (q *Queries) ListChannelModelsByChannel(ctx context.Context, channelID int64) ([]ListChannelModelsByChannelRow, error) {
	rows, err := q.db.Query(ctx, listChannelModelsByChannel, channelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChannelModelsByChannelRow
	for rows.Next() {
		var i ListChannelModelsByChannelRow
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.ModelID,
			&i.UpstreamModel,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ModelExternalID,
			&i.ModelDisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChannelPricesByChannel = `-- name: ListChannelPricesByChannel :many
SELECT
    cp.id,
    cp.channel_id,
    cp.model_id,
    cp.currency,
    cp.pricing_unit,
    cp.uncached_input_cost,
    cp.cache_read_input_cost,
    cp.cache_write_5m_input_cost,
    cp.cache_write_1h_input_cost,
    cp.cache_write_30m_input_cost,
    cp.output_cost,
    cp.reasoning_output_cost,
    cp.status,
    cp.effective_from,
    cp.effective_to,
    cp.created_at,
    cp.updated_at,
    m.model_id AS model_external_id,
    m.display_name AS model_display_name
FROM channel_prices cp
JOIN models m ON m.id = cp.model_id
WHERE cp.channel_id = $1
ORDER BY m.model_id, cp.effective_from DESC, cp.id DESC
`

type ListChannelPricesByChannelRow struct {
	ID                     int64
	ChannelID              int64
	ModelID                int64
	Currency               string
	PricingUnit            string
	UncachedInputCost      pgtype.Numeric
	CacheReadInputCost     pgtype.Numeric
	CacheWrite5mInputCost  pgtype.Numeric
	CacheWrite1hInputCost  pgtype.Numeric
	CacheWrite30mInputCost pgtype.Numeric
	OutputCost             pgtype.Numeric
	ReasoningOutputCost    pgtype.Numeric
	Status                 string
	EffectiveFrom          pgtype.Timestamptz
	EffectiveTo            pgtype.Timestamptz
	CreatedAt              pgtype.Timestamptz
	UpdatedAt              pgtype.Timestamptz
	ModelExternalID        string
	ModelDisplayName       string
}

// ListChannelPricesByChannel 列出某 channel 下全部渠道-模型成本价（含历史与停用），连带模型对外 ID/展示名，供 admin 管理台展示成本。
func (q *Queries) ListChannelPricesByChannel(ctx context.Context, channelID int64) ([]ListChannelPricesByChannelRow, error) {
	rows, err := q.db.Query(ctx, listChannelPricesByChannel, channelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChannelPricesByChannelRow
	for rows.Next() {
		var i ListChannelPricesByChannelRow
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.ModelID,
			&i.Currency,
			&i.PricingUnit,
			&i.UncachedInputCost,
			&i.CacheReadInputCost,
			&i.CacheWrite5mInputCost,
			&i.CacheWrite1hInputCost,
			&i.CacheWrite30mInputCost,
			&i.OutputCost,
			&i.ReasoningOutputCost,
			&i.Status,
			&i.EffectiveFrom,
			&i.EffectiveTo,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ModelExternalID,
			&i.ModelDisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChannelRechargeFactorsByChannel = `-- name: ListChannelRechargeFactorsByChannel :many
SELECT
    id,
    channel_id,
    factor,
    status,
    effective_from,
    effective_to,
    created_at,
    updated_at
FROM channel_recharge_factors
WHERE channel_id = $1
ORDER BY effective_from DESC, id DESC
`

// ListChannelRechargeFactorsByChannel 列出某 channel 的全部充值倍率（含历史与停用），供 admin 管理台展示。
func (q *Queries) ListChannelRechargeFactorsByChannel(ctx context.Context, channelID int64) ([]ChannelRechargeFactor, error) {
	rows, err := q.db.Query(ctx, listChannelRechargeFactorsByChannel, channelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChannelRechargeFactor
	for rows.Next() {
		var i ChannelRechargeFactor
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.Factor,
			&i.Status,
			&i.EffectiveFrom,
			&i.EffectiveTo,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChannelTestLogsByChannel = `-- name: ListChannelTestLogsByChannel :many
SELECT id, channel_id, created_at, source, success, error_code, http_status, latency_ms, tested_model, credential_valid_after, message, upstream_error, tested_endpoint_base_url_revision, tested_endpoint_status_revision, tested_config_revision, state_change_applied
FROM channel_test_logs
WHERE channel_id = $1
ORDER BY created_at DESC, id DESC
LIMIT $3 OFFSET $2
`

type ListChannelTestLogsByChannelParams struct {
	ChannelID  int64
	PageOffset int32
	PageLimit  int32
}

// ListChannelTestLogsByChannel 按渠道倒序分页返回检测日志（详情页「检测日志」区块）。
func (q *Queries) ListChannelTestLogsByChannel(ctx context.Context, arg ListChannelTestLogsByChannelParams) ([]ChannelTestLog, error) {
	rows, err := q.db.Query(ctx, listChannelTestLogsByChannel, arg.ChannelID, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChannelTestLog
	for rows.Next() {
		var i ChannelTestLog
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.CreatedAt,
			&i.Source,
			&i.Success,
			&i.ErrorCode,
			&i.HttpStatus,
			&i.LatencyMs,
			&i.TestedModel,
			&i.CredentialValidAfter,
			&i.Message,
			&i.UpstreamError,
			&i.TestedEndpointBaseUrlRevision,
			&i.TestedEndpointStatusRevision,
			&i.TestedConfigRevision,
			&i.StateChangeApplied,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChannelsByProvider = `-- name: ListChannelsByProvider :many
SELECT id, provider_id, provider_endpoint_id, name, protocol, adapter_key, credential, config_revision, admission_limits_revision, status, priority, timeout_ms, created_at, updated_at, rpm_limit, tpm_limit, rpd_limit, last_tested_at, last_test_ok, last_test_latency_ms, last_test_error, credential_valid, archived_at, concurrency_limit, upstream_bills_on_disconnect
FROM channels
WHERE provider_id = $1
ORDER BY priority, id
`

// ListChannelsByProvider 列出指定 provider 下的 channel，按 priority、id 升序。
func (q *Queries) ListChannelsByProvider(ctx context.Context, providerID int64) ([]Channel, error) {
	rows, err := q.db.Query(ctx, listChannelsByProvider, providerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Channel
	for rows.Next() {
		var i Channel
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.ProviderEndpointID,
			&i.Name,
			&i.Protocol,
			&i.AdapterKey,
			&i.Credential,
			&i.ConfigRevision,
			&i.AdmissionLimitsRevision,
			&i.Status,
			&i.Priority,
			&i.TimeoutMs,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RpmLimit,
			&i.TpmLimit,
			&i.RpdLimit,
			&i.LastTestedAt,
			&i.LastTestOk,
			&i.LastTestLatencyMs,
			&i.LastTestError,
			&i.CredentialValid,
			&i.ArchivedAt,
			&i.ConcurrencyLimit,
			&i.UpstreamBillsOnDisconnect,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChannelsForRuntimeControlRestore = `-- name: ListChannelsForRuntimeControlRestore :many
SELECT id, provider_id, provider_endpoint_id, name, protocol, adapter_key, credential, config_revision, admission_limits_revision, status, priority, timeout_ms, created_at, updated_at, rpm_limit, tpm_limit, rpd_limit, last_tested_at, last_test_ok, last_test_latency_ms, last_test_error, credential_valid, archived_at, concurrency_limit, upstream_bills_on_disconnect
FROM channels
ORDER BY id
`

// ListChannelsForRuntimeControlRestore 返回启动期恢复 Channel admission control 所需的 PostgreSQL 权威事实。
func (q *Queries) ListChannelsForRuntimeControlRestore(ctx context.Context) ([]Channel, error) {
	rows, err := q.db.Query(ctx, listChannelsForRuntimeControlRestore)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Channel
	for rows.Next() {
		var i Channel
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.ProviderEndpointID,
			&i.Name,
			&i.Protocol,
			&i.AdapterKey,
			&i.Credential,
			&i.ConfigRevision,
			&i.AdmissionLimitsRevision,
			&i.Status,
			&i.Priority,
			&i.TimeoutMs,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RpmLimit,
			&i.TpmLimit,
			&i.RpdLimit,
			&i.LastTestedAt,
			&i.LastTestOk,
			&i.LastTestLatencyMs,
			&i.LastTestError,
			&i.CredentialValid,
			&i.ArchivedAt,
			&i.ConcurrencyLimit,
			&i.UpstreamBillsOnDisconnect,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChannelsPage = `-- name: ListChannelsPage :many
SELECT
    c.id, c.provider_id, c.provider_endpoint_id, c.name, c.protocol, c.adapter_key, pe.base_url,
    c.credential, c.status, c.priority, c.timeout_ms, c.created_at, c.updated_at,
    c.rpm_limit, c.tpm_limit, c.rpd_limit, c.concurrency_limit, c.upstream_bills_on_disconnect,
    c.last_tested_at, c.last_test_ok, c.last_test_latency_ms, c.last_test_error, c.credential_valid,
    c.config_revision, c.admission_limits_revision,
    pe.name AS provider_endpoint_name, pe.status AS provider_endpoint_status,
    p.name AS provider_name
FROM channels c
JOIN providers p ON p.id = c.provider_id
JOIN provider_endpoints pe ON pe.id = c.provider_endpoint_id
WHERE ($1::bigint IS NULL OR c.provider_id = $1::bigint)
  AND ($2::text IS NULL OR c.status = $2::text)
  AND (
    $3::text IS NULL
    OR c.name ILIKE '%' || $3::text || '%'
    OR pe.base_url ILIKE '%' || $3::text || '%'
  )
ORDER BY c.priority, c.id
LIMIT $5 OFFSET $4
`

type ListChannelsPageParams struct {
	ProviderID pgtype.Int8
	Status     pgtype.Text
	Q          pgtype.Text
	PageOffset int32
	PageLimit  int32
}

type ListChannelsPageRow struct {
	ID                        int64
	ProviderID                int64
	ProviderEndpointID        int64
	Name                      string
	Protocol                  string
	AdapterKey                string
	BaseUrl                   string
	Credential                string
	Status                    string
	Priority                  int32
	TimeoutMs                 pgtype.Int4
	CreatedAt                 pgtype.Timestamptz
	UpdatedAt                 pgtype.Timestamptz
	RpmLimit                  pgtype.Int4
	TpmLimit                  pgtype.Int4
	RpdLimit                  pgtype.Int4
	ConcurrencyLimit          pgtype.Int4
	UpstreamBillsOnDisconnect bool
	LastTestedAt              pgtype.Timestamptz
	LastTestOk                pgtype.Bool
	LastTestLatencyMs         pgtype.Int4
	LastTestError             pgtype.Text
	CredentialValid           bool
	ConfigRevision            int64
	AdmissionLimitsRevision   int64
	ProviderEndpointName      string
	ProviderEndpointStatus    string
	ProviderName              string
}

// ListChannelsPage 按 provider/状态/关键字过滤后分页列出 channel，连带 provider 名称；过滤项为 NULL 时不过滤。
func (q *Queries) ListChannelsPage(ctx context.Context, arg ListChannelsPageParams) ([]ListChannelsPageRow, error) {
	rows, err := q.db.Query(ctx, listChannelsPage,
		arg.ProviderID,
		arg.Status,
		arg.Q,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChannelsPageRow
	for rows.Next() {
		var i ListChannelsPageRow
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.ProviderEndpointID,
			&i.Name,
			&i.Protocol,
			&i.AdapterKey,
			&i.BaseUrl,
			&i.Credential,
			&i.Status,
			&i.Priority,
			&i.TimeoutMs,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RpmLimit,
			&i.TpmLimit,
			&i.RpdLimit,
			&i.ConcurrencyLimit,
			&i.UpstreamBillsOnDisconnect,
			&i.LastTestedAt,
			&i.LastTestOk,
			&i.LastTestLatencyMs,
			&i.LastTestError,
			&i.CredentialValid,
			&i.ConfigRevision,
			&i.AdmissionLimitsRevision,
			&i.ProviderEndpointName,
			&i.ProviderEndpointStatus,
			&i.ProviderName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnabledChannelCostMultiplierWindows = `-- name: ListEnabledChannelCostMultiplierWindows :many
SELECT id, effective_from, effective_to
FROM channel_cost_multipliers
WHERE channel_id = $1
    AND model_id IS NOT DISTINCT FROM $2
    AND status = 'enabled'
    AND id <> $3
`

type ListEnabledChannelCostMultiplierWindowsParams struct {
	ChannelID int64
	ModelID   pgtype.Int8
	ExcludeID int64
}

type ListEnabledChannelCostMultiplierWindowsRow struct {
	ID            int64
	EffectiveFrom pgtype.Timestamptz
	EffectiveTo   pgtype.Timestamptz
}

// ListEnabledChannelCostMultiplierWindows 取某 channel + 同一 model_key（默认或某模型覆盖）全部启用中的生效窗口，
// 供「窗口不重叠」校验；exclude_id 用于更新时排除自身（创建时传 0）。model_id 用 IS NOT DISTINCT FROM 匹配 NULL 默认。
func (q *Queries) ListEnabledChannelCostMultiplierWindows(ctx context.Context, arg ListEnabledChannelCostMultiplierWindowsParams) ([]ListEnabledChannelCostMultiplierWindowsRow, error) {
	rows, err := q.db.Query(ctx, listEnabledChannelCostMultiplierWindows, arg.ChannelID, arg.ModelID, arg.ExcludeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEnabledChannelCostMultiplierWindowsRow
	for rows.Next() {
		var i ListEnabledChannelCostMultiplierWindowsRow
		if err := rows.Scan(&i.ID, &i.EffectiveFrom, &i.EffectiveTo); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnabledChannelPriceWindows = `-- name: ListEnabledChannelPriceWindows :many
SELECT id, effective_from, effective_to
FROM channel_prices
WHERE channel_id = $1
    AND model_id = $2
    AND status = 'enabled'
    AND id <> $3
`

type ListEnabledChannelPriceWindowsParams struct {
	ChannelID int64
	ModelID   int64
	ExcludeID int64
}

type ListEnabledChannelPriceWindowsRow struct {
	ID            int64
	EffectiveFrom pgtype.Timestamptz
	EffectiveTo   pgtype.Timestamptz
}

// ListEnabledChannelPriceWindows 取某 channel/model 全部启用中的价格生效窗口，供「窗口不重叠」校验；exclude_id 用于更新时排除自身（创建时传 0）。
func (q *Queries) ListEnabledChannelPriceWindows(ctx context.Context, arg ListEnabledChannelPriceWindowsParams) ([]ListEnabledChannelPriceWindowsRow, error) {
	rows, err := q.db.Query(ctx, listEnabledChannelPriceWindows, arg.ChannelID, arg.ModelID, arg.ExcludeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEnabledChannelPriceWindowsRow
	for rows.Next() {
		var i ListEnabledChannelPriceWindowsRow
		if err := rows.Scan(&i.ID, &i.EffectiveFrom, &i.EffectiveTo); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnabledChannelRechargeFactorWindows = `-- name: ListEnabledChannelRechargeFactorWindows :many
SELECT id, effective_from, effective_to
FROM channel_recharge_factors
WHERE channel_id = $1
    AND status = 'enabled'
    AND id <> $2
`

type ListEnabledChannelRechargeFactorWindowsParams struct {
	ChannelID int64
	ExcludeID int64
}

type ListEnabledChannelRechargeFactorWindowsRow struct {
	ID            int64
	EffectiveFrom pgtype.Timestamptz
	EffectiveTo   pgtype.Timestamptz
}

// ListEnabledChannelRechargeFactorWindows 取某 channel 全部启用中的充值倍率生效窗口，供「窗口不重叠」校验；exclude_id 用于更新时排除自身（创建时传 0）。
func (q *Queries) ListEnabledChannelRechargeFactorWindows(ctx context.Context, arg ListEnabledChannelRechargeFactorWindowsParams) ([]ListEnabledChannelRechargeFactorWindowsRow, error) {
	rows, err := q.db.Query(ctx, listEnabledChannelRechargeFactorWindows, arg.ChannelID, arg.ExcludeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEnabledChannelRechargeFactorWindowsRow
	for rows.Next() {
		var i ListEnabledChannelRechargeFactorWindowsRow
		if err := rows.Scan(&i.ID, &i.EffectiveFrom, &i.EffectiveTo); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnabledRoutesEmptiedByChannel = `-- name: ListEnabledRoutesEmptiedByChannel :many
SELECT rt.id, rt.name
FROM routes rt
JOIN route_channels target ON target.route_id = rt.id AND target.channel_id = $1
WHERE rt.status = 'enabled'
  AND NOT EXISTS (
      SELECT 1 FROM route_channels other
      WHERE other.route_id = rt.id AND other.channel_id <> $1
  )
ORDER BY rt.id
`

type ListEnabledRoutesEmptiedByChannelRow struct {
	ID   int64
	Name string
}

// 归档目标渠道后将失去最后一个显式池成员的启用线路；归档前必须先替换渠道或停用线路。
func (q *Queries) ListEnabledRoutesEmptiedByChannel(ctx context.Context, channelID int64) ([]ListEnabledRoutesEmptiedByChannelRow, error) {
	rows, err := q.db.Query(ctx, listEnabledRoutesEmptiedByChannel, channelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEnabledRoutesEmptiedByChannelRow
	for rows.Next() {
		var i ListEnabledRoutesEmptiedByChannelRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const prepareChannelCredentialRotation = `-- name: PrepareChannelCredentialRotation :one
WITH current AS MATERIALIZED (
    SELECT c.id, c.credential AS previous_credential, c.credential_valid AS previous_credential_valid
    FROM channels AS c
    WHERE c.id = $1
    FOR UPDATE
), updated AS (
    UPDATE channels AS c
    SET credential = $2,
        credential_valid = CASE
            WHEN current.previous_credential IS DISTINCT FROM $2 THEN FALSE
            ELSE c.credential_valid
        END,
        last_tested_at = CASE
            WHEN current.previous_credential IS DISTINCT FROM $2 THEN NULL
            ELSE c.last_tested_at
        END,
        last_test_ok = CASE
            WHEN current.previous_credential IS DISTINCT FROM $2 THEN NULL
            ELSE c.last_test_ok
        END,
        last_test_latency_ms = CASE
            WHEN current.previous_credential IS DISTINCT FROM $2 THEN NULL
            ELSE c.last_test_latency_ms
        END,
        last_test_error = CASE
            WHEN current.previous_credential IS DISTINCT FROM $2 THEN NULL
            ELSE c.last_test_error
        END,
        config_revision = c.config_revision + CASE
            WHEN current.previous_credential IS DISTINCT FROM $2 THEN 1
            ELSE 0
        END,
        updated_at = CASE
            WHEN current.previous_credential IS DISTINCT FROM $2 THEN now()
            ELSE c.updated_at
        END
    FROM current
    WHERE c.id = current.id
    RETURNING
        c.id AS channel_id,
        c.provider_id,
        c.provider_endpoint_id,
        c.protocol,
        c.adapter_key,
        c.credential,
        c.credential_valid,
        c.config_revision,
        (current.previous_credential IS DISTINCT FROM $2)::boolean AS credential_changed
)
SELECT
    updated.channel_id,
    updated.provider_id,
    updated.provider_endpoint_id,
    updated.protocol,
    updated.adapter_key,
    updated.credential,
    updated.credential_valid,
    updated.config_revision,
    updated.credential_changed,
    p.slug AS provider_slug,
    pe.base_url AS endpoint_base_url,
    pe.base_url_revision AS endpoint_base_url_revision,
    pe.status_revision AS endpoint_status_revision
FROM updated
JOIN providers p ON p.id = updated.provider_id
JOIN provider_endpoints pe ON pe.id = updated.provider_endpoint_id
`

type PrepareChannelCredentialRotationParams struct {
	ChannelID  int64
	Credential string
}

type PrepareChannelCredentialRotationRow struct {
	ChannelID               int64
	ProviderID              int64
	ProviderEndpointID      int64
	Protocol                string
	AdapterKey              string
	Credential              string
	CredentialValid         bool
	ConfigRevision          int64
	CredentialChanged       bool
	ProviderSlug            string
	EndpointBaseUrl         string
	EndpointBaseUrlRevision int64
	EndpointStatusRevision  int64
}

// PrepareChannelCredentialRotation 原子判定同值/真变化并保存 credential。真变化只推进一次 config_revision，
// 同时先把 credential_valid 置 false、清空只属于旧 credential 的最近检测摘要；随后即时检测按返回的三类 revision 做 CAS。
func (q *Queries) PrepareChannelCredentialRotation(ctx context.Context, arg PrepareChannelCredentialRotationParams) (PrepareChannelCredentialRotationRow, error) {
	row := q.db.QueryRow(ctx, prepareChannelCredentialRotation, arg.ChannelID, arg.Credential)
	var i PrepareChannelCredentialRotationRow
	err := row.Scan(
		&i.ChannelID,
		&i.ProviderID,
		&i.ProviderEndpointID,
		&i.Protocol,
		&i.AdapterKey,
		&i.Credential,
		&i.CredentialValid,
		&i.ConfigRevision,
		&i.CredentialChanged,
		&i.ProviderSlug,
		&i.EndpointBaseUrl,
		&i.EndpointBaseUrlRevision,
		&i.EndpointStatusRevision,
	)
	return i, err
}

const restoreChannel = `-- name: RestoreChannel :execrows
UPDATE channels
SET status = 'disabled', archived_at = NULL,
    config_revision = config_revision + 1, updated_at = now()
WHERE id = $1 AND status = 'archived'
`

// RestoreChannel 取消归档渠道：archived → disabled（archived_at 清空）。名字保持归档时的后缀名
// （如需干净名由管理员手动改）。调用方需先保证所属 provider 非 archived（服务层护栏）。
func (q *Queries) RestoreChannel(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, restoreChannel, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setChannelBillingBehavior = `-- name: SetChannelBillingBehavior :one
UPDATE channels
SET upstream_bills_on_disconnect = $1, updated_at = now()
WHERE id = $2
RETURNING id, provider_id, provider_endpoint_id, name, protocol, adapter_key, credential, config_revision, admission_limits_revision, status, priority, timeout_ms, created_at, updated_at, rpm_limit, tpm_limit, rpd_limit, last_tested_at, last_test_ok, last_test_latency_ms, last_test_error, credential_valid, archived_at, concurrency_limit, upstream_bills_on_disconnect
`

type SetChannelBillingBehaviorParams struct {
	UpstreamBillsOnDisconnect bool
	ID                        int64
}

// SetChannelBillingBehavior 设置渠道「断开仍计费」标记（DESIGN-bill-on-cancel 阶段一）。
// true 表示上游在连接断开后仍会完成生成并计费（sub2api 类中转）；打开后失败/取消路径会记成本敞口。
func (q *Queries) SetChannelBillingBehavior(ctx context.Context, arg SetChannelBillingBehaviorParams) (Channel, error) {
	row := q.db.QueryRow(ctx, setChannelBillingBehavior, arg.UpstreamBillsOnDisconnect, arg.ID)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.ProviderEndpointID,
		&i.Name,
		&i.Protocol,
		&i.AdapterKey,
		&i.Credential,
		&i.ConfigRevision,
		&i.AdmissionLimitsRevision,
		&i.Status,
		&i.Priority,
		&i.TimeoutMs,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RpmLimit,
		&i.TpmLimit,
		&i.RpdLimit,
		&i.LastTestedAt,
		&i.LastTestOk,
		&i.LastTestLatencyMs,
		&i.LastTestError,
		&i.CredentialValid,
		&i.ArchivedAt,
		&i.ConcurrencyLimit,
		&i.UpstreamBillsOnDisconnect,
	)
	return i, err
}

const setChannelCredentialValid = `-- name: SetChannelCredentialValid :execrows
UPDATE channels
SET credential_valid = TRUE
WHERE id = $1 AND credential_valid = FALSE
`

// SetChannelCredentialValid 将渠道恢复为「凭据有效」。幂等：仅在 false→true 跳变时写入并返回受影响行数=1。
func (q *Queries) SetChannelCredentialValid(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, setChannelCredentialValid, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setChannelTestResult = `-- name: SetChannelTestResult :execrows
UPDATE channels
SET last_tested_at = now(),
    last_test_ok = $1,
    last_test_latency_ms = $2,
    last_test_error = $3
WHERE id = $4
`

type SetChannelTestResultParams struct {
	LastTestOk        pgtype.Bool
	LastTestLatencyMs pgtype.Int4
	LastTestError     pgtype.Text
	ID                int64
}

// SetChannelTestResult 写入渠道「最近一次主动检测结果」（渠道检测，阶段一）。
// last_tested_at 用 DB now() 保证服务器时钟；latency 恒有值（连接失败也测到耗时）；
// error 成功时为 NULL、失败时为可读原因。不改 updated_at（检测是运营遥测，非配置变更），
// 也不改 status（阶段一只报告不摘除）。返回受影响行数用于判定渠道是否存在。
func (q *Queries) SetChannelTestResult(ctx context.Context, arg SetChannelTestResultParams) (int64, error) {
	result, err := q.db.Exec(ctx, setChannelTestResult,
		arg.LastTestOk,
		arg.LastTestLatencyMs,
		arg.LastTestError,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateChannel = `-- name: UpdateChannel :one
UPDATE channels
SET name = $1,
    provider_endpoint_id = $2,
    status = $3,
    priority = $4,
    timeout_ms = $5,
    config_revision = config_revision + (
        CASE WHEN (
            provider_endpoint_id IS DISTINCT FROM $2
            OR status IS DISTINCT FROM $3
            OR timeout_ms IS DISTINCT FROM $5
        ) THEN 1 ELSE 0 END
    ),
    updated_at = now()
WHERE id = $6
RETURNING id, provider_id, provider_endpoint_id, name, protocol, adapter_key, credential, config_revision, admission_limits_revision, status, priority, timeout_ms, created_at, updated_at, rpm_limit, tpm_limit, rpd_limit, last_tested_at, last_test_ok, last_test_latency_ms, last_test_error, credential_valid, archived_at, concurrency_limit, upstream_bills_on_disconnect
`

type UpdateChannelParams struct {
	Name               string
	ProviderEndpointID int64
	Status             string
	Priority           int32
	TimeoutMs          pgtype.Int4
	ID                 int64
}

// UpdateChannel 更新 channel 的展示名、绑定 Endpoint、启停状态、优先级与超时；protocol、adapter_key 与凭据不在此更新。
// [P4 §4.4] base_url 已移除（地址归 provider_endpoints）；config_revision 递增由服务层在真变化时于同事务处理。
func (q *Queries) UpdateChannel(ctx context.Context, arg UpdateChannelParams) (Channel, error) {
	row := q.db.QueryRow(ctx, updateChannel,
		arg.Name,
		arg.ProviderEndpointID,
		arg.Status,
		arg.Priority,
		arg.TimeoutMs,
		arg.ID,
	)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.ProviderEndpointID,
		&i.Name,
		&i.Protocol,
		&i.AdapterKey,
		&i.Credential,
		&i.ConfigRevision,
		&i.AdmissionLimitsRevision,
		&i.Status,
		&i.Priority,
		&i.TimeoutMs,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RpmLimit,
		&i.TpmLimit,
		&i.RpdLimit,
		&i.LastTestedAt,
		&i.LastTestOk,
		&i.LastTestLatencyMs,
		&i.LastTestError,
		&i.CredentialValid,
		&i.ArchivedAt,
		&i.ConcurrencyLimit,
		&i.UpstreamBillsOnDisconnect,
	)
	return i, err
}

const updateChannelCostMultiplierWindow = `-- name: UpdateChannelCostMultiplierWindow :one
UPDATE channel_cost_multipliers
SET effective_to = $1,
    status = $2,
    updated_at = now()
WHERE id = $3
RETURNING id, channel_id, model_id, multiplier, status, effective_from, effective_to, created_at, updated_at, model_key
`

type UpdateChannelCostMultiplierWindowParams struct {
	EffectiveTo pgtype.Timestamptz
	Status      string
	ID          int64
}

// UpdateChannelCostMultiplierWindow 调整生效结束时间与启停状态；倍率数值不可改（改倍率请新建一条），账务可复算。
func (q *Queries) UpdateChannelCostMultiplierWindow(ctx context.Context, arg UpdateChannelCostMultiplierWindowParams) (ChannelCostMultiplier, error) {
	row := q.db.QueryRow(ctx, updateChannelCostMultiplierWindow, arg.EffectiveTo, arg.Status, arg.ID)
	var i ChannelCostMultiplier
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.ModelID,
		&i.Multiplier,
		&i.Status,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ModelKey,
	)
	return i, err
}

const updateChannelCredential = `-- name: UpdateChannelCredential :execrows
UPDATE channels
SET credential = $1, updated_at = now()
WHERE id = $2
`

type UpdateChannelCredentialParams struct {
	Credential string
	ID         int64
}

// UpdateChannelCredential 更新 channel 的明文上游凭据；返回受影响行数用于判定 channel 是否存在。
func (q *Queries) UpdateChannelCredential(ctx context.Context, arg UpdateChannelCredentialParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateChannelCredential, arg.Credential, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateChannelModel = `-- name: UpdateChannelModel :one
UPDATE channel_models
SET upstream_model = $1, status = $2, updated_at = now()
WHERE channel_id = $3 AND model_id = $4
RETURNING id, channel_id, model_id, upstream_model, status, created_at, updated_at
`

type UpdateChannelModelParams struct {
	UpstreamModel string
	Status        string
	ChannelID     int64
	ModelID       int64
}

// UpdateChannelModel 更新绑定的上游模型名与启停状态；按 (channel_id, model_id) 定位。
func (q *Queries) UpdateChannelModel(ctx context.Context, arg UpdateChannelModelParams) (ChannelModel, error) {
	row := q.db.QueryRow(ctx, updateChannelModel,
		arg.UpstreamModel,
		arg.Status,
		arg.ChannelID,
		arg.ModelID,
	)
	var i ChannelModel
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.ModelID,
		&i.UpstreamModel,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateChannelPriceWindow = `-- name: UpdateChannelPriceWindow :one
UPDATE channel_prices
SET effective_to = $1,
    status = $2,
    updated_at = now()
WHERE id = $3
RETURNING id, channel_id, model_id, currency, pricing_unit, uncached_input_cost, cache_read_input_cost, cache_write_5m_input_cost, cache_write_1h_input_cost, output_cost, reasoning_output_cost, status, effective_from, effective_to, created_at, updated_at, cache_write_30m_input_cost
`

type UpdateChannelPriceWindowParams struct {
	EffectiveTo pgtype.Timestamptz
	Status      string
	ID          int64
}

// UpdateChannelPriceWindow 调整生效结束时间与启停状态；金额不可改（改价请新建一条），账务可复算。
func (q *Queries) UpdateChannelPriceWindow(ctx context.Context, arg UpdateChannelPriceWindowParams) (ChannelPrice, error) {
	row := q.db.QueryRow(ctx, updateChannelPriceWindow, arg.EffectiveTo, arg.Status, arg.ID)
	var i ChannelPrice
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.ModelID,
		&i.Currency,
		&i.PricingUnit,
		&i.UncachedInputCost,
		&i.CacheReadInputCost,
		&i.CacheWrite5mInputCost,
		&i.CacheWrite1hInputCost,
		&i.OutputCost,
		&i.ReasoningOutputCost,
		&i.Status,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CacheWrite30mInputCost,
	)
	return i, err
}

const updateChannelRechargeFactorWindow = `-- name: UpdateChannelRechargeFactorWindow :one
UPDATE channel_recharge_factors
SET effective_to = $1,
    status = $2,
    updated_at = now()
WHERE id = $3
RETURNING id, channel_id, factor, status, effective_from, effective_to, created_at, updated_at
`

type UpdateChannelRechargeFactorWindowParams struct {
	EffectiveTo pgtype.Timestamptz
	Status      string
	ID          int64
}

// UpdateChannelRechargeFactorWindow 调整生效结束时间与启停状态；倍率数值不可改（改倍率请新建一条），账务可复算。
func (q *Queries) UpdateChannelRechargeFactorWindow(ctx context.Context, arg UpdateChannelRechargeFactorWindowParams) (ChannelRechargeFactor, error) {
	row := q.db.QueryRow(ctx, updateChannelRechargeFactorWindow, arg.EffectiveTo, arg.Status, arg.ID)
	var i ChannelRechargeFactor
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.Factor,
		&i.Status,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
