// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: channel_models.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createChannelModel = `-- name: CreateChannelModel :one
INSERT INTO channel_models (channel_id, model_id, upstream_model, status)
VALUES ($1, $2, $3, $4)
RETURNING id, channel_id, model_id, upstream_model, status, created_at, updated_at
`

type CreateChannelModelParams struct {
	ChannelID     int64
	ModelID       int64
	UpstreamModel string
	Status        string
}

// CreateChannelModel 创建 channel↔model 绑定；同一 channel 对同一 model 只能绑定一次（唯一约束）。
func (q *Queries) CreateChannelModel(ctx context.Context, arg CreateChannelModelParams) (ChannelModel, error) {
	row := q.db.QueryRow(ctx, createChannelModel,
		arg.ChannelID,
		arg.ModelID,
		arg.UpstreamModel,
		arg.Status,
	)
	var i ChannelModel
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.ModelID,
		&i.UpstreamModel,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteChannelModel = `-- name: DeleteChannelModel :execrows
DELETE FROM channel_models
WHERE channel_id = $1 AND model_id = $2
`

type DeleteChannelModelParams struct {
	ChannelID int64
	ModelID   int64
}

// DeleteChannelModel 删除绑定；被 cost_snapshots/channel_prices 外键引用时由 DB 拒绝（23503），上层降级为 conflict。
func (q *Queries) DeleteChannelModel(ctx context.Context, arg DeleteChannelModelParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteChannelModel, arg.ChannelID, arg.ModelID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findRouteCandidates = `-- name: FindRouteCandidates :many
WITH project_scope AS (
    SELECT $6::BIGINT AS project_id
),
project_policy_mode AS (
    SELECT EXISTS (
        SELECT 1
        FROM project_model_policies pmp
        JOIN project_scope ps ON ps.project_id = pmp.project_id
        WHERE pmp.visibility = 'allowed'
    ) AS has_allow_list
)
SELECT
    m.id AS model_db_id,
    m.model_id AS requested_model_id,
    m.max_output_tokens AS model_max_output_tokens,
    p.id AS provider_id,
    p.slug AS provider_slug,
    c.adapter_key AS adapter_key,
    c.protocol AS protocol,
    c.id AS channel_id,
    c.base_url,
    c.credential_encrypted,
    c.timeout_ms,
    c.priority,
    c.rpm_limit AS channel_rpm_limit,
    c.tpm_limit AS channel_tpm_limit,
    c.rpd_limit AS channel_rpd_limit,
    cm.upstream_model,
    price.id AS channel_price_id,
    price.currency AS price_currency,
    price.pricing_unit AS price_pricing_unit,
    price.uncached_input_price,
    price.cache_read_input_price,
    price.cache_write_5m_input_price,
    price.cache_write_1h_input_price,
    price.output_price,
    price.reasoning_output_price
FROM channel_models cm
JOIN models m ON m.id = cm.model_id
JOIN channels c ON c.id = cm.channel_id
JOIN providers p ON p.id = c.provider_id
JOIN project_scope ps ON ps.project_id > 0
JOIN LATERAL (
    SELECT cp.id, cp.currency, cp.pricing_unit,
        cp.uncached_input_price, cp.cache_read_input_price,
        cp.cache_write_5m_input_price, cp.cache_write_1h_input_price,
        cp.output_price, cp.reasoning_output_price
    FROM channel_prices cp
    WHERE cp.channel_id = c.id
      AND cp.model_id = m.id
      AND cp.status = 'enabled'
      AND cp.effective_from <= $1
      AND (cp.effective_to IS NULL OR cp.effective_to > $1)
    ORDER BY cp.effective_from DESC, cp.id DESC
    LIMIT 1
) price ON TRUE
WHERE m.model_id = $2
  AND c.protocol = $3
  AND m.status = 'enabled'
  AND cm.status = 'enabled'
  AND c.status = 'enabled'
  AND p.status = 'enabled'
  AND (
    $4::TEXT = 'all'
        OR EXISTS (
        SELECT 1
        FROM route_channels rc
        WHERE rc.route_id = $5
          AND rc.channel_id = c.id
    )
  )
  AND NOT EXISTS (
    SELECT 1
    FROM project_model_policies denied
    JOIN project_scope ps ON ps.project_id = denied.project_id
    WHERE denied.model_id = m.id
      AND denied.visibility = 'denied'
)
  AND (
    NOT (SELECT has_allow_list FROM project_policy_mode)
        OR EXISTS (
        SELECT 1
        FROM project_model_policies allowed
        JOIN project_scope ps ON ps.project_id = allowed.project_id
        WHERE allowed.model_id = m.id
          AND allowed.visibility = 'allowed'
    )
    )
ORDER BY
    c.priority ASC,
    c.id ASC
`

type FindRouteCandidatesParams struct {
	AtTime           pgtype.Timestamptz
	RequestedModelID string
	IngressProtocol  string
	PoolKind         string
	RouteID          int64
	ProjectID        int64
}

type FindRouteCandidatesRow struct {
	ModelDbID              int64
	RequestedModelID       string
	ModelMaxOutputTokens   pgtype.Int8
	ProviderID             int64
	ProviderSlug           string
	AdapterKey             string
	Protocol               string
	ChannelID              int64
	BaseUrl                string
	CredentialEncrypted    []byte
	TimeoutMs              pgtype.Int4
	Priority               int32
	ChannelRpmLimit        pgtype.Int4
	ChannelTpmLimit        pgtype.Int4
	ChannelRpdLimit        pgtype.Int4
	UpstreamModel          string
	ChannelPriceID         int64
	PriceCurrency          string
	PricePricingUnit       string
	UncachedInputPrice     pgtype.Numeric
	CacheReadInputPrice    pgtype.Numeric
	CacheWrite5mInputPrice pgtype.Numeric
	CacheWrite1hInputPrice pgtype.Numeric
	OutputPrice            pgtype.Numeric
	ReasoningOutputPrice   pgtype.Numeric
}

// FindRouteCandidates 按请求模型、项目策略与线路查找可用 channel 路由候选（阶段 15）。
// 在既有过滤（model/channel/provider/cm enabled + 协议 + 项目 allow/deny）之上叠加：
//  1. 线路候选池：pool_kind='explicit' 时候选 ∩ route_channels（fixed 即只剩一条）；
//  2. 已定价过滤：候选必须在 channel_prices 有「当前生效、enabled」的售价行（未定价渠道排除，不参与计费）；
//  3. 带回命中渠道的当前生效售价（供 Go 侧 cheapest 排序与保守预授权上界）。
//
// 策略排序（cheapest/stable/fixed）在 Go 侧完成；此处仅给稳定的 priority 基序。
func (q *Queries) FindRouteCandidates(ctx context.Context, arg FindRouteCandidatesParams) ([]FindRouteCandidatesRow, error) {
	rows, err := q.db.Query(ctx, findRouteCandidates,
		arg.AtTime,
		arg.RequestedModelID,
		arg.IngressProtocol,
		arg.PoolKind,
		arg.RouteID,
		arg.ProjectID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindRouteCandidatesRow
	for rows.Next() {
		var i FindRouteCandidatesRow
		if err := rows.Scan(
			&i.ModelDbID,
			&i.RequestedModelID,
			&i.ModelMaxOutputTokens,
			&i.ProviderID,
			&i.ProviderSlug,
			&i.AdapterKey,
			&i.Protocol,
			&i.ChannelID,
			&i.BaseUrl,
			&i.CredentialEncrypted,
			&i.TimeoutMs,
			&i.Priority,
			&i.ChannelRpmLimit,
			&i.ChannelTpmLimit,
			&i.ChannelRpdLimit,
			&i.UpstreamModel,
			&i.ChannelPriceID,
			&i.PriceCurrency,
			&i.PricePricingUnit,
			&i.UncachedInputPrice,
			&i.CacheReadInputPrice,
			&i.CacheWrite5mInputPrice,
			&i.CacheWrite1hInputPrice,
			&i.OutputPrice,
			&i.ReasoningOutputPrice,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChannelModel = `-- name: GetChannelModel :one
SELECT id, channel_id, model_id, upstream_model, status, created_at, updated_at
FROM channel_models
WHERE channel_id = $1 AND model_id = $2
LIMIT 1
`

type GetChannelModelParams struct {
	ChannelID int64
	ModelID   int64
}

// GetChannelModel 按 (channel_id, model_id) 读取单条绑定。
func (q *Queries) GetChannelModel(ctx context.Context, arg GetChannelModelParams) (ChannelModel, error) {
	row := q.db.QueryRow(ctx, getChannelModel, arg.ChannelID, arg.ModelID)
	var i ChannelModel
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.ModelID,
		&i.UpstreamModel,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listChannelModelsByChannel = `-- name: ListChannelModelsByChannel :many
SELECT
    cm.id,
    cm.channel_id,
    cm.model_id,
    cm.upstream_model,
    cm.status,
    cm.created_at,
    cm.updated_at,
    m.model_id AS model_external_id,
    m.display_name AS model_display_name
FROM channel_models cm
JOIN models m ON m.id = cm.model_id
WHERE cm.channel_id = $1
ORDER BY m.model_id
`

type ListChannelModelsByChannelRow struct {
	ID               int64
	ChannelID        int64
	ModelID          int64
	UpstreamModel    string
	Status           string
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	ModelExternalID  string
	ModelDisplayName string
}

// ListChannelModelsByChannel 列出某 channel 的全部模型绑定，连带 Unio 侧模型的对外 ID 与展示名，供 admin 管理台展示。
func (q *Queries) ListChannelModelsByChannel(ctx context.Context, channelID int64) ([]ListChannelModelsByChannelRow, error) {
	rows, err := q.db.Query(ctx, listChannelModelsByChannel, channelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChannelModelsByChannelRow
	for rows.Next() {
		var i ListChannelModelsByChannelRow
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.ModelID,
			&i.UpstreamModel,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ModelExternalID,
			&i.ModelDisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateChannelModel = `-- name: UpdateChannelModel :one
UPDATE channel_models
SET upstream_model = $1, status = $2, updated_at = now()
WHERE channel_id = $3 AND model_id = $4
RETURNING id, channel_id, model_id, upstream_model, status, created_at, updated_at
`

type UpdateChannelModelParams struct {
	UpstreamModel string
	Status        string
	ChannelID     int64
	ModelID       int64
}

// UpdateChannelModel 更新绑定的上游模型名与启停状态；按 (channel_id, model_id) 定位。
func (q *Queries) UpdateChannelModel(ctx context.Context, arg UpdateChannelModelParams) (ChannelModel, error) {
	row := q.db.QueryRow(ctx, updateChannelModel,
		arg.UpstreamModel,
		arg.Status,
		arg.ChannelID,
		arg.ModelID,
	)
	var i ChannelModel
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.ModelID,
		&i.UpstreamModel,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
