// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cost_snapshots.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCostSnapshot = `-- name: CreateCostSnapshot :one
INSERT INTO cost_snapshots (
    request_record_id,
    cost_price_id,
    provider_id,
    channel_id,
    model_id,
    upstream_model,
    currency,
    pricing_unit,
    uncached_input_cost,
    cache_read_input_cost,
    cache_write_5m_input_cost,
    cache_write_1h_input_cost,
    output_cost,
    reasoning_output_cost,
    uncached_input_cost_amount,
    cache_read_input_cost_amount,
    cache_write_5m_input_cost_amount,
    cache_write_1h_input_cost_amount,
    output_cost_amount,
    reasoning_output_cost_amount,
    total_cost_amount,
    formula_version
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    $15,
    $16,
    $17,
    $18,
    $19,
    $20,
    $21,
    $22
)
RETURNING id, request_record_id, cost_price_id, provider_id, channel_id, model_id, upstream_model, currency, pricing_unit, uncached_input_cost, cache_read_input_cost, cache_write_5m_input_cost, cache_write_1h_input_cost, output_cost, reasoning_output_cost, uncached_input_cost_amount, cache_read_input_cost_amount, cache_write_5m_input_cost_amount, cache_write_1h_input_cost_amount, output_cost_amount, reasoning_output_cost_amount, total_cost_amount, formula_version, created_at
`

type CreateCostSnapshotParams struct {
	RequestRecordID             int64
	CostPriceID                 int64
	ProviderID                  int64
	ChannelID                   int64
	ModelID                     int64
	UpstreamModel               string
	Currency                    string
	PricingUnit                 string
	UncachedInputCost           pgtype.Numeric
	CacheReadInputCost          pgtype.Numeric
	CacheWrite5mInputCost       pgtype.Numeric
	CacheWrite1hInputCost       pgtype.Numeric
	OutputCost                  pgtype.Numeric
	ReasoningOutputCost         pgtype.Numeric
	UncachedInputCostAmount     pgtype.Numeric
	CacheReadInputCostAmount    pgtype.Numeric
	CacheWrite5mInputCostAmount pgtype.Numeric
	CacheWrite1hInputCostAmount pgtype.Numeric
	OutputCostAmount            pgtype.Numeric
	ReasoningOutputCostAmount   pgtype.Numeric
	TotalCostAmount             pgtype.Numeric
	FormulaVersion              string
}

// CreateCostSnapshot 创建一次请求结算使用的上游成本价快照和实际成本事实。
func (q *Queries) CreateCostSnapshot(ctx context.Context, arg CreateCostSnapshotParams) (CostSnapshot, error) {
	row := q.db.QueryRow(ctx, createCostSnapshot,
		arg.RequestRecordID,
		arg.CostPriceID,
		arg.ProviderID,
		arg.ChannelID,
		arg.ModelID,
		arg.UpstreamModel,
		arg.Currency,
		arg.PricingUnit,
		arg.UncachedInputCost,
		arg.CacheReadInputCost,
		arg.CacheWrite5mInputCost,
		arg.CacheWrite1hInputCost,
		arg.OutputCost,
		arg.ReasoningOutputCost,
		arg.UncachedInputCostAmount,
		arg.CacheReadInputCostAmount,
		arg.CacheWrite5mInputCostAmount,
		arg.CacheWrite1hInputCostAmount,
		arg.OutputCostAmount,
		arg.ReasoningOutputCostAmount,
		arg.TotalCostAmount,
		arg.FormulaVersion,
	)
	var i CostSnapshot
	err := row.Scan(
		&i.ID,
		&i.RequestRecordID,
		&i.CostPriceID,
		&i.ProviderID,
		&i.ChannelID,
		&i.ModelID,
		&i.UpstreamModel,
		&i.Currency,
		&i.PricingUnit,
		&i.UncachedInputCost,
		&i.CacheReadInputCost,
		&i.CacheWrite5mInputCost,
		&i.CacheWrite1hInputCost,
		&i.OutputCost,
		&i.ReasoningOutputCost,
		&i.UncachedInputCostAmount,
		&i.CacheReadInputCostAmount,
		&i.CacheWrite5mInputCostAmount,
		&i.CacheWrite1hInputCostAmount,
		&i.OutputCostAmount,
		&i.ReasoningOutputCostAmount,
		&i.TotalCostAmount,
		&i.FormulaVersion,
		&i.CreatedAt,
	)
	return i, err
}

const getCostSnapshotByRequest = `-- name: GetCostSnapshotByRequest :one
SELECT id, request_record_id, cost_price_id, provider_id, channel_id, model_id, upstream_model, currency, pricing_unit, uncached_input_cost, cache_read_input_cost, cache_write_5m_input_cost, cache_write_1h_input_cost, output_cost, reasoning_output_cost, uncached_input_cost_amount, cache_read_input_cost_amount, cache_write_5m_input_cost_amount, cache_write_1h_input_cost_amount, output_cost_amount, reasoning_output_cost_amount, total_cost_amount, formula_version, created_at
FROM cost_snapshots
WHERE request_record_id = $1
`

// GetCostSnapshotByRequest 按请求 ID 读取上游成本快照。
func (q *Queries) GetCostSnapshotByRequest(ctx context.Context, requestRecordID int64) (CostSnapshot, error) {
	row := q.db.QueryRow(ctx, getCostSnapshotByRequest, requestRecordID)
	var i CostSnapshot
	err := row.Scan(
		&i.ID,
		&i.RequestRecordID,
		&i.CostPriceID,
		&i.ProviderID,
		&i.ChannelID,
		&i.ModelID,
		&i.UpstreamModel,
		&i.Currency,
		&i.PricingUnit,
		&i.UncachedInputCost,
		&i.CacheReadInputCost,
		&i.CacheWrite5mInputCost,
		&i.CacheWrite1hInputCost,
		&i.OutputCost,
		&i.ReasoningOutputCost,
		&i.UncachedInputCostAmount,
		&i.CacheReadInputCostAmount,
		&i.CacheWrite5mInputCostAmount,
		&i.CacheWrite1hInputCostAmount,
		&i.OutputCostAmount,
		&i.ReasoningOutputCostAmount,
		&i.TotalCostAmount,
		&i.FormulaVersion,
		&i.CreatedAt,
	)
	return i, err
}
