// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ledger.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countChannelCostExposures = `-- name: CountChannelCostExposures :one
SELECT COUNT(*) AS total
FROM channel_cost_exposures e
WHERE e.channel_id = $1
  AND e.created_at >= $2
  AND e.created_at < $3
`

type CountChannelCostExposuresParams struct {
	ChannelID int64
	FromTime  pgtype.Timestamptz
	ToTime    pgtype.Timestamptz
}

// CountChannelCostExposures 返回与 ListChannelCostExposuresPage 相同过滤条件下的总条数。
func (q *Queries) CountChannelCostExposures(ctx context.Context, arg CountChannelCostExposuresParams) (int64, error) {
	row := q.db.QueryRow(ctx, countChannelCostExposures, arg.ChannelID, arg.FromTime, arg.ToTime)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countLedgerBillingExceptions = `-- name: CountLedgerBillingExceptions :one
SELECT COUNT(*) AS total
FROM ledger_billing_exceptions
WHERE ($1::bigint IS NULL OR user_id = $1::bigint)
  AND ($2::text IS NULL OR event_type = $2::text)
  AND ($3::text IS NULL OR reason_code = $3::text)
  AND ($4::timestamptz IS NULL OR created_at >= $4::timestamptz)
  AND ($5::timestamptz IS NULL OR created_at < $5::timestamptz)
`

type CountLedgerBillingExceptionsParams struct {
	UserID     pgtype.Int8
	EventType  pgtype.Text
	ReasonCode pgtype.Text
	FromTime   pgtype.Timestamptz
	ToTime     pgtype.Timestamptz
}

// CountLedgerBillingExceptions 返回与 ListLedgerBillingExceptionsPage 相同过滤条件下的总条数。
func (q *Queries) CountLedgerBillingExceptions(ctx context.Context, arg CountLedgerBillingExceptionsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countLedgerBillingExceptions,
		arg.UserID,
		arg.EventType,
		arg.ReasonCode,
		arg.FromTime,
		arg.ToTime,
	)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countLedgerEntries = `-- name: CountLedgerEntries :one
SELECT COUNT(*) AS total
FROM ledger_entries
WHERE ($1::bigint IS NULL OR user_id = $1::bigint)
  AND ($2::text IS NULL OR entry_type = $2::text)
  AND ($3::text IS NULL OR currency = $3::text)
  AND ($4::timestamptz IS NULL OR created_at >= $4::timestamptz)
  AND ($5::timestamptz IS NULL OR created_at < $5::timestamptz)
`

type CountLedgerEntriesParams struct {
	UserID    pgtype.Int8
	EntryType pgtype.Text
	Currency  pgtype.Text
	FromTime  pgtype.Timestamptz
	ToTime    pgtype.Timestamptz
}

// CountLedgerEntries 返回与 ListLedgerEntriesPage 相同过滤条件下的总条数。
func (q *Queries) CountLedgerEntries(ctx context.Context, arg CountLedgerEntriesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countLedgerEntries,
		arg.UserID,
		arg.EntryType,
		arg.Currency,
		arg.FromTime,
		arg.ToTime,
	)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const getLedgerBillingExceptionByRequest = `-- name: GetLedgerBillingExceptionByRequest :one
SELECT id, user_id, request_record_id, reservation_id, event_type, actual_amount, captured_amount, platform_amount, currency, reason_code, reason, created_at
FROM ledger_billing_exceptions
WHERE request_record_id = $1
`

// GetLedgerBillingExceptionByRequest 按请求记录 ID 读取该请求的 billing exception（每请求至多一条）。
func (q *Queries) GetLedgerBillingExceptionByRequest(ctx context.Context, requestRecordID int64) (LedgerBillingException, error) {
	row := q.db.QueryRow(ctx, getLedgerBillingExceptionByRequest, requestRecordID)
	var i LedgerBillingException
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RequestRecordID,
		&i.ReservationID,
		&i.EventType,
		&i.ActualAmount,
		&i.CapturedAmount,
		&i.PlatformAmount,
		&i.Currency,
		&i.ReasonCode,
		&i.Reason,
		&i.CreatedAt,
	)
	return i, err
}

const listChannelCostExposuresPage = `-- name: ListChannelCostExposuresPage :many
SELECT
    e.id,
    e.request_record_id,
    r.request_id,
    e.attempt_id,
    e.channel_id,
    e.provider_id,
    e.reason,
    e.estimated_input_tokens,
    e.assumed_output_tokens,
    e.estimated_cost_amount,
    e.currency,
    e.created_at
FROM channel_cost_exposures e
JOIN request_records r ON r.id = e.request_record_id
WHERE e.channel_id = $1
  AND e.created_at >= $2
  AND e.created_at < $3
ORDER BY e.created_at DESC, e.id DESC
LIMIT $5 OFFSET $4
`

type ListChannelCostExposuresPageParams struct {
	ChannelID  int64
	FromTime   pgtype.Timestamptz
	ToTime     pgtype.Timestamptz
	PageOffset int32
	PageLimit  int32
}

type ListChannelCostExposuresPageRow struct {
	ID                   int64
	RequestRecordID      int64
	RequestID            string
	AttemptID            int64
	ChannelID            int64
	ProviderID           int64
	Reason               string
	EstimatedInputTokens int64
	AssumedOutputTokens  int64
	EstimatedCostAmount  pgtype.Numeric
	Currency             string
	CreatedAt            pgtype.Timestamptz
}

// ListChannelCostExposuresPage 按渠道分页倒序列出成本敞口明细，连带对外 request_id 供跳转排查。
func (q *Queries) ListChannelCostExposuresPage(ctx context.Context, arg ListChannelCostExposuresPageParams) ([]ListChannelCostExposuresPageRow, error) {
	rows, err := q.db.Query(ctx, listChannelCostExposuresPage,
		arg.ChannelID,
		arg.FromTime,
		arg.ToTime,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChannelCostExposuresPageRow
	for rows.Next() {
		var i ListChannelCostExposuresPageRow
		if err := rows.Scan(
			&i.ID,
			&i.RequestRecordID,
			&i.RequestID,
			&i.AttemptID,
			&i.ChannelID,
			&i.ProviderID,
			&i.Reason,
			&i.EstimatedInputTokens,
			&i.AssumedOutputTokens,
			&i.EstimatedCostAmount,
			&i.Currency,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLedgerBillingExceptionsPage = `-- name: ListLedgerBillingExceptionsPage :many
SELECT
    e.id,
    e.user_id,
    u.display_name AS user_display_name,
    u.email AS user_email,
    e.request_record_id,
    r.request_id,
    e.reservation_id,
    e.event_type,
    e.actual_amount,
    e.captured_amount,
    e.platform_amount,
    e.currency,
    e.reason_code,
    e.reason,
    e.created_at
FROM ledger_billing_exceptions e
JOIN request_records r ON r.id = e.request_record_id
JOIN users u ON u.id = e.user_id
WHERE ($1::bigint IS NULL OR e.user_id = $1::bigint)
  AND ($2::text IS NULL OR e.event_type = $2::text)
  AND ($3::text IS NULL OR e.reason_code = $3::text)
  AND ($4::timestamptz IS NULL OR e.created_at >= $4::timestamptz)
  AND ($5::timestamptz IS NULL OR e.created_at < $5::timestamptz)
ORDER BY
  CASE WHEN COALESCE($6::text, 'created_at') IN ('', 'created_at') AND COALESCE($7::bool, true) THEN e.created_at END DESC NULLS LAST,
  CASE WHEN COALESCE($6::text, 'created_at') IN ('', 'created_at') AND NOT COALESCE($7::bool, true) THEN e.created_at END ASC NULLS LAST,
  CASE WHEN $6::text = 'user_id' AND COALESCE($7::bool, false) THEN e.user_id END DESC NULLS LAST,
  CASE WHEN $6::text = 'user_id' AND NOT COALESCE($7::bool, false) THEN e.user_id END ASC NULLS LAST,
  CASE WHEN $6::text = 'event_type' AND COALESCE($7::bool, false) THEN e.event_type END DESC NULLS LAST,
  CASE WHEN $6::text = 'event_type' AND NOT COALESCE($7::bool, false) THEN e.event_type END ASC NULLS LAST,
  e.id DESC
LIMIT $9 OFFSET $8
`

type ListLedgerBillingExceptionsPageParams struct {
	UserID     pgtype.Int8
	EventType  pgtype.Text
	ReasonCode pgtype.Text
	FromTime   pgtype.Timestamptz
	ToTime     pgtype.Timestamptz
	SortField  pgtype.Text
	SortDesc   pgtype.Bool
	PageOffset int32
	PageLimit  int32
}

type ListLedgerBillingExceptionsPageRow struct {
	ID              int64
	UserID          int64
	UserDisplayName string
	UserEmail       string
	RequestRecordID int64
	RequestID       string
	ReservationID   int64
	EventType       string
	ActualAmount    pgtype.Numeric
	CapturedAmount  pgtype.Numeric
	PlatformAmount  pgtype.Numeric
	Currency        string
	ReasonCode      string
	Reason          string
	CreatedAt       pgtype.Timestamptz
}

// ListLedgerBillingExceptionsPage 供 admin 只读查询台（M6）按用户/事件类型/时间过滤分页倒序列出核销/风险敞口事实。
// 联表带出对外 request_id（跳转请求详情）与用户展示字段（用户名/邮箱）。所有过滤项为 NULL 时不过滤。
func (q *Queries) ListLedgerBillingExceptionsPage(ctx context.Context, arg ListLedgerBillingExceptionsPageParams) ([]ListLedgerBillingExceptionsPageRow, error) {
	rows, err := q.db.Query(ctx, listLedgerBillingExceptionsPage,
		arg.UserID,
		arg.EventType,
		arg.ReasonCode,
		arg.FromTime,
		arg.ToTime,
		arg.SortField,
		arg.SortDesc,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLedgerBillingExceptionsPageRow
	for rows.Next() {
		var i ListLedgerBillingExceptionsPageRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.UserDisplayName,
			&i.UserEmail,
			&i.RequestRecordID,
			&i.RequestID,
			&i.ReservationID,
			&i.EventType,
			&i.ActualAmount,
			&i.CapturedAmount,
			&i.PlatformAmount,
			&i.Currency,
			&i.ReasonCode,
			&i.Reason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLedgerEntriesByUser = `-- name: ListLedgerEntriesByUser :many
SELECT
    id,
    user_id,
    request_record_id,
    entry_type,
    amount,
    currency,
    balance_before,
    balance_after,
    idempotency_key,
    reason,
    created_at
FROM
    ledger_entries
WHERE
    user_id = $1
  AND currency = $2
ORDER BY
    created_at DESC,
    id DESC
LIMIT
    $4
    OFFSET
    $3
`

type ListLedgerEntriesByUserParams struct {
	UserID     int64
	Currency   string
	OffsetRows int32
	LimitRows  int32
}

// ListLedgerEntriesByUser 按用户和币种倒序列出账本流水。
func (q *Queries) ListLedgerEntriesByUser(ctx context.Context, arg ListLedgerEntriesByUserParams) ([]LedgerEntry, error) {
	rows, err := q.db.Query(ctx, listLedgerEntriesByUser,
		arg.UserID,
		arg.Currency,
		arg.OffsetRows,
		arg.LimitRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LedgerEntry
	for rows.Next() {
		var i LedgerEntry
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.RequestRecordID,
			&i.EntryType,
			&i.Amount,
			&i.Currency,
			&i.BalanceBefore,
			&i.BalanceAfter,
			&i.IdempotencyKey,
			&i.Reason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLedgerEntriesPage = `-- name: ListLedgerEntriesPage :many
SELECT
    e.id,
    e.user_id,
    u.display_name AS user_display_name,
    u.email AS user_email,
    e.request_record_id,
    e.entry_type,
    e.amount,
    e.currency,
    e.balance_before,
    e.balance_after,
    e.idempotency_key,
    e.reason,
    e.created_at
FROM ledger_entries e
JOIN users u ON u.id = e.user_id
WHERE ($1::bigint IS NULL OR e.user_id = $1::bigint)
  AND ($2::text IS NULL OR e.entry_type = $2::text)
  AND ($3::text IS NULL OR e.currency = $3::text)
  AND ($4::timestamptz IS NULL OR e.created_at >= $4::timestamptz)
  AND ($5::timestamptz IS NULL OR e.created_at < $5::timestamptz)
ORDER BY
  CASE WHEN COALESCE($6::text, 'created_at') IN ('', 'created_at') AND COALESCE($7::bool, true) THEN e.created_at END DESC NULLS LAST,
  CASE WHEN COALESCE($6::text, 'created_at') IN ('', 'created_at') AND NOT COALESCE($7::bool, true) THEN e.created_at END ASC NULLS LAST,
  CASE WHEN $6::text = 'user_id' AND COALESCE($7::bool, false) THEN e.user_id END DESC NULLS LAST,
  CASE WHEN $6::text = 'user_id' AND NOT COALESCE($7::bool, false) THEN e.user_id END ASC NULLS LAST,
  CASE WHEN $6::text = 'amount' AND COALESCE($7::bool, false) THEN e.amount END DESC NULLS LAST,
  CASE WHEN $6::text = 'amount' AND NOT COALESCE($7::bool, false) THEN e.amount END ASC NULLS LAST,
  CASE WHEN $6::text = 'entry_type' AND COALESCE($7::bool, false) THEN e.entry_type END DESC NULLS LAST,
  CASE WHEN $6::text = 'entry_type' AND NOT COALESCE($7::bool, false) THEN e.entry_type END ASC NULLS LAST,
  e.id DESC
LIMIT $9 OFFSET $8
`

type ListLedgerEntriesPageParams struct {
	UserID     pgtype.Int8
	EntryType  pgtype.Text
	Currency   pgtype.Text
	FromTime   pgtype.Timestamptz
	ToTime     pgtype.Timestamptz
	SortField  pgtype.Text
	SortDesc   pgtype.Bool
	PageOffset int32
	PageLimit  int32
}

type ListLedgerEntriesPageRow struct {
	ID              int64
	UserID          int64
	UserDisplayName string
	UserEmail       string
	RequestRecordID pgtype.Int8
	EntryType       string
	Amount          pgtype.Numeric
	Currency        string
	BalanceBefore   pgtype.Numeric
	BalanceAfter    pgtype.Numeric
	IdempotencyKey  string
	Reason          string
	CreatedAt       pgtype.Timestamptz
}

// ListLedgerEntriesPage 供 admin 只读查询台（M6）按用户/类型/币种/时间过滤分页倒序列出账本流水。
// 联表带出用户展示字段（用户名/邮箱）。所有过滤项为 NULL 时不过滤。
func (q *Queries) ListLedgerEntriesPage(ctx context.Context, arg ListLedgerEntriesPageParams) ([]ListLedgerEntriesPageRow, error) {
	rows, err := q.db.Query(ctx, listLedgerEntriesPage,
		arg.UserID,
		arg.EntryType,
		arg.Currency,
		arg.FromTime,
		arg.ToTime,
		arg.SortField,
		arg.SortDesc,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLedgerEntriesPageRow
	for rows.Next() {
		var i ListLedgerEntriesPageRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.UserDisplayName,
			&i.UserEmail,
			&i.RequestRecordID,
			&i.EntryType,
			&i.Amount,
			&i.Currency,
			&i.BalanceBefore,
			&i.BalanceAfter,
			&i.IdempotencyKey,
			&i.Reason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const summarizeChannelCostExposures = `-- name: SummarizeChannelCostExposures :many
SELECT
    e.channel_id,
    c.name AS channel_name,
    e.provider_id,
    e.currency,
    COUNT(*) AS exposures,
    COALESCE(SUM(e.estimated_cost_amount), 0)::numeric AS total_estimated_cost
FROM channel_cost_exposures e
JOIN channels c ON c.id = e.channel_id
WHERE e.created_at >= $1
  AND e.created_at < $2
GROUP BY e.channel_id, c.name, e.provider_id, e.currency
ORDER BY total_estimated_cost DESC
`

type SummarizeChannelCostExposuresParams struct {
	FromTime pgtype.Timestamptz
	ToTime   pgtype.Timestamptz
}

type SummarizeChannelCostExposuresRow struct {
	ChannelID          int64
	ChannelName        string
	ProviderID         int64
	Currency           string
	Exposures          int64
	TotalEstimatedCost pgtype.Numeric
}

// SummarizeChannelCostExposures 按渠道聚合时间范围内的成本敞口（条数 + 金额上界合计），供渠道成本对账。
func (q *Queries) SummarizeChannelCostExposures(ctx context.Context, arg SummarizeChannelCostExposuresParams) ([]SummarizeChannelCostExposuresRow, error) {
	rows, err := q.db.Query(ctx, summarizeChannelCostExposures, arg.FromTime, arg.ToTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SummarizeChannelCostExposuresRow
	for rows.Next() {
		var i SummarizeChannelCostExposuresRow
		if err := rows.Scan(
			&i.ChannelID,
			&i.ChannelName,
			&i.ProviderID,
			&i.Currency,
			&i.Exposures,
			&i.TotalEstimatedCost,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
