// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: model_prices.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createModelPrice = `-- name: CreateModelPrice :one
INSERT INTO model_prices (
    model_id,
    currency,
    pricing_unit,
    uncached_input_price,
    cache_read_input_price,
    cache_write_5m_input_price,
    cache_write_1h_input_price,
    output_price,
    reasoning_output_price,
    status,
    effective_from,
    effective_to
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12
)
RETURNING id, model_id, currency, pricing_unit, uncached_input_price, cache_read_input_price, cache_write_5m_input_price, cache_write_1h_input_price, output_price, reasoning_output_price, status, effective_from, effective_to, created_at, updated_at
`

type CreateModelPriceParams struct {
	ModelID                int64
	Currency               string
	PricingUnit            string
	UncachedInputPrice     pgtype.Numeric
	CacheReadInputPrice    pgtype.Numeric
	CacheWrite5mInputPrice pgtype.Numeric
	CacheWrite1hInputPrice pgtype.Numeric
	OutputPrice            pgtype.Numeric
	ReasoningOutputPrice   pgtype.Numeric
	Status                 string
	EffectiveFrom          pgtype.Timestamptz
	EffectiveTo            pgtype.Timestamptz
}

// CreateModelPrice 创建一条模型基准售价（DEC-026）。客户最终售价 = 本基准价 × 线路倍率。
// 启用窗口重叠由 ex_model_prices_enabled_window 保证，违反报 23P01。
func (q *Queries) CreateModelPrice(ctx context.Context, arg CreateModelPriceParams) (ModelPrice, error) {
	row := q.db.QueryRow(ctx, createModelPrice,
		arg.ModelID,
		arg.Currency,
		arg.PricingUnit,
		arg.UncachedInputPrice,
		arg.CacheReadInputPrice,
		arg.CacheWrite5mInputPrice,
		arg.CacheWrite1hInputPrice,
		arg.OutputPrice,
		arg.ReasoningOutputPrice,
		arg.Status,
		arg.EffectiveFrom,
		arg.EffectiveTo,
	)
	var i ModelPrice
	err := row.Scan(
		&i.ID,
		&i.ModelID,
		&i.Currency,
		&i.PricingUnit,
		&i.UncachedInputPrice,
		&i.CacheReadInputPrice,
		&i.CacheWrite5mInputPrice,
		&i.CacheWrite1hInputPrice,
		&i.OutputPrice,
		&i.ReasoningOutputPrice,
		&i.Status,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findActiveModelPrice = `-- name: FindActiveModelPrice :one
SELECT id, model_id, currency, pricing_unit, uncached_input_price, cache_read_input_price, cache_write_5m_input_price, cache_write_1h_input_price, output_price, reasoning_output_price, status, effective_from, effective_to, created_at, updated_at
FROM model_prices
WHERE model_id = $1
    AND status = 'enabled'
    AND effective_from <= $2
    AND (
        effective_to IS NULL
        OR effective_to > $2
    )
ORDER BY effective_from DESC, id DESC
LIMIT 1
`

type FindActiveModelPriceParams struct {
	ModelID int64
	AtTime  pgtype.Timestamptz
}

// FindActiveModelPrice 查找指定 model 在指定时间生效的基准售价（settlement / authorization 计算客户售价用）。
func (q *Queries) FindActiveModelPrice(ctx context.Context, arg FindActiveModelPriceParams) (ModelPrice, error) {
	row := q.db.QueryRow(ctx, findActiveModelPrice, arg.ModelID, arg.AtTime)
	var i ModelPrice
	err := row.Scan(
		&i.ID,
		&i.ModelID,
		&i.Currency,
		&i.PricingUnit,
		&i.UncachedInputPrice,
		&i.CacheReadInputPrice,
		&i.CacheWrite5mInputPrice,
		&i.CacheWrite1hInputPrice,
		&i.OutputPrice,
		&i.ReasoningOutputPrice,
		&i.Status,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getModelPrice = `-- name: GetModelPrice :one
SELECT id, model_id, currency, pricing_unit, uncached_input_price, cache_read_input_price, cache_write_5m_input_price, cache_write_1h_input_price, output_price, reasoning_output_price, status, effective_from, effective_to, created_at, updated_at FROM model_prices WHERE id = $1 LIMIT 1
`

// GetModelPrice 按主键读取单条模型基准售价。
func (q *Queries) GetModelPrice(ctx context.Context, id int64) (ModelPrice, error) {
	row := q.db.QueryRow(ctx, getModelPrice, id)
	var i ModelPrice
	err := row.Scan(
		&i.ID,
		&i.ModelID,
		&i.Currency,
		&i.PricingUnit,
		&i.UncachedInputPrice,
		&i.CacheReadInputPrice,
		&i.CacheWrite5mInputPrice,
		&i.CacheWrite1hInputPrice,
		&i.OutputPrice,
		&i.ReasoningOutputPrice,
		&i.Status,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEnabledModelPriceWindows = `-- name: ListEnabledModelPriceWindows :many
SELECT id, effective_from, effective_to
FROM model_prices
WHERE model_id = $1
    AND status = 'enabled'
    AND id <> $2
`

type ListEnabledModelPriceWindowsParams struct {
	ModelID   int64
	ExcludeID int64
}

type ListEnabledModelPriceWindowsRow struct {
	ID            int64
	EffectiveFrom pgtype.Timestamptz
	EffectiveTo   pgtype.Timestamptz
}

// ListEnabledModelPriceWindows 取某 model 全部启用中的价格生效窗口，供「窗口不重叠」校验；exclude_id 用于更新时排除自身（创建时传 0）。
func (q *Queries) ListEnabledModelPriceWindows(ctx context.Context, arg ListEnabledModelPriceWindowsParams) ([]ListEnabledModelPriceWindowsRow, error) {
	rows, err := q.db.Query(ctx, listEnabledModelPriceWindows, arg.ModelID, arg.ExcludeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEnabledModelPriceWindowsRow
	for rows.Next() {
		var i ListEnabledModelPriceWindowsRow
		if err := rows.Scan(&i.ID, &i.EffectiveFrom, &i.EffectiveTo); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listModelPricesByModel = `-- name: ListModelPricesByModel :many
SELECT
    mp.id,
    mp.model_id,
    mp.currency,
    mp.pricing_unit,
    mp.uncached_input_price,
    mp.cache_read_input_price,
    mp.cache_write_5m_input_price,
    mp.cache_write_1h_input_price,
    mp.output_price,
    mp.reasoning_output_price,
    mp.status,
    mp.effective_from,
    mp.effective_to,
    mp.created_at,
    mp.updated_at,
    m.model_id AS model_external_id,
    m.display_name AS model_display_name
FROM model_prices mp
JOIN models m ON m.id = mp.model_id
WHERE mp.model_id = $1
ORDER BY mp.effective_from DESC, mp.id DESC
`

type ListModelPricesByModelRow struct {
	ID                     int64
	ModelID                int64
	Currency               string
	PricingUnit            string
	UncachedInputPrice     pgtype.Numeric
	CacheReadInputPrice    pgtype.Numeric
	CacheWrite5mInputPrice pgtype.Numeric
	CacheWrite1hInputPrice pgtype.Numeric
	OutputPrice            pgtype.Numeric
	ReasoningOutputPrice   pgtype.Numeric
	Status                 string
	EffectiveFrom          pgtype.Timestamptz
	EffectiveTo            pgtype.Timestamptz
	CreatedAt              pgtype.Timestamptz
	UpdatedAt              pgtype.Timestamptz
	ModelExternalID        string
	ModelDisplayName       string
}

// ListModelPricesByModel 列出某模型的全部基准售价（含历史与停用），连带模型对外 ID/展示名，供 admin 管理台展示。
func (q *Queries) ListModelPricesByModel(ctx context.Context, modelID int64) ([]ListModelPricesByModelRow, error) {
	rows, err := q.db.Query(ctx, listModelPricesByModel, modelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListModelPricesByModelRow
	for rows.Next() {
		var i ListModelPricesByModelRow
		if err := rows.Scan(
			&i.ID,
			&i.ModelID,
			&i.Currency,
			&i.PricingUnit,
			&i.UncachedInputPrice,
			&i.CacheReadInputPrice,
			&i.CacheWrite5mInputPrice,
			&i.CacheWrite1hInputPrice,
			&i.OutputPrice,
			&i.ReasoningOutputPrice,
			&i.Status,
			&i.EffectiveFrom,
			&i.EffectiveTo,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ModelExternalID,
			&i.ModelDisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateModelPriceWindow = `-- name: UpdateModelPriceWindow :one
UPDATE model_prices
SET effective_to = $1,
    status = $2,
    updated_at = now()
WHERE id = $3
RETURNING id, model_id, currency, pricing_unit, uncached_input_price, cache_read_input_price, cache_write_5m_input_price, cache_write_1h_input_price, output_price, reasoning_output_price, status, effective_from, effective_to, created_at, updated_at
`

type UpdateModelPriceWindowParams struct {
	EffectiveTo pgtype.Timestamptz
	Status      string
	ID          int64
}

// UpdateModelPriceWindow 调整生效结束时间与启停状态；金额不可改（改价请新建一条），账务可复算。
func (q *Queries) UpdateModelPriceWindow(ctx context.Context, arg UpdateModelPriceWindowParams) (ModelPrice, error) {
	row := q.db.QueryRow(ctx, updateModelPriceWindow, arg.EffectiveTo, arg.Status, arg.ID)
	var i ModelPrice
	err := row.Scan(
		&i.ID,
		&i.ModelID,
		&i.Currency,
		&i.PricingUnit,
		&i.UncachedInputPrice,
		&i.CacheReadInputPrice,
		&i.CacheWrite5mInputPrice,
		&i.CacheWrite1hInputPrice,
		&i.OutputPrice,
		&i.ReasoningOutputPrice,
		&i.Status,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
