// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: origin_routing_operations.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOriginRoutingOperation = `-- name: CreateOriginRoutingOperation :one

INSERT INTO origin_routing_operations (
    token, kind, provider_id, origin_id, transitions, payload_hash, state
) VALUES (
    $1, $2, $3, $4,
    $5, $6, 'preparing'
)
RETURNING id, token, kind, provider_id, origin_id, transitions, payload_hash, state, created_at, updated_at, completed_at
`

type CreateOriginRoutingOperationParams struct {
	Token       string
	Kind        string
	ProviderID  pgtype.Int8
	OriginID    pgtype.Int8
	Transitions []byte
	PayloadHash string
}

// origin_routing_operations 的可恢复围栏状态机查询（P4 §4.3）。
// 状态机：preparing -> prepared -> db_committed -> committed；仅 preparing|prepared -> aborted。
// 以 preparing 开一条 Origin/Provider 围栏操作（Redis Prepare 前）。
func (q *Queries) CreateOriginRoutingOperation(ctx context.Context, arg CreateOriginRoutingOperationParams) (OriginRoutingOperation, error) {
	row := q.db.QueryRow(ctx, createOriginRoutingOperation,
		arg.Token,
		arg.Kind,
		arg.ProviderID,
		arg.OriginID,
		arg.Transitions,
		arg.PayloadHash,
	)
	var i OriginRoutingOperation
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.Kind,
		&i.ProviderID,
		&i.OriginID,
		&i.Transitions,
		&i.PayloadHash,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const deleteTerminalOriginRoutingOperationsBefore = `-- name: DeleteTerminalOriginRoutingOperationsBefore :execrows
DELETE FROM origin_routing_operations
WHERE state = ANY (ARRAY['committed'::text, 'aborted'::text])
  AND completed_at IS NOT NULL
  AND completed_at < $1
`

func (q *Queries) DeleteTerminalOriginRoutingOperationsBefore(ctx context.Context, cutoff pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTerminalOriginRoutingOperationsBefore, cutoff)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getOriginRoutingOperationByToken = `-- name: GetOriginRoutingOperationByToken :one
SELECT id, token, kind, provider_id, origin_id, transitions, payload_hash, state, created_at, updated_at, completed_at
FROM origin_routing_operations
WHERE token = $1
`

func (q *Queries) GetOriginRoutingOperationByToken(ctx context.Context, token string) (OriginRoutingOperation, error) {
	row := q.db.QueryRow(ctx, getOriginRoutingOperationByToken, token)
	var i OriginRoutingOperation
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.Kind,
		&i.ProviderID,
		&i.OriginID,
		&i.Transitions,
		&i.PayloadHash,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const listNonterminalOriginRoutingOperations = `-- name: ListNonterminalOriginRoutingOperations :many
SELECT id, token, kind, provider_id, origin_id, transitions, payload_hash, state, created_at, updated_at, completed_at
FROM origin_routing_operations
WHERE state <> ALL (ARRAY['committed'::text, 'aborted'::text])
ORDER BY created_at, id
`

func (q *Queries) ListNonterminalOriginRoutingOperations(ctx context.Context) ([]OriginRoutingOperation, error) {
	rows, err := q.db.Query(ctx, listNonterminalOriginRoutingOperations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OriginRoutingOperation
	for rows.Next() {
		var i OriginRoutingOperation
		if err := rows.Scan(
			&i.ID,
			&i.Token,
			&i.Kind,
			&i.ProviderID,
			&i.OriginID,
			&i.Transitions,
			&i.PayloadHash,
			&i.State,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOriginRoutingOperationAborted = `-- name: MarkOriginRoutingOperationAborted :execrows
UPDATE origin_routing_operations
SET state = 'aborted', completed_at = now(), updated_at = now()
WHERE token = $1 AND payload_hash = $2
  AND state IN ('preparing', 'prepared')
`

type MarkOriginRoutingOperationAbortedParams struct {
	Token       string
	PayloadHash string
}

func (q *Queries) MarkOriginRoutingOperationAborted(ctx context.Context, arg MarkOriginRoutingOperationAbortedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markOriginRoutingOperationAborted, arg.Token, arg.PayloadHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markOriginRoutingOperationCommitted = `-- name: MarkOriginRoutingOperationCommitted :execrows
UPDATE origin_routing_operations
SET state = 'committed', completed_at = now(), updated_at = now()
WHERE token = $1 AND payload_hash = $2 AND state = 'db_committed'
`

type MarkOriginRoutingOperationCommittedParams struct {
	Token       string
	PayloadHash string
}

func (q *Queries) MarkOriginRoutingOperationCommitted(ctx context.Context, arg MarkOriginRoutingOperationCommittedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markOriginRoutingOperationCommitted, arg.Token, arg.PayloadHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markOriginRoutingOperationDBCommitted = `-- name: MarkOriginRoutingOperationDBCommitted :execrows
UPDATE origin_routing_operations
SET state = 'db_committed', updated_at = now()
WHERE token = $1 AND payload_hash = $2 AND state = 'prepared'
`

type MarkOriginRoutingOperationDBCommittedParams struct {
	Token       string
	PayloadHash string
}

func (q *Queries) MarkOriginRoutingOperationDBCommitted(ctx context.Context, arg MarkOriginRoutingOperationDBCommittedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markOriginRoutingOperationDBCommitted, arg.Token, arg.PayloadHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markOriginRoutingOperationPrepared = `-- name: MarkOriginRoutingOperationPrepared :execrows
UPDATE origin_routing_operations
SET state = 'prepared', updated_at = now()
WHERE token = $1 AND payload_hash = $2 AND state = 'preparing'
`

type MarkOriginRoutingOperationPreparedParams struct {
	Token       string
	PayloadHash string
}

func (q *Queries) MarkOriginRoutingOperationPrepared(ctx context.Context, arg MarkOriginRoutingOperationPreparedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markOriginRoutingOperationPrepared, arg.Token, arg.PayloadHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
