// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: price_snapshots.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPriceSnapshot = `-- name: CreatePriceSnapshot :one
INSERT INTO price_snapshots (
    request_record_id,
    price_id,
    currency,
    pricing_unit,
    uncached_input_price,
    cache_read_input_price,
    cache_write_5m_input_price,
    cache_write_1h_input_price,
    cache_write_30m_input_price,
    output_price,
    reasoning_output_price,
    formula_version,
    price_ratio
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13
)
RETURNING id, request_record_id, price_id, currency, pricing_unit, uncached_input_price, cache_read_input_price, cache_write_5m_input_price, cache_write_1h_input_price, output_price, reasoning_output_price, formula_version, created_at, price_ratio, cache_write_30m_input_price
`

type CreatePriceSnapshotParams struct {
	RequestRecordID         int64
	PriceID                 pgtype.Int8
	Currency                string
	PricingUnit             string
	UncachedInputPrice      pgtype.Numeric
	CacheReadInputPrice     pgtype.Numeric
	CacheWrite5mInputPrice  pgtype.Numeric
	CacheWrite1hInputPrice  pgtype.Numeric
	CacheWrite30mInputPrice pgtype.Numeric
	OutputPrice             pgtype.Numeric
	ReasoningOutputPrice    pgtype.Numeric
	FormulaVersion          string
	PriceRatio              pgtype.Numeric
}

// CreatePriceSnapshot 创建一次请求结算使用的客户售价快照。
func (q *Queries) CreatePriceSnapshot(ctx context.Context, arg CreatePriceSnapshotParams) (PriceSnapshot, error) {
	row := q.db.QueryRow(ctx, createPriceSnapshot,
		arg.RequestRecordID,
		arg.PriceID,
		arg.Currency,
		arg.PricingUnit,
		arg.UncachedInputPrice,
		arg.CacheReadInputPrice,
		arg.CacheWrite5mInputPrice,
		arg.CacheWrite1hInputPrice,
		arg.CacheWrite30mInputPrice,
		arg.OutputPrice,
		arg.ReasoningOutputPrice,
		arg.FormulaVersion,
		arg.PriceRatio,
	)
	var i PriceSnapshot
	err := row.Scan(
		&i.ID,
		&i.RequestRecordID,
		&i.PriceID,
		&i.Currency,
		&i.PricingUnit,
		&i.UncachedInputPrice,
		&i.CacheReadInputPrice,
		&i.CacheWrite5mInputPrice,
		&i.CacheWrite1hInputPrice,
		&i.OutputPrice,
		&i.ReasoningOutputPrice,
		&i.FormulaVersion,
		&i.CreatedAt,
		&i.PriceRatio,
		&i.CacheWrite30mInputPrice,
	)
	return i, err
}

const getPriceSnapshotByRequest = `-- name: GetPriceSnapshotByRequest :one
SELECT id, request_record_id, price_id, currency, pricing_unit, uncached_input_price, cache_read_input_price, cache_write_5m_input_price, cache_write_1h_input_price, output_price, reasoning_output_price, formula_version, created_at, price_ratio, cache_write_30m_input_price
FROM price_snapshots
WHERE request_record_id = $1
`

// GetPriceSnapshotByRequest 按请求 ID 读取客户售价快照。
func (q *Queries) GetPriceSnapshotByRequest(ctx context.Context, requestRecordID int64) (PriceSnapshot, error) {
	row := q.db.QueryRow(ctx, getPriceSnapshotByRequest, requestRecordID)
	var i PriceSnapshot
	err := row.Scan(
		&i.ID,
		&i.RequestRecordID,
		&i.PriceID,
		&i.Currency,
		&i.PricingUnit,
		&i.UncachedInputPrice,
		&i.CacheReadInputPrice,
		&i.CacheWrite5mInputPrice,
		&i.CacheWrite1hInputPrice,
		&i.OutputPrice,
		&i.ReasoningOutputPrice,
		&i.FormulaVersion,
		&i.CreatedAt,
		&i.PriceRatio,
		&i.CacheWrite30mInputPrice,
	)
	return i, err
}
