// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: providers.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const archiveProviderCascade = `-- name: ArchiveProviderCascade :execrows
WITH archived_channels AS (
    UPDATE channels
    SET status = 'archived', archived_at = now(), name = name || '__archived_' || id::text
    WHERE provider_id = $1 AND status <> 'archived'
    RETURNING id
),
cleared_pools AS (
    DELETE FROM route_channels WHERE channel_id IN (SELECT id FROM archived_channels)
)
UPDATE providers
SET status = 'archived', archived_at = now()
WHERE providers.id = $1 AND providers.status <> 'archived'
`

// ArchiveProviderCascade 归档 provider：单事务内把名下未归档渠道一并归档（释放渠道名：追加
// __archived_<id> 后缀）、从所有线路候选池移除这些渠道（route_channels 纯配置、无账务外键，可安全删），
// 再把 provider 置 archived。slug 与 provider.name 不变（服务商标识稳定，归档大概率不再复用同 slug）。
// 返回 providers 受影响行数（0 = provider 不存在或已归档）。恢复不向下级联，需逐个恢复渠道。
func (q *Queries) ArchiveProviderCascade(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, archiveProviderCascade, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countProviders = `-- name: CountProviders :one
SELECT COUNT(*) AS total
FROM providers
WHERE ($1::text IS NULL OR status = $1::text)
  AND (
    $2::text IS NULL
    OR slug ILIKE '%' || $2::text || '%'
    OR name ILIKE '%' || $2::text || '%'
  )
`

type CountProvidersParams struct {
	Status pgtype.Text
	Q      pgtype.Text
}

// CountProviders 返回与 ListProvidersPage 相同过滤条件下的总条数。
func (q *Queries) CountProviders(ctx context.Context, arg CountProvidersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countProviders, arg.Status, arg.Q)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const createProvider = `-- name: CreateProvider :one
INSERT INTO providers (slug, name, status)
VALUES ($1, $2, $3)
RETURNING id, slug, name, status, created_at, updated_at, archived_at
`

type CreateProviderParams struct {
	Slug   string
	Name   string
	Status string
}

// CreateProvider 创建 provider；slug 全局唯一由 DB 唯一约束保证。
func (q *Queries) CreateProvider(ctx context.Context, arg CreateProviderParams) (Provider, error) {
	row := q.db.QueryRow(ctx, createProvider, arg.Slug, arg.Name, arg.Status)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const deleteProvider = `-- name: DeleteProvider :execrows
DELETE FROM providers WHERE id = $1
`

// DeleteProvider 物理删除 provider，用于清理录错且从未使用的脏数据。
// provider 无自身配置子表，故不级联：名下仍有 channel，或被 request/cost 历史（NO ACTION 外键）
// 引用时，DB 拒绝删除（23503），上层降级为 conflict，提示先删渠道或改用停用。
func (q *Queries) DeleteProvider(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProvider, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getProvider = `-- name: GetProvider :one
SELECT id, slug, name, status, created_at, updated_at, archived_at
FROM providers
WHERE id = $1
LIMIT 1
`

// GetProvider 按 id 读取单个 provider。
func (q *Queries) GetProvider(ctx context.Context, id int64) (Provider, error) {
	row := q.db.QueryRow(ctx, getProvider, id)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const listProviders = `-- name: ListProviders :many
SELECT id, slug, name, status, created_at, updated_at, archived_at
FROM providers
ORDER BY id
`

// ListProviders 列出全部 provider，按 id 升序，供 admin 管理台展示。
func (q *Queries) ListProviders(ctx context.Context) ([]Provider, error) {
	rows, err := q.db.Query(ctx, listProviders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Provider
	for rows.Next() {
		var i Provider
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProvidersPage = `-- name: ListProvidersPage :many
SELECT id, slug, name, status, created_at, updated_at, archived_at
FROM providers
WHERE ($1::text IS NULL OR status = $1::text)
  AND (
    $2::text IS NULL
    OR slug ILIKE '%' || $2::text || '%'
    OR name ILIKE '%' || $2::text || '%'
  )
ORDER BY id
LIMIT $4 OFFSET $3
`

type ListProvidersPageParams struct {
	Status     pgtype.Text
	Q          pgtype.Text
	PageOffset int32
	PageLimit  int32
}

// ListProvidersPage 按状态/关键字过滤后分页列出 provider；status、q 为 NULL 时不过滤。
func (q *Queries) ListProvidersPage(ctx context.Context, arg ListProvidersPageParams) ([]Provider, error) {
	rows, err := q.db.Query(ctx, listProvidersPage,
		arg.Status,
		arg.Q,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Provider
	for rows.Next() {
		var i Provider
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreProvider = `-- name: RestoreProvider :execrows
UPDATE providers
SET status = 'disabled', archived_at = NULL
WHERE id = $1 AND status = 'archived'
`

// RestoreProvider 取消归档 provider：archived → disabled（archived_at 清空）。不向下级联恢复渠道。
func (q *Queries) RestoreProvider(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, restoreProvider, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateProvider = `-- name: UpdateProvider :one
UPDATE providers
SET name = $1, status = $2, updated_at = now()
WHERE id = $3
RETURNING id, slug, name, status, created_at, updated_at, archived_at
`

type UpdateProviderParams struct {
	Name   string
	Status string
	ID     int64
}

// UpdateProvider 更新 provider 的展示名与启停状态；slug 作为稳定业务标识不可变。
func (q *Queries) UpdateProvider(ctx context.Context, arg UpdateProviderParams) (Provider, error) {
	row := q.db.QueryRow(ctx, updateProvider, arg.Name, arg.Status, arg.ID)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}
