// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: provider_routing_operations.sql

package sqlc

import (
	"context"
)

const createProviderRoutingOperation = `-- name: CreateProviderRoutingOperation :one

INSERT INTO provider_routing_operations (
    token, kind, provider_id, transitions, payload_hash, state
) VALUES (
    $1, $2, $3,
    $4, $5, 'preparing'
)
RETURNING id, token, kind, provider_id, transitions, payload_hash, state, created_at, updated_at, completed_at
`

type CreateProviderRoutingOperationParams struct {
	Token       string
	Kind        string
	ProviderID  int64
	Transitions []byte
	PayloadHash string
}

// provider_routing_operations 的可恢复围栏状态机查询。
// 状态机：preparing -> prepared -> db_committed -> committed；仅 preparing|prepared -> aborted。
// 以 preparing 开一条 Provider 围栏操作（Redis Prepare 前）。
func (q *Queries) CreateProviderRoutingOperation(ctx context.Context, arg CreateProviderRoutingOperationParams) (ProviderRoutingOperation, error) {
	row := q.db.QueryRow(ctx, createProviderRoutingOperation,
		arg.Token,
		arg.Kind,
		arg.ProviderID,
		arg.Transitions,
		arg.PayloadHash,
	)
	var i ProviderRoutingOperation
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.Kind,
		&i.ProviderID,
		&i.Transitions,
		&i.PayloadHash,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getProviderRoutingOperationByToken = `-- name: GetProviderRoutingOperationByToken :one
SELECT id, token, kind, provider_id, transitions, payload_hash, state, created_at, updated_at, completed_at
FROM provider_routing_operations
WHERE token = $1
`

func (q *Queries) GetProviderRoutingOperationByToken(ctx context.Context, token string) (ProviderRoutingOperation, error) {
	row := q.db.QueryRow(ctx, getProviderRoutingOperationByToken, token)
	var i ProviderRoutingOperation
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.Kind,
		&i.ProviderID,
		&i.Transitions,
		&i.PayloadHash,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const listNonterminalProviderRoutingOperations = `-- name: ListNonterminalProviderRoutingOperations :many
SELECT id, token, kind, provider_id, transitions, payload_hash, state, created_at, updated_at, completed_at
FROM provider_routing_operations
WHERE state <> ALL (ARRAY['committed'::text, 'aborted'::text])
ORDER BY created_at, id
`

func (q *Queries) ListNonterminalProviderRoutingOperations(ctx context.Context) ([]ProviderRoutingOperation, error) {
	rows, err := q.db.Query(ctx, listNonterminalProviderRoutingOperations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProviderRoutingOperation
	for rows.Next() {
		var i ProviderRoutingOperation
		if err := rows.Scan(
			&i.ID,
			&i.Token,
			&i.Kind,
			&i.ProviderID,
			&i.Transitions,
			&i.PayloadHash,
			&i.State,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markProviderRoutingOperationAborted = `-- name: MarkProviderRoutingOperationAborted :execrows
UPDATE provider_routing_operations
SET state = 'aborted', completed_at = now(), updated_at = now()
WHERE token = $1 AND payload_hash = $2
  AND state IN ('preparing', 'prepared')
`

type MarkProviderRoutingOperationAbortedParams struct {
	Token       string
	PayloadHash string
}

func (q *Queries) MarkProviderRoutingOperationAborted(ctx context.Context, arg MarkProviderRoutingOperationAbortedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markProviderRoutingOperationAborted, arg.Token, arg.PayloadHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markProviderRoutingOperationCommitted = `-- name: MarkProviderRoutingOperationCommitted :execrows
UPDATE provider_routing_operations
SET state = 'committed', completed_at = now(), updated_at = now()
WHERE token = $1 AND payload_hash = $2 AND state = 'db_committed'
`

type MarkProviderRoutingOperationCommittedParams struct {
	Token       string
	PayloadHash string
}

func (q *Queries) MarkProviderRoutingOperationCommitted(ctx context.Context, arg MarkProviderRoutingOperationCommittedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markProviderRoutingOperationCommitted, arg.Token, arg.PayloadHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markProviderRoutingOperationDBCommitted = `-- name: MarkProviderRoutingOperationDBCommitted :execrows
UPDATE provider_routing_operations
SET state = 'db_committed', updated_at = now()
WHERE token = $1 AND payload_hash = $2 AND state = 'prepared'
`

type MarkProviderRoutingOperationDBCommittedParams struct {
	Token       string
	PayloadHash string
}

func (q *Queries) MarkProviderRoutingOperationDBCommitted(ctx context.Context, arg MarkProviderRoutingOperationDBCommittedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markProviderRoutingOperationDBCommitted, arg.Token, arg.PayloadHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markProviderRoutingOperationPrepared = `-- name: MarkProviderRoutingOperationPrepared :execrows
UPDATE provider_routing_operations
SET state = 'prepared', updated_at = now()
WHERE token = $1 AND payload_hash = $2 AND state = 'preparing'
`

type MarkProviderRoutingOperationPreparedParams struct {
	Token       string
	PayloadHash string
}

func (q *Queries) MarkProviderRoutingOperationPrepared(ctx context.Context, arg MarkProviderRoutingOperationPreparedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markProviderRoutingOperationPrepared, arg.Token, arg.PayloadHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
