// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: providers.sql

package sqlc

import (
	"context"
)

const createProvider = `-- name: CreateProvider :one
INSERT INTO providers (slug, name, status)
VALUES ($1, $2, $3)
RETURNING id, slug, name, status, created_at, updated_at
`

type CreateProviderParams struct {
	Slug   string
	Name   string
	Status string
}

// CreateProvider 创建 provider；slug 全局唯一由 DB 唯一约束保证。
func (q *Queries) CreateProvider(ctx context.Context, arg CreateProviderParams) (Provider, error) {
	row := q.db.QueryRow(ctx, createProvider, arg.Slug, arg.Name, arg.Status)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProvider = `-- name: GetProvider :one
SELECT id, slug, name, status, created_at, updated_at
FROM providers
WHERE id = $1
LIMIT 1
`

// GetProvider 按 id 读取单个 provider。
func (q *Queries) GetProvider(ctx context.Context, id int64) (Provider, error) {
	row := q.db.QueryRow(ctx, getProvider, id)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProviders = `-- name: ListProviders :many
SELECT id, slug, name, status, created_at, updated_at
FROM providers
ORDER BY id
`

// ListProviders 列出全部 provider，按 id 升序，供 admin 管理台展示。
func (q *Queries) ListProviders(ctx context.Context) ([]Provider, error) {
	rows, err := q.db.Query(ctx, listProviders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Provider
	for rows.Next() {
		var i Provider
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProvider = `-- name: UpdateProvider :one
UPDATE providers
SET name = $1, status = $2, updated_at = now()
WHERE id = $3
RETURNING id, slug, name, status, created_at, updated_at
`

type UpdateProviderParams struct {
	Name   string
	Status string
	ID     int64
}

// UpdateProvider 更新 provider 的展示名与启停状态；slug 作为稳定业务标识不可变。
func (q *Queries) UpdateProvider(ctx context.Context, arg UpdateProviderParams) (Provider, error) {
	row := q.db.QueryRow(ctx, updateProvider, arg.Name, arg.Status, arg.ID)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
