// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: provider_ledger.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addProviderBalance = `-- name: AddProviderBalance :one
UPDATE provider_balances
SET balance = balance + $1, updated_at = now()
WHERE provider_id = $2
  AND currency = $3
RETURNING id, provider_id, currency, balance, created_at, updated_at
`

type AddProviderBalanceParams struct {
	Amount     pgtype.Numeric
	ProviderID int64
	Currency   string
}

func (q *Queries) AddProviderBalance(ctx context.Context, arg AddProviderBalanceParams) (ProviderBalance, error) {
	row := q.db.QueryRow(ctx, addProviderBalance, arg.Amount, arg.ProviderID, arg.Currency)
	var i ProviderBalance
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.Currency,
		&i.Balance,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countLowBalanceProviders = `-- name: CountLowBalanceProviders :one
SELECT COUNT(*) AS total
FROM providers p
JOIN provider_balances pb ON pb.provider_id = p.id AND pb.currency = 'USD'
WHERE p.status <> 'archived'
  AND pb.balance < 10
`

func (q *Queries) CountLowBalanceProviders(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countLowBalanceProviders)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countProviderLedgerEntries = `-- name: CountProviderLedgerEntries :one
SELECT COUNT(*) AS total
FROM provider_ledger_entries e
WHERE e.provider_id = $1
  AND ($2::text IS NULL OR e.entry_type = $2::text)
  AND ($3::text IS NULL OR e.request_id = $3::text)
  AND ($4::timestamptz IS NULL OR e.created_at >= $4::timestamptz)
  AND ($5::timestamptz IS NULL OR e.created_at < $5::timestamptz)
`

type CountProviderLedgerEntriesParams struct {
	ProviderID int64
	EntryType  pgtype.Text
	RequestID  pgtype.Text
	FromTime   pgtype.Timestamptz
	ToTime     pgtype.Timestamptz
}

func (q *Queries) CountProviderLedgerEntries(ctx context.Context, arg CountProviderLedgerEntriesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countProviderLedgerEntries,
		arg.ProviderID,
		arg.EntryType,
		arg.RequestID,
		arg.FromTime,
		arg.ToTime,
	)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const createProviderLedgerEntry = `-- name: CreateProviderLedgerEntry :one
INSERT INTO provider_ledger_entries (
    provider_id,
    request_record_id,
    request_attempt_id,
    cost_snapshot_id,
    channel_id,
    request_id,
    channel_name,
    upstream_model,
    provider_probe_record_id,
    usage_source,
    entry_type,
    amount,
    currency,
    balance_before,
    balance_after,
    idempotency_key,
    reason
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    $15,
    $16,
    $17
)
RETURNING id, provider_id, request_record_id, request_attempt_id, provider_probe_record_id, cost_snapshot_id, channel_id, request_id, channel_name, upstream_model, entry_type, amount, currency, balance_before, balance_after, idempotency_key, reason, created_at, usage_source
`

type CreateProviderLedgerEntryParams struct {
	ProviderID            int64
	RequestRecordID       pgtype.Int8
	RequestAttemptID      pgtype.Int8
	CostSnapshotID        pgtype.Int8
	ChannelID             pgtype.Int8
	RequestID             pgtype.Text
	ChannelName           pgtype.Text
	UpstreamModel         pgtype.Text
	ProviderProbeRecordID pgtype.Int8
	UsageSource           pgtype.Text
	EntryType             string
	Amount                pgtype.Numeric
	Currency              string
	BalanceBefore         pgtype.Numeric
	BalanceAfter          pgtype.Numeric
	IdempotencyKey        string
	Reason                string
}

func (q *Queries) CreateProviderLedgerEntry(ctx context.Context, arg CreateProviderLedgerEntryParams) (ProviderLedgerEntry, error) {
	row := q.db.QueryRow(ctx, createProviderLedgerEntry,
		arg.ProviderID,
		arg.RequestRecordID,
		arg.RequestAttemptID,
		arg.CostSnapshotID,
		arg.ChannelID,
		arg.RequestID,
		arg.ChannelName,
		arg.UpstreamModel,
		arg.ProviderProbeRecordID,
		arg.UsageSource,
		arg.EntryType,
		arg.Amount,
		arg.Currency,
		arg.BalanceBefore,
		arg.BalanceAfter,
		arg.IdempotencyKey,
		arg.Reason,
	)
	var i ProviderLedgerEntry
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.RequestRecordID,
		&i.RequestAttemptID,
		&i.ProviderProbeRecordID,
		&i.CostSnapshotID,
		&i.ChannelID,
		&i.RequestID,
		&i.ChannelName,
		&i.UpstreamModel,
		&i.EntryType,
		&i.Amount,
		&i.Currency,
		&i.BalanceBefore,
		&i.BalanceAfter,
		&i.IdempotencyKey,
		&i.Reason,
		&i.CreatedAt,
		&i.UsageSource,
	)
	return i, err
}

const createProviderProbeRecord = `-- name: CreateProviderProbeRecord :one
INSERT INTO provider_probe_records (
    provider_id, channel_id, model_id, protocol, source, upstream_model,
    success, http_status, error_code, message, latency_ms, usage_source,
    usage_facts, usage_reliable, cost_amount, currency, formula_version, idempotency_key
)
VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9, $10,
    $11, $12, $13::jsonb, $14,
    $15, $16, $17, $18
)
RETURNING id, provider_id, channel_id, model_id, protocol, source, upstream_model, success, http_status, error_code, message, latency_ms, usage_source, usage_facts, usage_reliable, cost_amount, currency, formula_version, idempotency_key, created_at
`

type CreateProviderProbeRecordParams struct {
	ProviderID     int64
	ChannelID      int64
	ModelID        pgtype.Int8
	Protocol       string
	Source         string
	UpstreamModel  string
	Success        bool
	HttpStatus     int32
	ErrorCode      pgtype.Text
	Message        pgtype.Text
	LatencyMs      pgtype.Int8
	UsageSource    pgtype.Text
	UsageFacts     []byte
	UsageReliable  bool
	CostAmount     pgtype.Numeric
	Currency       pgtype.Text
	FormulaVersion pgtype.Text
	IdempotencyKey string
}

func (q *Queries) CreateProviderProbeRecord(ctx context.Context, arg CreateProviderProbeRecordParams) (ProviderProbeRecord, error) {
	row := q.db.QueryRow(ctx, createProviderProbeRecord,
		arg.ProviderID,
		arg.ChannelID,
		arg.ModelID,
		arg.Protocol,
		arg.Source,
		arg.UpstreamModel,
		arg.Success,
		arg.HttpStatus,
		arg.ErrorCode,
		arg.Message,
		arg.LatencyMs,
		arg.UsageSource,
		arg.UsageFacts,
		arg.UsageReliable,
		arg.CostAmount,
		arg.Currency,
		arg.FormulaVersion,
		arg.IdempotencyKey,
	)
	var i ProviderProbeRecord
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.ChannelID,
		&i.ModelID,
		&i.Protocol,
		&i.Source,
		&i.UpstreamModel,
		&i.Success,
		&i.HttpStatus,
		&i.ErrorCode,
		&i.Message,
		&i.LatencyMs,
		&i.UsageSource,
		&i.UsageFacts,
		&i.UsageReliable,
		&i.CostAmount,
		&i.Currency,
		&i.FormulaVersion,
		&i.IdempotencyKey,
		&i.CreatedAt,
	)
	return i, err
}

const ensureProviderBalance = `-- name: EnsureProviderBalance :exec
INSERT INTO provider_balances (provider_id, currency)
VALUES ($1, $2)
ON CONFLICT (provider_id, currency) DO NOTHING
`

type EnsureProviderBalanceParams struct {
	ProviderID int64
	Currency   string
}

func (q *Queries) EnsureProviderBalance(ctx context.Context, arg EnsureProviderBalanceParams) error {
	_, err := q.db.Exec(ctx, ensureProviderBalance, arg.ProviderID, arg.Currency)
	return err
}

const getProviderBalance = `-- name: GetProviderBalance :one
SELECT id, provider_id, currency, balance, created_at, updated_at
FROM provider_balances
WHERE provider_id = $1
  AND currency = $2
`

type GetProviderBalanceParams struct {
	ProviderID int64
	Currency   string
}

func (q *Queries) GetProviderBalance(ctx context.Context, arg GetProviderBalanceParams) (ProviderBalance, error) {
	row := q.db.QueryRow(ctx, getProviderBalance, arg.ProviderID, arg.Currency)
	var i ProviderBalance
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.Currency,
		&i.Balance,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProviderBalanceForUpdate = `-- name: GetProviderBalanceForUpdate :one
SELECT id, provider_id, currency, balance, created_at, updated_at
FROM provider_balances
WHERE provider_id = $1
  AND currency = $2
FOR UPDATE
`

type GetProviderBalanceForUpdateParams struct {
	ProviderID int64
	Currency   string
}

func (q *Queries) GetProviderBalanceForUpdate(ctx context.Context, arg GetProviderBalanceForUpdateParams) (ProviderBalance, error) {
	row := q.db.QueryRow(ctx, getProviderBalanceForUpdate, arg.ProviderID, arg.Currency)
	var i ProviderBalance
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.Currency,
		&i.Balance,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProviderLedgerEntryByCostSnapshotID = `-- name: GetProviderLedgerEntryByCostSnapshotID :one
SELECT id, provider_id, request_record_id, request_attempt_id, provider_probe_record_id, cost_snapshot_id, channel_id, request_id, channel_name, upstream_model, entry_type, amount, currency, balance_before, balance_after, idempotency_key, reason, created_at, usage_source
FROM provider_ledger_entries
WHERE cost_snapshot_id = $1
`

func (q *Queries) GetProviderLedgerEntryByCostSnapshotID(ctx context.Context, costSnapshotID pgtype.Int8) (ProviderLedgerEntry, error) {
	row := q.db.QueryRow(ctx, getProviderLedgerEntryByCostSnapshotID, costSnapshotID)
	var i ProviderLedgerEntry
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.RequestRecordID,
		&i.RequestAttemptID,
		&i.ProviderProbeRecordID,
		&i.CostSnapshotID,
		&i.ChannelID,
		&i.RequestID,
		&i.ChannelName,
		&i.UpstreamModel,
		&i.EntryType,
		&i.Amount,
		&i.Currency,
		&i.BalanceBefore,
		&i.BalanceAfter,
		&i.IdempotencyKey,
		&i.Reason,
		&i.CreatedAt,
		&i.UsageSource,
	)
	return i, err
}

const getProviderLedgerEntryByIdempotencyKey = `-- name: GetProviderLedgerEntryByIdempotencyKey :one
SELECT id, provider_id, request_record_id, request_attempt_id, provider_probe_record_id, cost_snapshot_id, channel_id, request_id, channel_name, upstream_model, entry_type, amount, currency, balance_before, balance_after, idempotency_key, reason, created_at, usage_source
FROM provider_ledger_entries
WHERE idempotency_key = $1
`

func (q *Queries) GetProviderLedgerEntryByIdempotencyKey(ctx context.Context, idempotencyKey string) (ProviderLedgerEntry, error) {
	row := q.db.QueryRow(ctx, getProviderLedgerEntryByIdempotencyKey, idempotencyKey)
	var i ProviderLedgerEntry
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.RequestRecordID,
		&i.RequestAttemptID,
		&i.ProviderProbeRecordID,
		&i.CostSnapshotID,
		&i.ChannelID,
		&i.RequestID,
		&i.ChannelName,
		&i.UpstreamModel,
		&i.EntryType,
		&i.Amount,
		&i.Currency,
		&i.BalanceBefore,
		&i.BalanceAfter,
		&i.IdempotencyKey,
		&i.Reason,
		&i.CreatedAt,
		&i.UsageSource,
	)
	return i, err
}

const getProviderLedgerEntryByProbeRecordID = `-- name: GetProviderLedgerEntryByProbeRecordID :one
SELECT id, provider_id, request_record_id, request_attempt_id, provider_probe_record_id, cost_snapshot_id, channel_id, request_id, channel_name, upstream_model, entry_type, amount, currency, balance_before, balance_after, idempotency_key, reason, created_at, usage_source
FROM provider_ledger_entries
WHERE provider_probe_record_id = $1
`

func (q *Queries) GetProviderLedgerEntryByProbeRecordID(ctx context.Context, providerProbeRecordID pgtype.Int8) (ProviderLedgerEntry, error) {
	row := q.db.QueryRow(ctx, getProviderLedgerEntryByProbeRecordID, providerProbeRecordID)
	var i ProviderLedgerEntry
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.RequestRecordID,
		&i.RequestAttemptID,
		&i.ProviderProbeRecordID,
		&i.CostSnapshotID,
		&i.ChannelID,
		&i.RequestID,
		&i.ChannelName,
		&i.UpstreamModel,
		&i.EntryType,
		&i.Amount,
		&i.Currency,
		&i.BalanceBefore,
		&i.BalanceAfter,
		&i.IdempotencyKey,
		&i.Reason,
		&i.CreatedAt,
		&i.UsageSource,
	)
	return i, err
}

const getProviderProbeRecordByIdempotencyKey = `-- name: GetProviderProbeRecordByIdempotencyKey :one
SELECT id, provider_id, channel_id, model_id, protocol, source, upstream_model, success, http_status, error_code, message, latency_ms, usage_source, usage_facts, usage_reliable, cost_amount, currency, formula_version, idempotency_key, created_at FROM provider_probe_records
WHERE idempotency_key = $1
`

func (q *Queries) GetProviderProbeRecordByIdempotencyKey(ctx context.Context, idempotencyKey string) (ProviderProbeRecord, error) {
	row := q.db.QueryRow(ctx, getProviderProbeRecordByIdempotencyKey, idempotencyKey)
	var i ProviderProbeRecord
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.ChannelID,
		&i.ModelID,
		&i.Protocol,
		&i.Source,
		&i.UpstreamModel,
		&i.Success,
		&i.HttpStatus,
		&i.ErrorCode,
		&i.Message,
		&i.LatencyMs,
		&i.UsageSource,
		&i.UsageFacts,
		&i.UsageReliable,
		&i.CostAmount,
		&i.Currency,
		&i.FormulaVersion,
		&i.IdempotencyKey,
		&i.CreatedAt,
	)
	return i, err
}

const listProviderLedgerEntriesPage = `-- name: ListProviderLedgerEntriesPage :many
SELECT
    e.id,
    e.provider_id,
    e.request_record_id,
    e.request_attempt_id,
    e.cost_snapshot_id,
    e.channel_id,
    e.request_id,
    e.channel_name,
    e.upstream_model,
	e.provider_probe_record_id,
	e.usage_source,
    probe.channel_id AS probe_channel_id,
    probe_channel.name AS probe_channel_name,
    probe.upstream_model AS probe_upstream_model,
    e.entry_type,
    e.amount,
    e.currency,
    e.balance_before,
    e.balance_after,
    e.idempotency_key,
    e.reason,
    e.created_at
FROM provider_ledger_entries e
LEFT JOIN provider_probe_records probe ON probe.id = e.provider_probe_record_id
LEFT JOIN channels probe_channel ON probe_channel.id = probe.channel_id
WHERE e.provider_id = $1
  AND ($2::text IS NULL OR e.entry_type = $2::text)
  AND ($3::text IS NULL OR e.request_id = $3::text)
  AND ($4::timestamptz IS NULL OR e.created_at >= $4::timestamptz)
  AND ($5::timestamptz IS NULL OR e.created_at < $5::timestamptz)
ORDER BY e.created_at DESC, e.id DESC
LIMIT $7 OFFSET $6
`

type ListProviderLedgerEntriesPageParams struct {
	ProviderID int64
	EntryType  pgtype.Text
	RequestID  pgtype.Text
	FromTime   pgtype.Timestamptz
	ToTime     pgtype.Timestamptz
	PageOffset int32
	PageLimit  int32
}

type ListProviderLedgerEntriesPageRow struct {
	ID                    int64
	ProviderID            int64
	RequestRecordID       pgtype.Int8
	RequestAttemptID      pgtype.Int8
	CostSnapshotID        pgtype.Int8
	ChannelID             pgtype.Int8
	RequestID             pgtype.Text
	ChannelName           pgtype.Text
	UpstreamModel         pgtype.Text
	ProviderProbeRecordID pgtype.Int8
	UsageSource           pgtype.Text
	ProbeChannelID        pgtype.Int8
	ProbeChannelName      pgtype.Text
	ProbeUpstreamModel    pgtype.Text
	EntryType             string
	Amount                pgtype.Numeric
	Currency              string
	BalanceBefore         pgtype.Numeric
	BalanceAfter          pgtype.Numeric
	IdempotencyKey        string
	Reason                string
	CreatedAt             pgtype.Timestamptz
}

func (q *Queries) ListProviderLedgerEntriesPage(ctx context.Context, arg ListProviderLedgerEntriesPageParams) ([]ListProviderLedgerEntriesPageRow, error) {
	rows, err := q.db.Query(ctx, listProviderLedgerEntriesPage,
		arg.ProviderID,
		arg.EntryType,
		arg.RequestID,
		arg.FromTime,
		arg.ToTime,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProviderLedgerEntriesPageRow
	for rows.Next() {
		var i ListProviderLedgerEntriesPageRow
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.RequestRecordID,
			&i.RequestAttemptID,
			&i.CostSnapshotID,
			&i.ChannelID,
			&i.RequestID,
			&i.ChannelName,
			&i.UpstreamModel,
			&i.ProviderProbeRecordID,
			&i.UsageSource,
			&i.ProbeChannelID,
			&i.ProbeChannelName,
			&i.ProbeUpstreamModel,
			&i.EntryType,
			&i.Amount,
			&i.Currency,
			&i.BalanceBefore,
			&i.BalanceAfter,
			&i.IdempotencyKey,
			&i.Reason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockProviderLedgerIdempotencyKey = `-- name: LockProviderLedgerIdempotencyKey :exec
SELECT pg_advisory_xact_lock(
    hashtext('provider_ledger_entries'),
    hashtext($1::text)
)
`

func (q *Queries) LockProviderLedgerIdempotencyKey(ctx context.Context, idempotencyKey string) error {
	_, err := q.db.Exec(ctx, lockProviderLedgerIdempotencyKey, idempotencyKey)
	return err
}

const subtractProviderBalance = `-- name: SubtractProviderBalance :one
UPDATE provider_balances
SET balance = balance - $1, updated_at = now()
WHERE provider_id = $2
  AND currency = $3
RETURNING id, provider_id, currency, balance, created_at, updated_at
`

type SubtractProviderBalanceParams struct {
	Amount     pgtype.Numeric
	ProviderID int64
	Currency   string
}

func (q *Queries) SubtractProviderBalance(ctx context.Context, arg SubtractProviderBalanceParams) (ProviderBalance, error) {
	row := q.db.QueryRow(ctx, subtractProviderBalance, arg.Amount, arg.ProviderID, arg.Currency)
	var i ProviderBalance
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.Currency,
		&i.Balance,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
