// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: request_attempts.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRequestAttempt = `-- name: CreateRequestAttempt :one
INSERT INTO request_attempts (
    request_record_id,
    attempt_index,
    provider_id,
    channel_id,
    adapter_key,
    upstream_model,
    upstream_protocol,
    upstream_response_id,
    upstream_response_model,
    upstream_finish_reason,
    finish_class,
    status,
    upstream_status_code,
    upstream_request_id,
    error_code,
    error_message,
    internal_error_detail,
    response_started_at,
    final_usage_received,
    usage_mapping_version,
    required_capabilities,
    used_capabilities,
    started_at,
    completed_at
)
VALUES (
           $1,
           $2,
           $3,
           $4,
           $5,
           $6,
           $7,
           $8,
           $9,
           $10,
           $11,
           $12,
           $13,
           $14,
           $15,
           $16,
           $17,
           $18,
           $19,
           $20,
           COALESCE($21::text[], '{}'),
           COALESCE($22::text[], '{}'),
           $23,
           $24
       )
RETURNING
    id,
    request_record_id,
    attempt_index,
    provider_id,
    channel_id,
    adapter_key,
    upstream_model,
    upstream_protocol,
    upstream_response_id,
    upstream_response_model,
    upstream_finish_reason,
    finish_class,
    status,
    upstream_status_code,
    upstream_request_id,
    error_code,
    error_message,
    internal_error_detail,
    response_started_at,
    final_usage_received,
    usage_mapping_version,
    required_capabilities,
    used_capabilities,
    started_at,
    completed_at,
    created_at
`

type CreateRequestAttemptParams struct {
	RequestRecordID       int64
	AttemptIndex          int32
	ProviderID            int64
	ChannelID             int64
	AdapterKey            string
	UpstreamModel         string
	UpstreamProtocol      string
	UpstreamResponseID    pgtype.Text
	UpstreamResponseModel pgtype.Text
	UpstreamFinishReason  pgtype.Text
	FinishClass           pgtype.Text
	Status                string
	UpstreamStatusCode    pgtype.Int4
	UpstreamRequestID     pgtype.Text
	ErrorCode             pgtype.Text
	ErrorMessage          pgtype.Text
	InternalErrorDetail   pgtype.Text
	ResponseStartedAt     pgtype.Timestamptz
	FinalUsageReceived    bool
	UsageMappingVersion   pgtype.Text
	RequiredCapabilities  []string
	UsedCapabilities      []string
	StartedAt             pgtype.Timestamptz
	CompletedAt           pgtype.Timestamptz
}

type CreateRequestAttemptRow struct {
	ID                    int64
	RequestRecordID       int64
	AttemptIndex          int32
	ProviderID            int64
	ChannelID             int64
	AdapterKey            string
	UpstreamModel         string
	UpstreamProtocol      string
	UpstreamResponseID    pgtype.Text
	UpstreamResponseModel pgtype.Text
	UpstreamFinishReason  pgtype.Text
	FinishClass           pgtype.Text
	Status                string
	UpstreamStatusCode    pgtype.Int4
	UpstreamRequestID     pgtype.Text
	ErrorCode             pgtype.Text
	ErrorMessage          pgtype.Text
	InternalErrorDetail   pgtype.Text
	ResponseStartedAt     pgtype.Timestamptz
	FinalUsageReceived    bool
	UsageMappingVersion   pgtype.Text
	RequiredCapabilities  []string
	UsedCapabilities      []string
	StartedAt             pgtype.Timestamptz
	CompletedAt           pgtype.Timestamptz
	CreatedAt             pgtype.Timestamptz
}

// CreateRequestAttempt 创建一次请求下的一次上游 channel 尝试记录。
func (q *Queries) CreateRequestAttempt(ctx context.Context, arg CreateRequestAttemptParams) (CreateRequestAttemptRow, error) {
	row := q.db.QueryRow(ctx, createRequestAttempt,
		arg.RequestRecordID,
		arg.AttemptIndex,
		arg.ProviderID,
		arg.ChannelID,
		arg.AdapterKey,
		arg.UpstreamModel,
		arg.UpstreamProtocol,
		arg.UpstreamResponseID,
		arg.UpstreamResponseModel,
		arg.UpstreamFinishReason,
		arg.FinishClass,
		arg.Status,
		arg.UpstreamStatusCode,
		arg.UpstreamRequestID,
		arg.ErrorCode,
		arg.ErrorMessage,
		arg.InternalErrorDetail,
		arg.ResponseStartedAt,
		arg.FinalUsageReceived,
		arg.UsageMappingVersion,
		arg.RequiredCapabilities,
		arg.UsedCapabilities,
		arg.StartedAt,
		arg.CompletedAt,
	)
	var i CreateRequestAttemptRow
	err := row.Scan(
		&i.ID,
		&i.RequestRecordID,
		&i.AttemptIndex,
		&i.ProviderID,
		&i.ChannelID,
		&i.AdapterKey,
		&i.UpstreamModel,
		&i.UpstreamProtocol,
		&i.UpstreamResponseID,
		&i.UpstreamResponseModel,
		&i.UpstreamFinishReason,
		&i.FinishClass,
		&i.Status,
		&i.UpstreamStatusCode,
		&i.UpstreamRequestID,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.InternalErrorDetail,
		&i.ResponseStartedAt,
		&i.FinalUsageReceived,
		&i.UsageMappingVersion,
		&i.RequiredCapabilities,
		&i.UsedCapabilities,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listRequestAttemptsByRequest = `-- name: ListRequestAttemptsByRequest :many
SELECT id, request_record_id, attempt_index, provider_id, channel_id, adapter_key, upstream_model, upstream_protocol, upstream_response_id, upstream_response_model, upstream_finish_reason, finish_class, status, upstream_status_code, upstream_request_id, error_code, error_message, internal_error_detail, response_started_at, final_usage_received, usage_mapping_version, required_capabilities, started_at, completed_at, created_at, used_capabilities
FROM request_attempts
WHERE request_record_id = $1
ORDER BY attempt_index
`

// ListRequestAttemptsByRequest 按请求 ID 列出完整上游尝试链路。
func (q *Queries) ListRequestAttemptsByRequest(ctx context.Context, requestRecordID int64) ([]RequestAttempt, error) {
	rows, err := q.db.Query(ctx, listRequestAttemptsByRequest, requestRecordID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RequestAttempt
	for rows.Next() {
		var i RequestAttempt
		if err := rows.Scan(
			&i.ID,
			&i.RequestRecordID,
			&i.AttemptIndex,
			&i.ProviderID,
			&i.ChannelID,
			&i.AdapterKey,
			&i.UpstreamModel,
			&i.UpstreamProtocol,
			&i.UpstreamResponseID,
			&i.UpstreamResponseModel,
			&i.UpstreamFinishReason,
			&i.FinishClass,
			&i.Status,
			&i.UpstreamStatusCode,
			&i.UpstreamRequestID,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.InternalErrorDetail,
			&i.ResponseStartedAt,
			&i.FinalUsageReceived,
			&i.UsageMappingVersion,
			&i.RequiredCapabilities,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UsedCapabilities,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markRequestAttemptCanceled = `-- name: MarkRequestAttemptCanceled :one
WITH updated AS (
    UPDATE request_attempts
        SET status = 'canceled',
            error_code = $1,
            error_message = $2,
            internal_error_detail = $3,
            completed_at = $4
        WHERE request_attempts.id = $5
            AND request_attempts.status = 'running'
        RETURNING request_attempts.id, request_attempts.request_record_id, request_attempts.attempt_index, request_attempts.provider_id, request_attempts.channel_id, request_attempts.adapter_key, request_attempts.upstream_model, request_attempts.upstream_protocol, request_attempts.upstream_response_id, request_attempts.upstream_response_model, request_attempts.upstream_finish_reason, request_attempts.finish_class, request_attempts.status, request_attempts.upstream_status_code, request_attempts.upstream_request_id, request_attempts.error_code, request_attempts.error_message, request_attempts.internal_error_detail, request_attempts.response_started_at, request_attempts.final_usage_received, request_attempts.usage_mapping_version, request_attempts.required_capabilities, request_attempts.started_at, request_attempts.completed_at, request_attempts.created_at, request_attempts.used_capabilities
)
SELECT id, request_record_id, attempt_index, provider_id, channel_id, adapter_key, upstream_model, upstream_protocol, upstream_response_id, upstream_response_model, upstream_finish_reason, finish_class, status, upstream_status_code, upstream_request_id, error_code, error_message, internal_error_detail, response_started_at, final_usage_received, usage_mapping_version, required_capabilities, started_at, completed_at, created_at, used_capabilities
FROM updated

UNION ALL

SELECT request_attempts.id, request_attempts.request_record_id, request_attempts.attempt_index, request_attempts.provider_id, request_attempts.channel_id, request_attempts.adapter_key, request_attempts.upstream_model, request_attempts.upstream_protocol, request_attempts.upstream_response_id, request_attempts.upstream_response_model, request_attempts.upstream_finish_reason, request_attempts.finish_class, request_attempts.status, request_attempts.upstream_status_code, request_attempts.upstream_request_id, request_attempts.error_code, request_attempts.error_message, request_attempts.internal_error_detail, request_attempts.response_started_at, request_attempts.final_usage_received, request_attempts.usage_mapping_version, request_attempts.required_capabilities, request_attempts.started_at, request_attempts.completed_at, request_attempts.created_at, request_attempts.used_capabilities
FROM request_attempts
WHERE request_attempts.id = $5
  AND request_attempts.status = 'canceled'
  AND NOT EXISTS (SELECT 1 FROM updated)
`

type MarkRequestAttemptCanceledParams struct {
	ErrorCode           pgtype.Text
	ErrorMessage        pgtype.Text
	InternalErrorDetail pgtype.Text
	CompletedAt         pgtype.Timestamptz
	AttemptID           int64
}

type MarkRequestAttemptCanceledRow struct {
	ID                    int64
	RequestRecordID       int64
	AttemptIndex          int32
	ProviderID            int64
	ChannelID             int64
	AdapterKey            string
	UpstreamModel         string
	UpstreamProtocol      string
	UpstreamResponseID    pgtype.Text
	UpstreamResponseModel pgtype.Text
	UpstreamFinishReason  pgtype.Text
	FinishClass           pgtype.Text
	Status                string
	UpstreamStatusCode    pgtype.Int4
	UpstreamRequestID     pgtype.Text
	ErrorCode             pgtype.Text
	ErrorMessage          pgtype.Text
	InternalErrorDetail   pgtype.Text
	ResponseStartedAt     pgtype.Timestamptz
	FinalUsageReceived    bool
	UsageMappingVersion   pgtype.Text
	RequiredCapabilities  []string
	StartedAt             pgtype.Timestamptz
	CompletedAt           pgtype.Timestamptz
	CreatedAt             pgtype.Timestamptz
	UsedCapabilities      []string
}

// MarkRequestAttemptCanceled 将 running attempt 原子推进到 canceled，重复 canceled 返回第一次取消事实。
// 重复取消写入不能覆盖 error metadata。
func (q *Queries) MarkRequestAttemptCanceled(ctx context.Context, arg MarkRequestAttemptCanceledParams) (MarkRequestAttemptCanceledRow, error) {
	row := q.db.QueryRow(ctx, markRequestAttemptCanceled,
		arg.ErrorCode,
		arg.ErrorMessage,
		arg.InternalErrorDetail,
		arg.CompletedAt,
		arg.AttemptID,
	)
	var i MarkRequestAttemptCanceledRow
	err := row.Scan(
		&i.ID,
		&i.RequestRecordID,
		&i.AttemptIndex,
		&i.ProviderID,
		&i.ChannelID,
		&i.AdapterKey,
		&i.UpstreamModel,
		&i.UpstreamProtocol,
		&i.UpstreamResponseID,
		&i.UpstreamResponseModel,
		&i.UpstreamFinishReason,
		&i.FinishClass,
		&i.Status,
		&i.UpstreamStatusCode,
		&i.UpstreamRequestID,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.InternalErrorDetail,
		&i.ResponseStartedAt,
		&i.FinalUsageReceived,
		&i.UsageMappingVersion,
		&i.RequiredCapabilities,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UsedCapabilities,
	)
	return i, err
}

const markRequestAttemptFailed = `-- name: MarkRequestAttemptFailed :one
WITH updated AS (
    UPDATE request_attempts
        SET status = 'failed',
            upstream_status_code = $1,
            upstream_request_id = $2,
            error_code = $3,
            error_message = $4,
            internal_error_detail = $5,
            completed_at = $6
        WHERE request_attempts.id = $7
            AND request_attempts.status = 'running'
        RETURNING request_attempts.id, request_attempts.request_record_id, request_attempts.attempt_index, request_attempts.provider_id, request_attempts.channel_id, request_attempts.adapter_key, request_attempts.upstream_model, request_attempts.upstream_protocol, request_attempts.upstream_response_id, request_attempts.upstream_response_model, request_attempts.upstream_finish_reason, request_attempts.finish_class, request_attempts.status, request_attempts.upstream_status_code, request_attempts.upstream_request_id, request_attempts.error_code, request_attempts.error_message, request_attempts.internal_error_detail, request_attempts.response_started_at, request_attempts.final_usage_received, request_attempts.usage_mapping_version, request_attempts.required_capabilities, request_attempts.started_at, request_attempts.completed_at, request_attempts.created_at, request_attempts.used_capabilities
)
SELECT id, request_record_id, attempt_index, provider_id, channel_id, adapter_key, upstream_model, upstream_protocol, upstream_response_id, upstream_response_model, upstream_finish_reason, finish_class, status, upstream_status_code, upstream_request_id, error_code, error_message, internal_error_detail, response_started_at, final_usage_received, usage_mapping_version, required_capabilities, started_at, completed_at, created_at, used_capabilities
FROM updated

UNION ALL

SELECT request_attempts.id, request_attempts.request_record_id, request_attempts.attempt_index, request_attempts.provider_id, request_attempts.channel_id, request_attempts.adapter_key, request_attempts.upstream_model, request_attempts.upstream_protocol, request_attempts.upstream_response_id, request_attempts.upstream_response_model, request_attempts.upstream_finish_reason, request_attempts.finish_class, request_attempts.status, request_attempts.upstream_status_code, request_attempts.upstream_request_id, request_attempts.error_code, request_attempts.error_message, request_attempts.internal_error_detail, request_attempts.response_started_at, request_attempts.final_usage_received, request_attempts.usage_mapping_version, request_attempts.required_capabilities, request_attempts.started_at, request_attempts.completed_at, request_attempts.created_at, request_attempts.used_capabilities
FROM request_attempts
WHERE request_attempts.id = $7
  AND request_attempts.status = 'failed'
  AND NOT EXISTS (SELECT 1 FROM updated)
`

type MarkRequestAttemptFailedParams struct {
	UpstreamStatusCode  pgtype.Int4
	UpstreamRequestID   pgtype.Text
	ErrorCode           pgtype.Text
	ErrorMessage        pgtype.Text
	InternalErrorDetail pgtype.Text
	CompletedAt         pgtype.Timestamptz
	AttemptID           int64
}

type MarkRequestAttemptFailedRow struct {
	ID                    int64
	RequestRecordID       int64
	AttemptIndex          int32
	ProviderID            int64
	ChannelID             int64
	AdapterKey            string
	UpstreamModel         string
	UpstreamProtocol      string
	UpstreamResponseID    pgtype.Text
	UpstreamResponseModel pgtype.Text
	UpstreamFinishReason  pgtype.Text
	FinishClass           pgtype.Text
	Status                string
	UpstreamStatusCode    pgtype.Int4
	UpstreamRequestID     pgtype.Text
	ErrorCode             pgtype.Text
	ErrorMessage          pgtype.Text
	InternalErrorDetail   pgtype.Text
	ResponseStartedAt     pgtype.Timestamptz
	FinalUsageReceived    bool
	UsageMappingVersion   pgtype.Text
	RequiredCapabilities  []string
	StartedAt             pgtype.Timestamptz
	CompletedAt           pgtype.Timestamptz
	CreatedAt             pgtype.Timestamptz
	UsedCapabilities      []string
}

// MarkRequestAttemptFailed 将 running attempt 原子推进到 failed，重复 failed 返回第一次失败事实。
// 重复失败写入不能覆盖 error/upstream metadata。
func (q *Queries) MarkRequestAttemptFailed(ctx context.Context, arg MarkRequestAttemptFailedParams) (MarkRequestAttemptFailedRow, error) {
	row := q.db.QueryRow(ctx, markRequestAttemptFailed,
		arg.UpstreamStatusCode,
		arg.UpstreamRequestID,
		arg.ErrorCode,
		arg.ErrorMessage,
		arg.InternalErrorDetail,
		arg.CompletedAt,
		arg.AttemptID,
	)
	var i MarkRequestAttemptFailedRow
	err := row.Scan(
		&i.ID,
		&i.RequestRecordID,
		&i.AttemptIndex,
		&i.ProviderID,
		&i.ChannelID,
		&i.AdapterKey,
		&i.UpstreamModel,
		&i.UpstreamProtocol,
		&i.UpstreamResponseID,
		&i.UpstreamResponseModel,
		&i.UpstreamFinishReason,
		&i.FinishClass,
		&i.Status,
		&i.UpstreamStatusCode,
		&i.UpstreamRequestID,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.InternalErrorDetail,
		&i.ResponseStartedAt,
		&i.FinalUsageReceived,
		&i.UsageMappingVersion,
		&i.RequiredCapabilities,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UsedCapabilities,
	)
	return i, err
}

const markRequestAttemptSucceeded = `-- name: MarkRequestAttemptSucceeded :one
WITH updated AS (
    UPDATE request_attempts
        SET status = 'succeeded',
            upstream_response_id = $1,
            upstream_response_model = $2,
            upstream_finish_reason = $3,
            finish_class = $4,
            upstream_status_code = $5,
            upstream_request_id = $6,
            final_usage_received = TRUE,
            usage_mapping_version = $7,
            used_capabilities = COALESCE($8::text[], '{}'),
            completed_at = $9
        WHERE request_attempts.id = $10
            AND request_attempts.status = 'running'
        RETURNING request_attempts.id, request_attempts.request_record_id, request_attempts.attempt_index, request_attempts.provider_id, request_attempts.channel_id, request_attempts.adapter_key, request_attempts.upstream_model, request_attempts.upstream_protocol, request_attempts.upstream_response_id, request_attempts.upstream_response_model, request_attempts.upstream_finish_reason, request_attempts.finish_class, request_attempts.status, request_attempts.upstream_status_code, request_attempts.upstream_request_id, request_attempts.error_code, request_attempts.error_message, request_attempts.internal_error_detail, request_attempts.response_started_at, request_attempts.final_usage_received, request_attempts.usage_mapping_version, request_attempts.required_capabilities, request_attempts.started_at, request_attempts.completed_at, request_attempts.created_at, request_attempts.used_capabilities
)
SELECT id, request_record_id, attempt_index, provider_id, channel_id, adapter_key, upstream_model, upstream_protocol, upstream_response_id, upstream_response_model, upstream_finish_reason, finish_class, status, upstream_status_code, upstream_request_id, error_code, error_message, internal_error_detail, response_started_at, final_usage_received, usage_mapping_version, required_capabilities, started_at, completed_at, created_at, used_capabilities
FROM updated

UNION ALL

SELECT request_attempts.id, request_attempts.request_record_id, request_attempts.attempt_index, request_attempts.provider_id, request_attempts.channel_id, request_attempts.adapter_key, request_attempts.upstream_model, request_attempts.upstream_protocol, request_attempts.upstream_response_id, request_attempts.upstream_response_model, request_attempts.upstream_finish_reason, request_attempts.finish_class, request_attempts.status, request_attempts.upstream_status_code, request_attempts.upstream_request_id, request_attempts.error_code, request_attempts.error_message, request_attempts.internal_error_detail, request_attempts.response_started_at, request_attempts.final_usage_received, request_attempts.usage_mapping_version, request_attempts.required_capabilities, request_attempts.started_at, request_attempts.completed_at, request_attempts.created_at, request_attempts.used_capabilities
FROM request_attempts
WHERE request_attempts.id = $10
  AND request_attempts.status = 'succeeded'
  AND NOT EXISTS (SELECT 1 FROM updated)
`

type MarkRequestAttemptSucceededParams struct {
	UpstreamResponseID    pgtype.Text
	UpstreamResponseModel pgtype.Text
	UpstreamFinishReason  pgtype.Text
	FinishClass           pgtype.Text
	UpstreamStatusCode    pgtype.Int4
	UpstreamRequestID     pgtype.Text
	UsageMappingVersion   pgtype.Text
	UsedCapabilities      []string
	CompletedAt           pgtype.Timestamptz
	AttemptID             int64
}

type MarkRequestAttemptSucceededRow struct {
	ID                    int64
	RequestRecordID       int64
	AttemptIndex          int32
	ProviderID            int64
	ChannelID             int64
	AdapterKey            string
	UpstreamModel         string
	UpstreamProtocol      string
	UpstreamResponseID    pgtype.Text
	UpstreamResponseModel pgtype.Text
	UpstreamFinishReason  pgtype.Text
	FinishClass           pgtype.Text
	Status                string
	UpstreamStatusCode    pgtype.Int4
	UpstreamRequestID     pgtype.Text
	ErrorCode             pgtype.Text
	ErrorMessage          pgtype.Text
	InternalErrorDetail   pgtype.Text
	ResponseStartedAt     pgtype.Timestamptz
	FinalUsageReceived    bool
	UsageMappingVersion   pgtype.Text
	RequiredCapabilities  []string
	StartedAt             pgtype.Timestamptz
	CompletedAt           pgtype.Timestamptz
	CreatedAt             pgtype.Timestamptz
	UsedCapabilities      []string
}

// MarkRequestAttemptSucceeded 将 running attempt 原子推进到 succeeded，重复 succeeded 返回第一次成功事实。
// 重复成功写入不能覆盖 upstream response metadata。
func (q *Queries) MarkRequestAttemptSucceeded(ctx context.Context, arg MarkRequestAttemptSucceededParams) (MarkRequestAttemptSucceededRow, error) {
	row := q.db.QueryRow(ctx, markRequestAttemptSucceeded,
		arg.UpstreamResponseID,
		arg.UpstreamResponseModel,
		arg.UpstreamFinishReason,
		arg.FinishClass,
		arg.UpstreamStatusCode,
		arg.UpstreamRequestID,
		arg.UsageMappingVersion,
		arg.UsedCapabilities,
		arg.CompletedAt,
		arg.AttemptID,
	)
	var i MarkRequestAttemptSucceededRow
	err := row.Scan(
		&i.ID,
		&i.RequestRecordID,
		&i.AttemptIndex,
		&i.ProviderID,
		&i.ChannelID,
		&i.AdapterKey,
		&i.UpstreamModel,
		&i.UpstreamProtocol,
		&i.UpstreamResponseID,
		&i.UpstreamResponseModel,
		&i.UpstreamFinishReason,
		&i.FinishClass,
		&i.Status,
		&i.UpstreamStatusCode,
		&i.UpstreamRequestID,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.InternalErrorDetail,
		&i.ResponseStartedAt,
		&i.FinalUsageReceived,
		&i.UsageMappingVersion,
		&i.RequiredCapabilities,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UsedCapabilities,
	)
	return i, err
}
