// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: request_records.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRequestRecord = `-- name: CreateRequestRecord :one
INSERT INTO request_records (
    request_id,
    user_id,
    api_key_id,
    requested_model_id,
    ingress_protocol,
    operation,
    response_model_id,
    response_protocol,
    response_id,
    stream,
    status,
    final_provider_id,
    final_channel_id,
    error_code,
    error_message,
    internal_error_detail,
    delivery_status,
    response_started_at,
    response_completed_at,
    started_at,
    completed_at,
    route_id,
    reasoning_effort,
    reasoning_budget_tokens,
    client_ip
)
VALUES (
           $1,
           $2,
           $3,
           $4,
           $5,
           $6,
           $7,
           $8,
           $9,
           $10,
           $11,
           $12,
           $13,
           $14,
           $15,
           $16,
           $17,
           $18,
           $19,
           $20,
           $21,
           $22,
           $23,
           $24,
           $25
       )
RETURNING
    id,
    request_id,
    user_id,
    api_key_id,
    requested_model_id,
    ingress_protocol,
    operation,
    response_model_id,
    response_protocol,
    response_id,
    stream,
    status,
    final_provider_id,
    final_channel_id,
    error_code,
    error_message,
    internal_error_detail,
    delivery_status,
    response_started_at,
    response_completed_at,
    started_at,
    completed_at,
    created_at,
    updated_at,
    route_id,
    reasoning_effort,
    reasoning_budget_tokens,
    client_ip
`

type CreateRequestRecordParams struct {
	RequestID             string
	UserID                int64
	ApiKeyID              int64
	RequestedModelID      string
	IngressProtocol       string
	Operation             string
	ResponseModelID       pgtype.Text
	ResponseProtocol      pgtype.Text
	ResponseID            pgtype.Text
	Stream                bool
	Status                string
	FinalProviderID       pgtype.Int8
	FinalChannelID        pgtype.Int8
	ErrorCode             pgtype.Text
	ErrorMessage          pgtype.Text
	InternalErrorDetail   pgtype.Text
	DeliveryStatus        string
	ResponseStartedAt     pgtype.Timestamptz
	ResponseCompletedAt   pgtype.Timestamptz
	StartedAt             pgtype.Timestamptz
	CompletedAt           pgtype.Timestamptz
	RouteID               pgtype.Int8
	ReasoningEffort       pgtype.Text
	ReasoningBudgetTokens pgtype.Int4
	ClientIp              pgtype.Text
}

// CreateRequestRecord 创建一次用户可见的 Unio API 请求记录。
func (q *Queries) CreateRequestRecord(ctx context.Context, arg CreateRequestRecordParams) (RequestRecord, error) {
	row := q.db.QueryRow(ctx, createRequestRecord,
		arg.RequestID,
		arg.UserID,
		arg.ApiKeyID,
		arg.RequestedModelID,
		arg.IngressProtocol,
		arg.Operation,
		arg.ResponseModelID,
		arg.ResponseProtocol,
		arg.ResponseID,
		arg.Stream,
		arg.Status,
		arg.FinalProviderID,
		arg.FinalChannelID,
		arg.ErrorCode,
		arg.ErrorMessage,
		arg.InternalErrorDetail,
		arg.DeliveryStatus,
		arg.ResponseStartedAt,
		arg.ResponseCompletedAt,
		arg.StartedAt,
		arg.CompletedAt,
		arg.RouteID,
		arg.ReasoningEffort,
		arg.ReasoningBudgetTokens,
		arg.ClientIp,
	)
	var i RequestRecord
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.UserID,
		&i.ApiKeyID,
		&i.RequestedModelID,
		&i.IngressProtocol,
		&i.Operation,
		&i.ResponseModelID,
		&i.ResponseProtocol,
		&i.ResponseID,
		&i.Stream,
		&i.Status,
		&i.FinalProviderID,
		&i.FinalChannelID,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.InternalErrorDetail,
		&i.DeliveryStatus,
		&i.ResponseStartedAt,
		&i.ResponseCompletedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RouteID,
		&i.ReasoningEffort,
		&i.ReasoningBudgetTokens,
		&i.ClientIp,
	)
	return i, err
}

const getRequestRecordForUpdate = `-- name: GetRequestRecordForUpdate :one
SELECT
    id,
    request_id,
    user_id,
    api_key_id,
    requested_model_id,
    ingress_protocol,
    operation,
    response_model_id,
    response_protocol,
    response_id,
    stream,
    status,
    final_provider_id,
    final_channel_id,
    error_code,
    error_message,
    internal_error_detail,
    delivery_status,
    response_started_at,
    response_completed_at,
    started_at,
    completed_at,
    created_at,
    updated_at,
    route_id,
    reasoning_effort,
    reasoning_budget_tokens,
    client_ip
FROM request_records
WHERE id = $1
    FOR UPDATE
`

// GetRequestRecordForUpdate 锁定请求记录，串行化同一个 request 的并发结算。
// running 表示本次可以继续首次 settlement；succeeded 表示可能是幂等重放。
func (q *Queries) GetRequestRecordForUpdate(ctx context.Context, requestRecordID int64) (RequestRecord, error) {
	row := q.db.QueryRow(ctx, getRequestRecordForUpdate, requestRecordID)
	var i RequestRecord
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.UserID,
		&i.ApiKeyID,
		&i.RequestedModelID,
		&i.IngressProtocol,
		&i.Operation,
		&i.ResponseModelID,
		&i.ResponseProtocol,
		&i.ResponseID,
		&i.Stream,
		&i.Status,
		&i.FinalProviderID,
		&i.FinalChannelID,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.InternalErrorDetail,
		&i.DeliveryStatus,
		&i.ResponseStartedAt,
		&i.ResponseCompletedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RouteID,
		&i.ReasoningEffort,
		&i.ReasoningBudgetTokens,
		&i.ClientIp,
	)
	return i, err
}

const markRequestCanceled = `-- name: MarkRequestCanceled :one
WITH updated AS (
    UPDATE request_records
        SET status = 'canceled',
            error_code = $1,
            error_message = $2,
            internal_error_detail = $3,
            completed_at = $4,
            updated_at = now()
        WHERE request_records.id = $5
            AND request_records.status = 'running'
        RETURNING request_records.id, request_records.request_id, request_records.user_id, request_records.api_key_id, request_records.requested_model_id, request_records.ingress_protocol, request_records.operation, request_records.response_model_id, request_records.response_protocol, request_records.response_id, request_records.stream, request_records.status, request_records.final_provider_id, request_records.final_channel_id, request_records.error_code, request_records.error_message, request_records.internal_error_detail, request_records.delivery_status, request_records.response_started_at, request_records.response_completed_at, request_records.started_at, request_records.completed_at, request_records.created_at, request_records.updated_at, request_records.route_id, request_records.reasoning_effort, request_records.reasoning_budget_tokens, request_records.client_ip
)
SELECT id, request_id, user_id, api_key_id, requested_model_id, ingress_protocol, operation, response_model_id, response_protocol, response_id, stream, status, final_provider_id, final_channel_id, error_code, error_message, internal_error_detail, delivery_status, response_started_at, response_completed_at, started_at, completed_at, created_at, updated_at, route_id, reasoning_effort, reasoning_budget_tokens, client_ip
FROM updated

UNION ALL

SELECT request_records.id, request_records.request_id, request_records.user_id, request_records.api_key_id, request_records.requested_model_id, request_records.ingress_protocol, request_records.operation, request_records.response_model_id, request_records.response_protocol, request_records.response_id, request_records.stream, request_records.status, request_records.final_provider_id, request_records.final_channel_id, request_records.error_code, request_records.error_message, request_records.internal_error_detail, request_records.delivery_status, request_records.response_started_at, request_records.response_completed_at, request_records.started_at, request_records.completed_at, request_records.created_at, request_records.updated_at, request_records.route_id, request_records.reasoning_effort, request_records.reasoning_budget_tokens, request_records.client_ip
FROM request_records
WHERE request_records.id = $5
  AND request_records.status = 'canceled'
  AND NOT EXISTS (SELECT 1 FROM updated)
`

type MarkRequestCanceledParams struct {
	ErrorCode           pgtype.Text
	ErrorMessage        pgtype.Text
	InternalErrorDetail pgtype.Text
	CompletedAt         pgtype.Timestamptz
	RequestRecordID     int64
}

type MarkRequestCanceledRow struct {
	ID                    int64
	RequestID             string
	UserID                int64
	ApiKeyID              int64
	RequestedModelID      string
	IngressProtocol       string
	Operation             string
	ResponseModelID       pgtype.Text
	ResponseProtocol      pgtype.Text
	ResponseID            pgtype.Text
	Stream                bool
	Status                string
	FinalProviderID       pgtype.Int8
	FinalChannelID        pgtype.Int8
	ErrorCode             pgtype.Text
	ErrorMessage          pgtype.Text
	InternalErrorDetail   pgtype.Text
	DeliveryStatus        string
	ResponseStartedAt     pgtype.Timestamptz
	ResponseCompletedAt   pgtype.Timestamptz
	StartedAt             pgtype.Timestamptz
	CompletedAt           pgtype.Timestamptz
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
	RouteID               pgtype.Int8
	ReasoningEffort       pgtype.Text
	ReasoningBudgetTokens pgtype.Int4
	ClientIp              pgtype.Text
}

// MarkRequestCanceled 将 running 请求原子推进到 canceled，重复 canceled 返回第一次取消事实。
// 重复取消写入不能覆盖 error_code/error_message/internal_error_detail/completed_at。
func (q *Queries) MarkRequestCanceled(ctx context.Context, arg MarkRequestCanceledParams) (MarkRequestCanceledRow, error) {
	row := q.db.QueryRow(ctx, markRequestCanceled,
		arg.ErrorCode,
		arg.ErrorMessage,
		arg.InternalErrorDetail,
		arg.CompletedAt,
		arg.RequestRecordID,
	)
	var i MarkRequestCanceledRow
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.UserID,
		&i.ApiKeyID,
		&i.RequestedModelID,
		&i.IngressProtocol,
		&i.Operation,
		&i.ResponseModelID,
		&i.ResponseProtocol,
		&i.ResponseID,
		&i.Stream,
		&i.Status,
		&i.FinalProviderID,
		&i.FinalChannelID,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.InternalErrorDetail,
		&i.DeliveryStatus,
		&i.ResponseStartedAt,
		&i.ResponseCompletedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RouteID,
		&i.ReasoningEffort,
		&i.ReasoningBudgetTokens,
		&i.ClientIp,
	)
	return i, err
}

const markRequestDeliveryCompleted = `-- name: MarkRequestDeliveryCompleted :one
WITH updated AS (
    UPDATE request_records
        SET delivery_status = 'completed',
            response_completed_at = $1,
            updated_at = now()
        WHERE request_records.id = $2
            AND request_records.delivery_status IN ('not_started', 'in_progress')
        RETURNING request_records.id, request_records.request_id, request_records.user_id, request_records.api_key_id, request_records.requested_model_id, request_records.ingress_protocol, request_records.operation, request_records.response_model_id, request_records.response_protocol, request_records.response_id, request_records.stream, request_records.status, request_records.final_provider_id, request_records.final_channel_id, request_records.error_code, request_records.error_message, request_records.internal_error_detail, request_records.delivery_status, request_records.response_started_at, request_records.response_completed_at, request_records.started_at, request_records.completed_at, request_records.created_at, request_records.updated_at, request_records.route_id, request_records.reasoning_effort, request_records.reasoning_budget_tokens, request_records.client_ip
)
SELECT id, request_id, user_id, api_key_id, requested_model_id, ingress_protocol, operation, response_model_id, response_protocol, response_id, stream, status, final_provider_id, final_channel_id, error_code, error_message, internal_error_detail, delivery_status, response_started_at, response_completed_at, started_at, completed_at, created_at, updated_at, route_id, reasoning_effort, reasoning_budget_tokens, client_ip
FROM updated

UNION ALL

SELECT request_records.id, request_records.request_id, request_records.user_id, request_records.api_key_id, request_records.requested_model_id, request_records.ingress_protocol, request_records.operation, request_records.response_model_id, request_records.response_protocol, request_records.response_id, request_records.stream, request_records.status, request_records.final_provider_id, request_records.final_channel_id, request_records.error_code, request_records.error_message, request_records.internal_error_detail, request_records.delivery_status, request_records.response_started_at, request_records.response_completed_at, request_records.started_at, request_records.completed_at, request_records.created_at, request_records.updated_at, request_records.route_id, request_records.reasoning_effort, request_records.reasoning_budget_tokens, request_records.client_ip
FROM request_records
WHERE request_records.id = $2
  AND request_records.delivery_status = 'completed'
  AND NOT EXISTS (SELECT 1 FROM updated)
`

type MarkRequestDeliveryCompletedParams struct {
	ResponseCompletedAt pgtype.Timestamptz
	RequestRecordID     int64
}

type MarkRequestDeliveryCompletedRow struct {
	ID                    int64
	RequestID             string
	UserID                int64
	ApiKeyID              int64
	RequestedModelID      string
	IngressProtocol       string
	Operation             string
	ResponseModelID       pgtype.Text
	ResponseProtocol      pgtype.Text
	ResponseID            pgtype.Text
	Stream                bool
	Status                string
	FinalProviderID       pgtype.Int8
	FinalChannelID        pgtype.Int8
	ErrorCode             pgtype.Text
	ErrorMessage          pgtype.Text
	InternalErrorDetail   pgtype.Text
	DeliveryStatus        string
	ResponseStartedAt     pgtype.Timestamptz
	ResponseCompletedAt   pgtype.Timestamptz
	StartedAt             pgtype.Timestamptz
	CompletedAt           pgtype.Timestamptz
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
	RouteID               pgtype.Int8
	ReasoningEffort       pgtype.Text
	ReasoningBudgetTokens pgtype.Int4
	ClientIp              pgtype.Text
}

// MarkRequestDeliveryCompleted 在响应完整交付后把交付状态推进到 completed，并同语句落地
// response_completed_at，满足 ck_request_records_delivery_completed_at。仅从 not_started/in_progress
// 推进；重复调用返回当前 completed 行（幂等，最佳努力审计）。
func (q *Queries) MarkRequestDeliveryCompleted(ctx context.Context, arg MarkRequestDeliveryCompletedParams) (MarkRequestDeliveryCompletedRow, error) {
	row := q.db.QueryRow(ctx, markRequestDeliveryCompleted, arg.ResponseCompletedAt, arg.RequestRecordID)
	var i MarkRequestDeliveryCompletedRow
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.UserID,
		&i.ApiKeyID,
		&i.RequestedModelID,
		&i.IngressProtocol,
		&i.Operation,
		&i.ResponseModelID,
		&i.ResponseProtocol,
		&i.ResponseID,
		&i.Stream,
		&i.Status,
		&i.FinalProviderID,
		&i.FinalChannelID,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.InternalErrorDetail,
		&i.DeliveryStatus,
		&i.ResponseStartedAt,
		&i.ResponseCompletedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RouteID,
		&i.ReasoningEffort,
		&i.ReasoningBudgetTokens,
		&i.ClientIp,
	)
	return i, err
}

const markRequestDeliveryInterrupted = `-- name: MarkRequestDeliveryInterrupted :one
WITH updated AS (
    UPDATE request_records
        SET delivery_status = 'interrupted',
            updated_at = now()
        WHERE request_records.id = $1
            AND request_records.delivery_status IN ('not_started', 'in_progress')
        RETURNING request_records.id, request_records.request_id, request_records.user_id, request_records.api_key_id, request_records.requested_model_id, request_records.ingress_protocol, request_records.operation, request_records.response_model_id, request_records.response_protocol, request_records.response_id, request_records.stream, request_records.status, request_records.final_provider_id, request_records.final_channel_id, request_records.error_code, request_records.error_message, request_records.internal_error_detail, request_records.delivery_status, request_records.response_started_at, request_records.response_completed_at, request_records.started_at, request_records.completed_at, request_records.created_at, request_records.updated_at, request_records.route_id, request_records.reasoning_effort, request_records.reasoning_budget_tokens, request_records.client_ip
)
SELECT id, request_id, user_id, api_key_id, requested_model_id, ingress_protocol, operation, response_model_id, response_protocol, response_id, stream, status, final_provider_id, final_channel_id, error_code, error_message, internal_error_detail, delivery_status, response_started_at, response_completed_at, started_at, completed_at, created_at, updated_at, route_id, reasoning_effort, reasoning_budget_tokens, client_ip
FROM updated

UNION ALL

SELECT request_records.id, request_records.request_id, request_records.user_id, request_records.api_key_id, request_records.requested_model_id, request_records.ingress_protocol, request_records.operation, request_records.response_model_id, request_records.response_protocol, request_records.response_id, request_records.stream, request_records.status, request_records.final_provider_id, request_records.final_channel_id, request_records.error_code, request_records.error_message, request_records.internal_error_detail, request_records.delivery_status, request_records.response_started_at, request_records.response_completed_at, request_records.started_at, request_records.completed_at, request_records.created_at, request_records.updated_at, request_records.route_id, request_records.reasoning_effort, request_records.reasoning_budget_tokens, request_records.client_ip
FROM request_records
WHERE request_records.id = $1
  AND request_records.delivery_status = 'interrupted'
  AND NOT EXISTS (SELECT 1 FROM updated)
`

type MarkRequestDeliveryInterruptedRow struct {
	ID                    int64
	RequestID             string
	UserID                int64
	ApiKeyID              int64
	RequestedModelID      string
	IngressProtocol       string
	Operation             string
	ResponseModelID       pgtype.Text
	ResponseProtocol      pgtype.Text
	ResponseID            pgtype.Text
	Stream                bool
	Status                string
	FinalProviderID       pgtype.Int8
	FinalChannelID        pgtype.Int8
	ErrorCode             pgtype.Text
	ErrorMessage          pgtype.Text
	InternalErrorDetail   pgtype.Text
	DeliveryStatus        string
	ResponseStartedAt     pgtype.Timestamptz
	ResponseCompletedAt   pgtype.Timestamptz
	StartedAt             pgtype.Timestamptz
	CompletedAt           pgtype.Timestamptz
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
	RouteID               pgtype.Int8
	ReasoningEffort       pgtype.Text
	ReasoningBudgetTokens pgtype.Int4
	ClientIp              pgtype.Text
}

// MarkRequestDeliveryInterrupted 在交付中断（客户端取消、上游中断、尾部错误）时把交付状态推进到
// interrupted。response_completed_at 保持 NULL。仅从 not_started/in_progress 推进；重复调用返回当前
// interrupted 行（幂等，最佳努力审计）。
func (q *Queries) MarkRequestDeliveryInterrupted(ctx context.Context, requestRecordID int64) (MarkRequestDeliveryInterruptedRow, error) {
	row := q.db.QueryRow(ctx, markRequestDeliveryInterrupted, requestRecordID)
	var i MarkRequestDeliveryInterruptedRow
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.UserID,
		&i.ApiKeyID,
		&i.RequestedModelID,
		&i.IngressProtocol,
		&i.Operation,
		&i.ResponseModelID,
		&i.ResponseProtocol,
		&i.ResponseID,
		&i.Stream,
		&i.Status,
		&i.FinalProviderID,
		&i.FinalChannelID,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.InternalErrorDetail,
		&i.DeliveryStatus,
		&i.ResponseStartedAt,
		&i.ResponseCompletedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RouteID,
		&i.ReasoningEffort,
		&i.ReasoningBudgetTokens,
		&i.ClientIp,
	)
	return i, err
}

const markRequestFailed = `-- name: MarkRequestFailed :one
WITH updated AS (
    UPDATE request_records
        SET status = 'failed',
            error_code = $1,
            error_message = $2,
            internal_error_detail = $3,
            completed_at = $4,
            updated_at = now()
        WHERE request_records.id = $5
            AND request_records.status = 'running'
        RETURNING request_records.id, request_records.request_id, request_records.user_id, request_records.api_key_id, request_records.requested_model_id, request_records.ingress_protocol, request_records.operation, request_records.response_model_id, request_records.response_protocol, request_records.response_id, request_records.stream, request_records.status, request_records.final_provider_id, request_records.final_channel_id, request_records.error_code, request_records.error_message, request_records.internal_error_detail, request_records.delivery_status, request_records.response_started_at, request_records.response_completed_at, request_records.started_at, request_records.completed_at, request_records.created_at, request_records.updated_at, request_records.route_id, request_records.reasoning_effort, request_records.reasoning_budget_tokens, request_records.client_ip
)
SELECT id, request_id, user_id, api_key_id, requested_model_id, ingress_protocol, operation, response_model_id, response_protocol, response_id, stream, status, final_provider_id, final_channel_id, error_code, error_message, internal_error_detail, delivery_status, response_started_at, response_completed_at, started_at, completed_at, created_at, updated_at, route_id, reasoning_effort, reasoning_budget_tokens, client_ip
FROM updated

UNION ALL

SELECT request_records.id, request_records.request_id, request_records.user_id, request_records.api_key_id, request_records.requested_model_id, request_records.ingress_protocol, request_records.operation, request_records.response_model_id, request_records.response_protocol, request_records.response_id, request_records.stream, request_records.status, request_records.final_provider_id, request_records.final_channel_id, request_records.error_code, request_records.error_message, request_records.internal_error_detail, request_records.delivery_status, request_records.response_started_at, request_records.response_completed_at, request_records.started_at, request_records.completed_at, request_records.created_at, request_records.updated_at, request_records.route_id, request_records.reasoning_effort, request_records.reasoning_budget_tokens, request_records.client_ip
FROM request_records
WHERE request_records.id = $5
  AND request_records.status = 'failed'
  AND NOT EXISTS (SELECT 1 FROM updated)
`

type MarkRequestFailedParams struct {
	ErrorCode           pgtype.Text
	ErrorMessage        pgtype.Text
	InternalErrorDetail pgtype.Text
	CompletedAt         pgtype.Timestamptz
	RequestRecordID     int64
}

type MarkRequestFailedRow struct {
	ID                    int64
	RequestID             string
	UserID                int64
	ApiKeyID              int64
	RequestedModelID      string
	IngressProtocol       string
	Operation             string
	ResponseModelID       pgtype.Text
	ResponseProtocol      pgtype.Text
	ResponseID            pgtype.Text
	Stream                bool
	Status                string
	FinalProviderID       pgtype.Int8
	FinalChannelID        pgtype.Int8
	ErrorCode             pgtype.Text
	ErrorMessage          pgtype.Text
	InternalErrorDetail   pgtype.Text
	DeliveryStatus        string
	ResponseStartedAt     pgtype.Timestamptz
	ResponseCompletedAt   pgtype.Timestamptz
	StartedAt             pgtype.Timestamptz
	CompletedAt           pgtype.Timestamptz
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
	RouteID               pgtype.Int8
	ReasoningEffort       pgtype.Text
	ReasoningBudgetTokens pgtype.Int4
	ClientIp              pgtype.Text
}

// MarkRequestFailed 将 running 请求原子推进到 failed，重复 failed 返回第一次失败事实。
// 重复失败写入不能覆盖 error_code/error_message/internal_error_detail/completed_at。
func (q *Queries) MarkRequestFailed(ctx context.Context, arg MarkRequestFailedParams) (MarkRequestFailedRow, error) {
	row := q.db.QueryRow(ctx, markRequestFailed,
		arg.ErrorCode,
		arg.ErrorMessage,
		arg.InternalErrorDetail,
		arg.CompletedAt,
		arg.RequestRecordID,
	)
	var i MarkRequestFailedRow
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.UserID,
		&i.ApiKeyID,
		&i.RequestedModelID,
		&i.IngressProtocol,
		&i.Operation,
		&i.ResponseModelID,
		&i.ResponseProtocol,
		&i.ResponseID,
		&i.Stream,
		&i.Status,
		&i.FinalProviderID,
		&i.FinalChannelID,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.InternalErrorDetail,
		&i.DeliveryStatus,
		&i.ResponseStartedAt,
		&i.ResponseCompletedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RouteID,
		&i.ReasoningEffort,
		&i.ReasoningBudgetTokens,
		&i.ClientIp,
	)
	return i, err
}

const markRequestResponseStarted = `-- name: MarkRequestResponseStarted :one
WITH updated AS (
    UPDATE request_records
        SET response_started_at = COALESCE(request_records.response_started_at, $1),
            delivery_status = CASE
                WHEN request_records.delivery_status = 'not_started' THEN 'in_progress'
                ELSE request_records.delivery_status
            END,
            updated_at = now()
        WHERE request_records.id = $2
          AND request_records.status IN ('running', 'succeeded')
        RETURNING request_records.id, request_records.request_id, request_records.user_id, request_records.api_key_id, request_records.requested_model_id, request_records.ingress_protocol, request_records.operation, request_records.response_model_id, request_records.response_protocol, request_records.response_id, request_records.stream, request_records.status, request_records.final_provider_id, request_records.final_channel_id, request_records.error_code, request_records.error_message, request_records.internal_error_detail, request_records.delivery_status, request_records.response_started_at, request_records.response_completed_at, request_records.started_at, request_records.completed_at, request_records.created_at, request_records.updated_at, request_records.route_id, request_records.reasoning_effort, request_records.reasoning_budget_tokens, request_records.client_ip
)
SELECT id, request_id, user_id, api_key_id, requested_model_id, ingress_protocol, operation, response_model_id, response_protocol, response_id, stream, status, final_provider_id, final_channel_id, error_code, error_message, internal_error_detail, delivery_status, response_started_at, response_completed_at, started_at, completed_at, created_at, updated_at, route_id, reasoning_effort, reasoning_budget_tokens, client_ip
FROM updated

UNION ALL

SELECT request_records.id, request_records.request_id, request_records.user_id, request_records.api_key_id, request_records.requested_model_id, request_records.ingress_protocol, request_records.operation, request_records.response_model_id, request_records.response_protocol, request_records.response_id, request_records.stream, request_records.status, request_records.final_provider_id, request_records.final_channel_id, request_records.error_code, request_records.error_message, request_records.internal_error_detail, request_records.delivery_status, request_records.response_started_at, request_records.response_completed_at, request_records.started_at, request_records.completed_at, request_records.created_at, request_records.updated_at, request_records.route_id, request_records.reasoning_effort, request_records.reasoning_budget_tokens, request_records.client_ip
FROM request_records
WHERE request_records.id = $2
  AND request_records.response_started_at IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM updated)
`

type MarkRequestResponseStartedParams struct {
	ResponseStartedAt pgtype.Timestamptz
	RequestRecordID   int64
}

type MarkRequestResponseStartedRow struct {
	ID                    int64
	RequestID             string
	UserID                int64
	ApiKeyID              int64
	RequestedModelID      string
	IngressProtocol       string
	Operation             string
	ResponseModelID       pgtype.Text
	ResponseProtocol      pgtype.Text
	ResponseID            pgtype.Text
	Stream                bool
	Status                string
	FinalProviderID       pgtype.Int8
	FinalChannelID        pgtype.Int8
	ErrorCode             pgtype.Text
	ErrorMessage          pgtype.Text
	InternalErrorDetail   pgtype.Text
	DeliveryStatus        string
	ResponseStartedAt     pgtype.Timestamptz
	ResponseCompletedAt   pgtype.Timestamptz
	StartedAt             pgtype.Timestamptz
	CompletedAt           pgtype.Timestamptz
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
	RouteID               pgtype.Int8
	ReasoningEffort       pgtype.Text
	ReasoningBudgetTokens pgtype.Int4
	ClientIp              pgtype.Text
}

// MarkRequestResponseStarted 记录首次客户可见响应时间，并把交付状态从 not_started 推进到 in_progress。
// 重复调用保留第一次时间，且不回退已更靠后的交付状态。首字节时 delivery 与 response_started_at 同写。
func (q *Queries) MarkRequestResponseStarted(ctx context.Context, arg MarkRequestResponseStartedParams) (MarkRequestResponseStartedRow, error) {
	row := q.db.QueryRow(ctx, markRequestResponseStarted, arg.ResponseStartedAt, arg.RequestRecordID)
	var i MarkRequestResponseStartedRow
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.UserID,
		&i.ApiKeyID,
		&i.RequestedModelID,
		&i.IngressProtocol,
		&i.Operation,
		&i.ResponseModelID,
		&i.ResponseProtocol,
		&i.ResponseID,
		&i.Stream,
		&i.Status,
		&i.FinalProviderID,
		&i.FinalChannelID,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.InternalErrorDetail,
		&i.DeliveryStatus,
		&i.ResponseStartedAt,
		&i.ResponseCompletedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RouteID,
		&i.ReasoningEffort,
		&i.ReasoningBudgetTokens,
		&i.ClientIp,
	)
	return i, err
}

const markRequestRunning = `-- name: MarkRequestRunning :one
WITH updated AS (
    UPDATE request_records
        SET status = 'running',
            updated_at = now()
        WHERE request_records.id = $1
            AND request_records.status = 'pending'
        RETURNING request_records.id, request_records.request_id, request_records.user_id, request_records.api_key_id, request_records.requested_model_id, request_records.ingress_protocol, request_records.operation, request_records.response_model_id, request_records.response_protocol, request_records.response_id, request_records.stream, request_records.status, request_records.final_provider_id, request_records.final_channel_id, request_records.error_code, request_records.error_message, request_records.internal_error_detail, request_records.delivery_status, request_records.response_started_at, request_records.response_completed_at, request_records.started_at, request_records.completed_at, request_records.created_at, request_records.updated_at, request_records.route_id, request_records.reasoning_effort, request_records.reasoning_budget_tokens, request_records.client_ip
)
SELECT id, request_id, user_id, api_key_id, requested_model_id, ingress_protocol, operation, response_model_id, response_protocol, response_id, stream, status, final_provider_id, final_channel_id, error_code, error_message, internal_error_detail, delivery_status, response_started_at, response_completed_at, started_at, completed_at, created_at, updated_at, route_id, reasoning_effort, reasoning_budget_tokens, client_ip
FROM updated

UNION ALL

SELECT request_records.id, request_records.request_id, request_records.user_id, request_records.api_key_id, request_records.requested_model_id, request_records.ingress_protocol, request_records.operation, request_records.response_model_id, request_records.response_protocol, request_records.response_id, request_records.stream, request_records.status, request_records.final_provider_id, request_records.final_channel_id, request_records.error_code, request_records.error_message, request_records.internal_error_detail, request_records.delivery_status, request_records.response_started_at, request_records.response_completed_at, request_records.started_at, request_records.completed_at, request_records.created_at, request_records.updated_at, request_records.route_id, request_records.reasoning_effort, request_records.reasoning_budget_tokens, request_records.client_ip
FROM request_records
WHERE request_records.id = $1
  AND request_records.status = 'running'
  AND NOT EXISTS (SELECT 1 FROM updated)
`

type MarkRequestRunningRow struct {
	ID                    int64
	RequestID             string
	UserID                int64
	ApiKeyID              int64
	RequestedModelID      string
	IngressProtocol       string
	Operation             string
	ResponseModelID       pgtype.Text
	ResponseProtocol      pgtype.Text
	ResponseID            pgtype.Text
	Stream                bool
	Status                string
	FinalProviderID       pgtype.Int8
	FinalChannelID        pgtype.Int8
	ErrorCode             pgtype.Text
	ErrorMessage          pgtype.Text
	InternalErrorDetail   pgtype.Text
	DeliveryStatus        string
	ResponseStartedAt     pgtype.Timestamptz
	ResponseCompletedAt   pgtype.Timestamptz
	StartedAt             pgtype.Timestamptz
	CompletedAt           pgtype.Timestamptz
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
	RouteID               pgtype.Int8
	ReasoningEffort       pgtype.Text
	ReasoningBudgetTokens pgtype.Int4
	ClientIp              pgtype.Text
}

// MarkRequestRunning 将 pending 请求原子推进到 running，重复 running 返回原事实。
// succeeded/failed/canceled 是终态，不会被重新打开。
func (q *Queries) MarkRequestRunning(ctx context.Context, requestRecordID int64) (MarkRequestRunningRow, error) {
	row := q.db.QueryRow(ctx, markRequestRunning, requestRecordID)
	var i MarkRequestRunningRow
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.UserID,
		&i.ApiKeyID,
		&i.RequestedModelID,
		&i.IngressProtocol,
		&i.Operation,
		&i.ResponseModelID,
		&i.ResponseProtocol,
		&i.ResponseID,
		&i.Stream,
		&i.Status,
		&i.FinalProviderID,
		&i.FinalChannelID,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.InternalErrorDetail,
		&i.DeliveryStatus,
		&i.ResponseStartedAt,
		&i.ResponseCompletedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RouteID,
		&i.ReasoningEffort,
		&i.ReasoningBudgetTokens,
		&i.ClientIp,
	)
	return i, err
}

const markRequestSucceeded = `-- name: MarkRequestSucceeded :one
WITH updated AS (
    UPDATE request_records
        SET status = 'succeeded',
            response_model_id = $1,
            response_protocol = $2,
            response_id = $3,
            final_provider_id = $4,
            final_channel_id = $5,
            response_started_at = COALESCE(request_records.response_started_at, $6),
            completed_at = $7,
            updated_at = now()
        WHERE request_records.id = $8
            AND request_records.status = 'running'
        RETURNING request_records.id, request_records.request_id, request_records.user_id, request_records.api_key_id, request_records.requested_model_id, request_records.ingress_protocol, request_records.operation, request_records.response_model_id, request_records.response_protocol, request_records.response_id, request_records.stream, request_records.status, request_records.final_provider_id, request_records.final_channel_id, request_records.error_code, request_records.error_message, request_records.internal_error_detail, request_records.delivery_status, request_records.response_started_at, request_records.response_completed_at, request_records.started_at, request_records.completed_at, request_records.created_at, request_records.updated_at, request_records.route_id, request_records.reasoning_effort, request_records.reasoning_budget_tokens, request_records.client_ip
)
SELECT id, request_id, user_id, api_key_id, requested_model_id, ingress_protocol, operation, response_model_id, response_protocol, response_id, stream, status, final_provider_id, final_channel_id, error_code, error_message, internal_error_detail, delivery_status, response_started_at, response_completed_at, started_at, completed_at, created_at, updated_at, route_id, reasoning_effort, reasoning_budget_tokens, client_ip
FROM updated

UNION ALL

SELECT request_records.id, request_records.request_id, request_records.user_id, request_records.api_key_id, request_records.requested_model_id, request_records.ingress_protocol, request_records.operation, request_records.response_model_id, request_records.response_protocol, request_records.response_id, request_records.stream, request_records.status, request_records.final_provider_id, request_records.final_channel_id, request_records.error_code, request_records.error_message, request_records.internal_error_detail, request_records.delivery_status, request_records.response_started_at, request_records.response_completed_at, request_records.started_at, request_records.completed_at, request_records.created_at, request_records.updated_at, request_records.route_id, request_records.reasoning_effort, request_records.reasoning_budget_tokens, request_records.client_ip
FROM request_records
WHERE request_records.id = $8
  AND request_records.status = 'succeeded'
  AND NOT EXISTS (SELECT 1 FROM updated)
`

type MarkRequestSucceededParams struct {
	ResponseModelID   pgtype.Text
	ResponseProtocol  pgtype.Text
	ResponseID        pgtype.Text
	FinalProviderID   pgtype.Int8
	FinalChannelID    pgtype.Int8
	ResponseStartedAt pgtype.Timestamptz
	CompletedAt       pgtype.Timestamptz
	RequestRecordID   int64
}

type MarkRequestSucceededRow struct {
	ID                    int64
	RequestID             string
	UserID                int64
	ApiKeyID              int64
	RequestedModelID      string
	IngressProtocol       string
	Operation             string
	ResponseModelID       pgtype.Text
	ResponseProtocol      pgtype.Text
	ResponseID            pgtype.Text
	Stream                bool
	Status                string
	FinalProviderID       pgtype.Int8
	FinalChannelID        pgtype.Int8
	ErrorCode             pgtype.Text
	ErrorMessage          pgtype.Text
	InternalErrorDetail   pgtype.Text
	DeliveryStatus        string
	ResponseStartedAt     pgtype.Timestamptz
	ResponseCompletedAt   pgtype.Timestamptz
	StartedAt             pgtype.Timestamptz
	CompletedAt           pgtype.Timestamptz
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
	RouteID               pgtype.Int8
	ReasoningEffort       pgtype.Text
	ReasoningBudgetTokens pgtype.Int4
	ClientIp              pgtype.Text
}

// MarkRequestSucceeded 将 running 请求原子推进到 succeeded，重复 succeeded 返回第一次成功事实。
// 重复 settlement 不能覆盖 response_model/provider/channel/completed_at。
// response_completed_at 属于交付状态机（仅在 delivery_status='completed' 时落地，见
// ck_request_records_delivery_completed_at），结算阶段不写，避免违反约束导致结算失败。
func (q *Queries) MarkRequestSucceeded(ctx context.Context, arg MarkRequestSucceededParams) (MarkRequestSucceededRow, error) {
	row := q.db.QueryRow(ctx, markRequestSucceeded,
		arg.ResponseModelID,
		arg.ResponseProtocol,
		arg.ResponseID,
		arg.FinalProviderID,
		arg.FinalChannelID,
		arg.ResponseStartedAt,
		arg.CompletedAt,
		arg.RequestRecordID,
	)
	var i MarkRequestSucceededRow
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.UserID,
		&i.ApiKeyID,
		&i.RequestedModelID,
		&i.IngressProtocol,
		&i.Operation,
		&i.ResponseModelID,
		&i.ResponseProtocol,
		&i.ResponseID,
		&i.Stream,
		&i.Status,
		&i.FinalProviderID,
		&i.FinalChannelID,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.InternalErrorDetail,
		&i.DeliveryStatus,
		&i.ResponseStartedAt,
		&i.ResponseCompletedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RouteID,
		&i.ReasoningEffort,
		&i.ReasoningBudgetTokens,
		&i.ClientIp,
	)
	return i, err
}

const markSettledRequestCanceled = `-- name: MarkSettledRequestCanceled :one
WITH updated AS (
    UPDATE request_records
        SET status = 'canceled',
            response_model_id = $1,
            response_protocol = $2,
            response_id = $3,
            final_provider_id = $4,
            final_channel_id = $5,
            error_code = $6,
            error_message = $7,
            internal_error_detail = $8,
            response_started_at = COALESCE(request_records.response_started_at, $9),
            completed_at = $10,
            updated_at = now()
        WHERE request_records.id = $11
            AND request_records.status = 'running'
        RETURNING request_records.id, request_records.request_id, request_records.user_id, request_records.api_key_id, request_records.requested_model_id, request_records.ingress_protocol, request_records.operation, request_records.response_model_id, request_records.response_protocol, request_records.response_id, request_records.stream, request_records.status, request_records.final_provider_id, request_records.final_channel_id, request_records.error_code, request_records.error_message, request_records.internal_error_detail, request_records.delivery_status, request_records.response_started_at, request_records.response_completed_at, request_records.started_at, request_records.completed_at, request_records.created_at, request_records.updated_at, request_records.route_id, request_records.reasoning_effort, request_records.reasoning_budget_tokens, request_records.client_ip
)
SELECT id, request_id, user_id, api_key_id, requested_model_id, ingress_protocol, operation, response_model_id, response_protocol, response_id, stream, status, final_provider_id, final_channel_id, error_code, error_message, internal_error_detail, delivery_status, response_started_at, response_completed_at, started_at, completed_at, created_at, updated_at, route_id, reasoning_effort, reasoning_budget_tokens, client_ip
FROM updated

UNION ALL

SELECT request_records.id, request_records.request_id, request_records.user_id, request_records.api_key_id, request_records.requested_model_id, request_records.ingress_protocol, request_records.operation, request_records.response_model_id, request_records.response_protocol, request_records.response_id, request_records.stream, request_records.status, request_records.final_provider_id, request_records.final_channel_id, request_records.error_code, request_records.error_message, request_records.internal_error_detail, request_records.delivery_status, request_records.response_started_at, request_records.response_completed_at, request_records.started_at, request_records.completed_at, request_records.created_at, request_records.updated_at, request_records.route_id, request_records.reasoning_effort, request_records.reasoning_budget_tokens, request_records.client_ip
FROM request_records
WHERE request_records.id = $11
  AND request_records.status = 'canceled'
  AND NOT EXISTS (SELECT 1 FROM updated)
`

type MarkSettledRequestCanceledParams struct {
	ResponseModelID     pgtype.Text
	ResponseProtocol    pgtype.Text
	ResponseID          pgtype.Text
	FinalProviderID     pgtype.Int8
	FinalChannelID      pgtype.Int8
	ErrorCode           pgtype.Text
	ErrorMessage        pgtype.Text
	InternalErrorDetail pgtype.Text
	ResponseStartedAt   pgtype.Timestamptz
	CompletedAt         pgtype.Timestamptz
	RequestRecordID     int64
}

type MarkSettledRequestCanceledRow struct {
	ID                    int64
	RequestID             string
	UserID                int64
	ApiKeyID              int64
	RequestedModelID      string
	IngressProtocol       string
	Operation             string
	ResponseModelID       pgtype.Text
	ResponseProtocol      pgtype.Text
	ResponseID            pgtype.Text
	Stream                bool
	Status                string
	FinalProviderID       pgtype.Int8
	FinalChannelID        pgtype.Int8
	ErrorCode             pgtype.Text
	ErrorMessage          pgtype.Text
	InternalErrorDetail   pgtype.Text
	DeliveryStatus        string
	ResponseStartedAt     pgtype.Timestamptz
	ResponseCompletedAt   pgtype.Timestamptz
	StartedAt             pgtype.Timestamptz
	CompletedAt           pgtype.Timestamptz
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
	RouteID               pgtype.Int8
	ReasoningEffort       pgtype.Text
	ReasoningBudgetTokens pgtype.Int4
	ClientIp              pgtype.Text
}

// MarkSettledRequestCanceled 将 running 请求推进到 canceled，但保留已结算响应事实（partial stream 客户端取消）。
// 与 MarkRequestCanceled 不同：该路径已经写入 usage/price/ledger，只是客户主动中断交付。
func (q *Queries) MarkSettledRequestCanceled(ctx context.Context, arg MarkSettledRequestCanceledParams) (MarkSettledRequestCanceledRow, error) {
	row := q.db.QueryRow(ctx, markSettledRequestCanceled,
		arg.ResponseModelID,
		arg.ResponseProtocol,
		arg.ResponseID,
		arg.FinalProviderID,
		arg.FinalChannelID,
		arg.ErrorCode,
		arg.ErrorMessage,
		arg.InternalErrorDetail,
		arg.ResponseStartedAt,
		arg.CompletedAt,
		arg.RequestRecordID,
	)
	var i MarkSettledRequestCanceledRow
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.UserID,
		&i.ApiKeyID,
		&i.RequestedModelID,
		&i.IngressProtocol,
		&i.Operation,
		&i.ResponseModelID,
		&i.ResponseProtocol,
		&i.ResponseID,
		&i.Stream,
		&i.Status,
		&i.FinalProviderID,
		&i.FinalChannelID,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.InternalErrorDetail,
		&i.DeliveryStatus,
		&i.ResponseStartedAt,
		&i.ResponseCompletedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RouteID,
		&i.ReasoningEffort,
		&i.ReasoningBudgetTokens,
		&i.ClientIp,
	)
	return i, err
}

const markSettledRequestFailed = `-- name: MarkSettledRequestFailed :one
WITH updated AS (
    UPDATE request_records
        SET status = 'failed',
            response_model_id = $1,
            response_protocol = $2,
            response_id = $3,
            final_provider_id = $4,
            final_channel_id = $5,
            error_code = $6,
            error_message = $7,
            internal_error_detail = $8,
            response_started_at = COALESCE(request_records.response_started_at, $9),
            completed_at = $10,
            updated_at = now()
        WHERE request_records.id = $11
            AND request_records.status = 'running'
        RETURNING request_records.id, request_records.request_id, request_records.user_id, request_records.api_key_id, request_records.requested_model_id, request_records.ingress_protocol, request_records.operation, request_records.response_model_id, request_records.response_protocol, request_records.response_id, request_records.stream, request_records.status, request_records.final_provider_id, request_records.final_channel_id, request_records.error_code, request_records.error_message, request_records.internal_error_detail, request_records.delivery_status, request_records.response_started_at, request_records.response_completed_at, request_records.started_at, request_records.completed_at, request_records.created_at, request_records.updated_at, request_records.route_id, request_records.reasoning_effort, request_records.reasoning_budget_tokens, request_records.client_ip
)
SELECT id, request_id, user_id, api_key_id, requested_model_id, ingress_protocol, operation, response_model_id, response_protocol, response_id, stream, status, final_provider_id, final_channel_id, error_code, error_message, internal_error_detail, delivery_status, response_started_at, response_completed_at, started_at, completed_at, created_at, updated_at, route_id, reasoning_effort, reasoning_budget_tokens, client_ip
FROM updated

UNION ALL

SELECT request_records.id, request_records.request_id, request_records.user_id, request_records.api_key_id, request_records.requested_model_id, request_records.ingress_protocol, request_records.operation, request_records.response_model_id, request_records.response_protocol, request_records.response_id, request_records.stream, request_records.status, request_records.final_provider_id, request_records.final_channel_id, request_records.error_code, request_records.error_message, request_records.internal_error_detail, request_records.delivery_status, request_records.response_started_at, request_records.response_completed_at, request_records.started_at, request_records.completed_at, request_records.created_at, request_records.updated_at, request_records.route_id, request_records.reasoning_effort, request_records.reasoning_budget_tokens, request_records.client_ip
FROM request_records
WHERE request_records.id = $11
  AND request_records.status = 'failed'
  AND NOT EXISTS (SELECT 1 FROM updated)
`

type MarkSettledRequestFailedParams struct {
	ResponseModelID     pgtype.Text
	ResponseProtocol    pgtype.Text
	ResponseID          pgtype.Text
	FinalProviderID     pgtype.Int8
	FinalChannelID      pgtype.Int8
	ErrorCode           pgtype.Text
	ErrorMessage        pgtype.Text
	InternalErrorDetail pgtype.Text
	ResponseStartedAt   pgtype.Timestamptz
	CompletedAt         pgtype.Timestamptz
	RequestRecordID     int64
}

type MarkSettledRequestFailedRow struct {
	ID                    int64
	RequestID             string
	UserID                int64
	ApiKeyID              int64
	RequestedModelID      string
	IngressProtocol       string
	Operation             string
	ResponseModelID       pgtype.Text
	ResponseProtocol      pgtype.Text
	ResponseID            pgtype.Text
	Stream                bool
	Status                string
	FinalProviderID       pgtype.Int8
	FinalChannelID        pgtype.Int8
	ErrorCode             pgtype.Text
	ErrorMessage          pgtype.Text
	InternalErrorDetail   pgtype.Text
	DeliveryStatus        string
	ResponseStartedAt     pgtype.Timestamptz
	ResponseCompletedAt   pgtype.Timestamptz
	StartedAt             pgtype.Timestamptz
	CompletedAt           pgtype.Timestamptz
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
	RouteID               pgtype.Int8
	ReasoningEffort       pgtype.Text
	ReasoningBudgetTokens pgtype.Int4
	ClientIp              pgtype.Text
}

// MarkSettledRequestFailed 将 running 请求推进到 failed，但保留已结算响应事实（partial stream 上游中断）。
func (q *Queries) MarkSettledRequestFailed(ctx context.Context, arg MarkSettledRequestFailedParams) (MarkSettledRequestFailedRow, error) {
	row := q.db.QueryRow(ctx, markSettledRequestFailed,
		arg.ResponseModelID,
		arg.ResponseProtocol,
		arg.ResponseID,
		arg.FinalProviderID,
		arg.FinalChannelID,
		arg.ErrorCode,
		arg.ErrorMessage,
		arg.InternalErrorDetail,
		arg.ResponseStartedAt,
		arg.CompletedAt,
		arg.RequestRecordID,
	)
	var i MarkSettledRequestFailedRow
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.UserID,
		&i.ApiKeyID,
		&i.RequestedModelID,
		&i.IngressProtocol,
		&i.Operation,
		&i.ResponseModelID,
		&i.ResponseProtocol,
		&i.ResponseID,
		&i.Stream,
		&i.Status,
		&i.FinalProviderID,
		&i.FinalChannelID,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.InternalErrorDetail,
		&i.DeliveryStatus,
		&i.ResponseStartedAt,
		&i.ResponseCompletedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RouteID,
		&i.ReasoningEffort,
		&i.ReasoningBudgetTokens,
		&i.ClientIp,
	)
	return i, err
}
