// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: route.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addRouteChannel = `-- name: AddRouteChannel :exec
INSERT INTO route_channels (route_id, channel_id)
VALUES ($1, $2)
ON CONFLICT (route_id, channel_id) DO NOTHING
`

type AddRouteChannelParams struct {
	RouteID   int64
	ChannelID int64
}

// AddRouteChannel 把一条渠道加入线路池；重复加入由主键幂等忽略。
func (q *Queries) AddRouteChannel(ctx context.Context, arg AddRouteChannelParams) error {
	_, err := q.db.Exec(ctx, addRouteChannel, arg.RouteID, arg.ChannelID)
	return err
}

const archiveRoute = `-- name: ArchiveRoute :execrows
UPDATE routes
SET status = 'archived', archived_at = now(), name = name || '__archived_' || id::text
WHERE routes.id = $1 AND routes.status <> 'archived'
`

// ArchiveRoute 归档线路（要求已无绑定 key，服务层护栏保证）：置 archived + 释放全局唯一线路名
// （追加 __archived_<id> 后缀）。route_channels 保留（线路已隐藏，便于恢复）。
func (q *Queries) ArchiveRoute(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, archiveRoute, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const archiveRouteWithKeyMigration = `-- name: ArchiveRouteWithKeyMigration :execrows
WITH migrated AS (
    UPDATE api_keys SET route_id = $2, updated_at = now()
    WHERE route_id = $1
)
UPDATE routes
SET status = 'archived', archived_at = now(), name = name || '__archived_' || id::text
WHERE routes.id = $1 AND routes.status <> 'archived'
`

type ArchiveRouteWithKeyMigrationParams struct {
	ID            int64
	TargetRouteID int64
}

// ArchiveRouteWithKeyMigration 单事务内先把源线路全部 api_key 迁到目标线路，再归档源线路
// （§4B 入口②「迁移并归档」）。目标线路有效性（存在且 enabled、非自身）由服务层先校验。
func (q *Queries) ArchiveRouteWithKeyMigration(ctx context.Context, arg ArchiveRouteWithKeyMigrationParams) (int64, error) {
	result, err := q.db.Exec(ctx, archiveRouteWithKeyMigration, arg.ID, arg.TargetRouteID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countApiKeysByRoute = `-- name: CountApiKeysByRoute :one
SELECT COUNT(*) AS total FROM api_keys WHERE route_id = $1
`

// CountApiKeysByRoute 统计绑定到某线路的 api_key 数量，供线路归档护栏（有 key 则拦截）。
func (q *Queries) CountApiKeysByRoute(ctx context.Context, routeID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countApiKeysByRoute, routeID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countRouteChannels = `-- name: CountRouteChannels :one
SELECT COUNT(*) FROM route_channels WHERE route_id = $1
`

func (q *Queries) CountRouteChannels(ctx context.Context, routeID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countRouteChannels, routeID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRoute = `-- name: CreateRoute :one
INSERT INTO routes (name, mode, status, description, price_ratio, rpm_limit, tpm_limit, rpd_limit, sticky_enabled)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9
)
RETURNING id, name, mode, status, description, created_at, updated_at, price_ratio, rpm_limit, tpm_limit, rpd_limit, archived_at, sticky_enabled
`

type CreateRouteParams struct {
	Name          string
	Mode          string
	Status        string
	Description   pgtype.Text
	PriceRatio    pgtype.Numeric
	RpmLimit      pgtype.Int4
	TpmLimit      pgtype.Int4
	RpdLimit      pgtype.Int4
	StickyEnabled pgtype.Bool
}

// CreateRoute 创建线路；price_ratio 是客户售价倍率（DEC-026：客户售价 = 模型基准价 × 倍率）；
// rpm/tpm/rpd_limit 是线路级限流上限（DEC-027：NULL=继承全局默认，0=不限，>0=上限）；
// sticky_enabled 是会话粘性开关（NULL=继承系统设置默认）；
// balanced/fixed 的渠道数量约束由 service 层校验。
func (q *Queries) CreateRoute(ctx context.Context, arg CreateRouteParams) (Route, error) {
	row := q.db.QueryRow(ctx, createRoute,
		arg.Name,
		arg.Mode,
		arg.Status,
		arg.Description,
		arg.PriceRatio,
		arg.RpmLimit,
		arg.TpmLimit,
		arg.RpdLimit,
		arg.StickyEnabled,
	)
	var i Route
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Mode,
		&i.Status,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PriceRatio,
		&i.RpmLimit,
		&i.TpmLimit,
		&i.RpdLimit,
		&i.ArchivedAt,
		&i.StickyEnabled,
	)
	return i, err
}

const deleteRoute = `-- name: DeleteRoute :execrows
DELETE FROM routes WHERE id = $1
`

// DeleteRoute 删除线路；被 api_keys/users 引用时由 DB 外键拒绝（23503）。
func (q *Queries) DeleteRoute(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRoute, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteRouteChannels = `-- name: DeleteRouteChannels :exec
DELETE FROM route_channels WHERE route_id = $1
`

// DeleteRouteChannels 清空某线路的渠道池（设置渠道池前先清空，整体在事务内重建）。
func (q *Queries) DeleteRouteChannels(ctx context.Context, routeID int64) error {
	_, err := q.db.Exec(ctx, deleteRouteChannels, routeID)
	return err
}

const listEmptyRoutesWithKeys = `-- name: ListEmptyRoutesWithKeys :many
SELECT rt.id, rt.name,
    (SELECT COUNT(*) FROM api_keys k WHERE k.route_id = rt.id) AS key_count
FROM routes rt
WHERE rt.status <> 'archived'
  AND NOT EXISTS (SELECT 1 FROM route_channels rc WHERE rc.route_id = rt.id)
  AND EXISTS (SELECT 1 FROM api_keys k WHERE k.route_id = rt.id)
ORDER BY rt.id
`

type ListEmptyRoutesWithKeysRow struct {
	ID       int64
	Name     string
	KeyCount int64
}

// ListEmptyRoutesWithKeys 列出「候选池为空但仍有绑定 key」的非归档线路，供归档后预警断供。
func (q *Queries) ListEmptyRoutesWithKeys(ctx context.Context) ([]ListEmptyRoutesWithKeysRow, error) {
	rows, err := q.db.Query(ctx, listEmptyRoutesWithKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEmptyRoutesWithKeysRow
	for rows.Next() {
		var i ListEmptyRoutesWithKeysRow
		if err := rows.Scan(&i.ID, &i.Name, &i.KeyCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRouteChannelsDetailed = `-- name: ListRouteChannelsDetailed :many
SELECT
    rc.channel_id,
    c.name AS channel_name,
    c.provider_id,
    p.slug AS provider_slug
FROM route_channels rc
JOIN channels c ON c.id = rc.channel_id
JOIN providers p ON p.id = c.provider_id
WHERE rc.route_id = $1
ORDER BY rc.channel_id
`

type ListRouteChannelsDetailedRow struct {
	ChannelID    int64
	ChannelName  string
	ProviderID   int64
	ProviderSlug string
}

// ListRouteChannelsDetailed 列出某线路渠道池，连带渠道展示名/provider，供 admin 管理台展示。
func (q *Queries) ListRouteChannelsDetailed(ctx context.Context, routeID int64) ([]ListRouteChannelsDetailedRow, error) {
	rows, err := q.db.Query(ctx, listRouteChannelsDetailed, routeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRouteChannelsDetailedRow
	for rows.Next() {
		var i ListRouteChannelsDetailedRow
		if err := rows.Scan(
			&i.ChannelID,
			&i.ChannelName,
			&i.ProviderID,
			&i.ProviderSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoutes = `-- name: ListRoutes :many
SELECT id, name, mode, status, description, created_at, updated_at, price_ratio, rpm_limit, tpm_limit, rpd_limit, archived_at, sticky_enabled FROM routes ORDER BY id ASC
`

// ListRoutes 列出全部线路，供 admin 管理台展示。
func (q *Queries) ListRoutes(ctx context.Context) ([]Route, error) {
	rows, err := q.db.Query(ctx, listRoutes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Route
	for rows.Next() {
		var i Route
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Mode,
			&i.Status,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PriceRatio,
			&i.RpmLimit,
			&i.TpmLimit,
			&i.RpdLimit,
			&i.ArchivedAt,
			&i.StickyEnabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreRoute = `-- name: RestoreRoute :execrows
UPDATE routes
SET status = 'disabled', archived_at = NULL
WHERE id = $1 AND status = 'archived'
`

// RestoreRoute 取消归档线路：archived → disabled（archived_at 清空）。route_channels 原样保留；
// 归档前已无 key，恢复后仍无 key，需手动绑定或迁入。
func (q *Queries) RestoreRoute(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, restoreRoute, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const routeOpsBoundKeys = `-- name: RouteOpsBoundKeys :many
SELECT k.id, k.name, k.user_id, k.disabled_at, k.revoked_at, k.expires_at
FROM api_keys k
WHERE k.route_id = $1
ORDER BY k.id
LIMIT 200
`

type RouteOpsBoundKeysRow struct {
	ID         int64
	Name       string
	UserID     int64
	DisabledAt pgtype.Timestamptz
	RevokedAt  pgtype.Timestamptz
	ExpiresAt  pgtype.Timestamptz
}

// RouteOpsBoundKeys 绑定本线路的 API Key（抽屉绑定 Tab，P0）。状态由时间戳派生。
func (q *Queries) RouteOpsBoundKeys(ctx context.Context, routeID int64) ([]RouteOpsBoundKeysRow, error) {
	rows, err := q.db.Query(ctx, routeOpsBoundKeys, routeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RouteOpsBoundKeysRow
	for rows.Next() {
		var i RouteOpsBoundKeysRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.UserID,
			&i.DisabledAt,
			&i.RevokedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const routeOpsBoundUsers = `-- name: RouteOpsBoundUsers :many
SELECT DISTINCT u.id, u.email, u.display_name
FROM users u
JOIN api_keys k ON k.user_id = u.id
WHERE k.route_id = $1
ORDER BY u.id
LIMIT 200
`

type RouteOpsBoundUsersRow struct {
	ID          int64
	Email       string
	DisplayName string
}

// RouteOpsBoundUsers 拥有「绑定本线路的 API Key」的用户（去重，抽屉绑定 Tab，P0）。
func (q *Queries) RouteOpsBoundUsers(ctx context.Context, routeID int64) ([]RouteOpsBoundUsersRow, error) {
	rows, err := q.db.Query(ctx, routeOpsBoundUsers, routeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RouteOpsBoundUsersRow
	for rows.Next() {
		var i RouteOpsBoundUsersRow
		if err := rows.Scan(&i.ID, &i.Email, &i.DisplayName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const routeOpsChannelPool = `-- name: RouteOpsChannelPool :many
SELECT
    c.id AS channel_id,
    c.name AS channel_name,
    c.status AS channel_status,
    c.priority,
    p.name AS provider_name
FROM route_channels rc
JOIN channels c ON c.id = rc.channel_id
JOIN providers p ON p.id = c.provider_id
WHERE rc.route_id = $1
ORDER BY c.priority, c.id
`

type RouteOpsChannelPoolRow struct {
	ChannelID     int64
	ChannelName   string
	ChannelStatus string
	Priority      int32
	ProviderName  string
}

// RouteOpsChannelPool 线路渠道池成员 + 渠道健康（抽屉渠道池 Tab）。
func (q *Queries) RouteOpsChannelPool(ctx context.Context, routeID int64) ([]RouteOpsChannelPoolRow, error) {
	rows, err := q.db.Query(ctx, routeOpsChannelPool, routeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RouteOpsChannelPoolRow
	for rows.Next() {
		var i RouteOpsChannelPoolRow
		if err := rows.Scan(
			&i.ChannelID,
			&i.ChannelName,
			&i.ChannelStatus,
			&i.Priority,
			&i.ProviderName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const routeOpsDetail = `-- name: RouteOpsDetail :one
WITH attributed AS (
    SELECT
        r.status,
        r.error_code,
        r.started_at,
        r.completed_at,
        (SELECT COUNT(*) FROM request_attempts a WHERE a.request_record_id = r.id) AS attempt_count
    FROM request_records r
    JOIN api_keys ak ON ak.id = r.api_key_id
    WHERE ak.route_id = $1
      AND ($2::timestamptz IS NULL OR r.created_at >= $2::timestamptz)
      AND ($3::timestamptz IS NULL OR r.created_at < $3::timestamptz)
)
SELECT
    COUNT(*) FILTER (WHERE status IN ('succeeded', 'failed')) AS request_total,
    COUNT(*) FILTER (WHERE status = 'succeeded') AS request_succeeded,
    COUNT(*) FILTER (WHERE status = 'succeeded' AND attempt_count > 1) AS fallback_total,
    COUNT(*) FILTER (WHERE error_code IN ('no_available_channel', 'routing_no_available_channel')) AS no_channel_total,
    COALESCE(percentile_cont(0.5) WITHIN GROUP (ORDER BY
        CASE WHEN status = 'succeeded' AND completed_at IS NOT NULL
             THEN (EXTRACT(EPOCH FROM (completed_at - started_at)) * 1000)::float8 END), 0)::float8 AS latency_p50,
    COALESCE(percentile_cont(0.95) WITHIN GROUP (ORDER BY
        CASE WHEN status = 'succeeded' AND completed_at IS NOT NULL
             THEN (EXTRACT(EPOCH FROM (completed_at - started_at)) * 1000)::float8 END), 0)::float8 AS latency_p95,
    (SELECT rt.status FROM routes rt WHERE rt.id = $1) AS route_status
FROM attributed
`

type RouteOpsDetailParams struct {
	RouteID  int64
	FromTime pgtype.Timestamptz
	ToTime   pgtype.Timestamptz
}

type RouteOpsDetailRow struct {
	RequestTotal     int64
	RequestSucceeded int64
	FallbackTotal    int64
	NoChannelTotal   int64
	LatencyP50       float64
	LatencyP95       float64
	RouteStatus      string
}

// RouteOpsDetail 单线路抽屉概览：归因请求指标 + fallback + 无可用渠道。
func (q *Queries) RouteOpsDetail(ctx context.Context, arg RouteOpsDetailParams) (RouteOpsDetailRow, error) {
	row := q.db.QueryRow(ctx, routeOpsDetail, arg.RouteID, arg.FromTime, arg.ToTime)
	var i RouteOpsDetailRow
	err := row.Scan(
		&i.RequestTotal,
		&i.RequestSucceeded,
		&i.FallbackTotal,
		&i.NoChannelTotal,
		&i.LatencyP50,
		&i.LatencyP95,
		&i.RouteStatus,
	)
	return i, err
}

const routeOpsModels = `-- name: RouteOpsModels :many
WITH attributed AS (
    SELECT r.requested_model_id, r.status
    FROM request_records r
    JOIN api_keys ak ON ak.id = r.api_key_id
    WHERE ak.route_id = $1
      AND ($2::timestamptz IS NULL OR r.created_at >= $2::timestamptz)
      AND ($3::timestamptz IS NULL OR r.created_at < $3::timestamptz)
)
SELECT
    requested_model_id AS model_id,
    COUNT(*) FILTER (WHERE status IN ('succeeded', 'failed')) AS request_total,
    COUNT(*) FILTER (WHERE status = 'succeeded') AS request_succeeded
FROM attributed
GROUP BY requested_model_id
ORDER BY request_total DESC
LIMIT 50
`

type RouteOpsModelsParams struct {
	RouteID  int64
	FromTime pgtype.Timestamptz
	ToTime   pgtype.Timestamptz
}

type RouteOpsModelsRow struct {
	ModelID          string
	RequestTotal     int64
	RequestSucceeded int64
}

// RouteOpsModels 本线路下各模型表现（抽屉模型 Tab，精简 §1.8）。
func (q *Queries) RouteOpsModels(ctx context.Context, arg RouteOpsModelsParams) ([]RouteOpsModelsRow, error) {
	rows, err := q.db.Query(ctx, routeOpsModels, arg.RouteID, arg.FromTime, arg.ToTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RouteOpsModelsRow
	for rows.Next() {
		var i RouteOpsModelsRow
		if err := rows.Scan(&i.ModelID, &i.RequestTotal, &i.RequestSucceeded); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const routeOpsPerformanceTimeseries = `-- name: RouteOpsPerformanceTimeseries :many
WITH attributed AS (
    SELECT r.created_at, r.status, r.started_at, r.completed_at
    FROM request_records r
    JOIN api_keys ak ON ak.id = r.api_key_id
    WHERE ak.route_id = $2
      AND ($3::timestamptz IS NULL OR r.created_at >= $3::timestamptz)
      AND ($4::timestamptz IS NULL OR r.created_at < $4::timestamptz)
)
SELECT
    date_trunc($1::text, created_at)::timestamptz AS bucket,
    COUNT(*) FILTER (WHERE status IN ('succeeded', 'failed')) AS request_total,
    COUNT(*) FILTER (WHERE status = 'succeeded') AS request_succeeded,
    COALESCE(percentile_cont(0.95) WITHIN GROUP (ORDER BY
        CASE WHEN status = 'succeeded' AND completed_at IS NOT NULL
             THEN (EXTRACT(EPOCH FROM (completed_at - started_at)) * 1000)::float8 END), 0)::float8 AS latency_p95
FROM attributed
GROUP BY bucket
ORDER BY bucket
`

type RouteOpsPerformanceTimeseriesParams struct {
	Unit     string
	RouteID  int64
	FromTime pgtype.Timestamptz
	ToTime   pgtype.Timestamptz
}

type RouteOpsPerformanceTimeseriesRow struct {
	Bucket           pgtype.Timestamptz
	RequestTotal     int64
	RequestSucceeded int64
	LatencyP95       float64
}

func (q *Queries) RouteOpsPerformanceTimeseries(ctx context.Context, arg RouteOpsPerformanceTimeseriesParams) ([]RouteOpsPerformanceTimeseriesRow, error) {
	rows, err := q.db.Query(ctx, routeOpsPerformanceTimeseries,
		arg.Unit,
		arg.RouteID,
		arg.FromTime,
		arg.ToTime,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RouteOpsPerformanceTimeseriesRow
	for rows.Next() {
		var i RouteOpsPerformanceTimeseriesRow
		if err := rows.Scan(
			&i.Bucket,
			&i.RequestTotal,
			&i.RequestSucceeded,
			&i.LatencyP95,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const routeOpsReachableModels = `-- name: RouteOpsReachableModels :many
SELECT
    m.model_id,
    m.display_name
FROM models m
JOIN channel_models cm ON cm.model_id = m.id AND cm.status = 'enabled'
JOIN channels c ON c.id = cm.channel_id AND c.status = 'enabled'
JOIN routes rt ON rt.id = $1
WHERE (
    EXISTS (
        SELECT 1 FROM channel_prices p
        WHERE p.channel_id = cm.channel_id AND p.model_id = cm.model_id AND p.status = 'enabled'
          AND p.effective_from <= now() AND (p.effective_to IS NULL OR p.effective_to > now())
    )
    OR (
        EXISTS (
            SELECT 1 FROM model_prices mp
            WHERE mp.model_id = cm.model_id AND mp.status = 'enabled'
              AND mp.effective_from <= now() AND (mp.effective_to IS NULL OR mp.effective_to > now())
        )
        AND EXISTS (
            SELECT 1 FROM channel_cost_multipliers ccm
            WHERE ccm.channel_id = cm.channel_id
              AND (ccm.model_id = cm.model_id OR ccm.model_id IS NULL)
              AND ccm.status = 'enabled'
              AND ccm.effective_from <= now() AND (ccm.effective_to IS NULL OR ccm.effective_to > now())
        )
    )
)
AND cm.channel_id IN (SELECT channel_id FROM route_channels WHERE route_id = rt.id)
GROUP BY m.id, m.model_id, m.display_name
ORDER BY m.model_id
LIMIT 500
`

type RouteOpsReachableModelsRow struct {
	ModelID     string
	DisplayName string
}

// RouteOpsReachableModels 线路可达模型（有启用绑定且可解析成本的 distinct 模型；DEC-031：绝对覆盖 OR 基准价+价格倍率）。
func (q *Queries) RouteOpsReachableModels(ctx context.Context, routeID int64) ([]RouteOpsReachableModelsRow, error) {
	rows, err := q.db.Query(ctx, routeOpsReachableModels, routeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RouteOpsReachableModelsRow
	for rows.Next() {
		var i RouteOpsReachableModelsRow
		if err := rows.Scan(&i.ModelID, &i.DisplayName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const routeOpsRequests = `-- name: RouteOpsRequests :many
SELECT
    r.request_id,
    r.created_at,
    r.status,
    r.requested_model_id,
    r.final_channel_id,
    CASE WHEN r.completed_at IS NOT NULL THEN (EXTRACT(EPOCH FROM (r.completed_at - r.started_at)) * 1000)::float8 END AS latency_ms
FROM request_records r
JOIN api_keys ak ON ak.id = r.api_key_id
WHERE ak.route_id = $1
  AND ($2::timestamptz IS NULL OR r.created_at >= $2::timestamptz)
  AND ($3::timestamptz IS NULL OR r.created_at < $3::timestamptz)
ORDER BY r.created_at DESC
LIMIT $5 OFFSET $4
`

type RouteOpsRequestsParams struct {
	RouteID    int64
	FromTime   pgtype.Timestamptz
	ToTime     pgtype.Timestamptz
	PageOffset int32
	PageLimit  int32
}

type RouteOpsRequestsRow struct {
	RequestID        string
	CreatedAt        pgtype.Timestamptz
	Status           string
	RequestedModelID string
	FinalChannelID   pgtype.Int8
	LatencyMs        interface{}
}

// RouteOpsRequests 本线路最近请求（抽屉请求 Tab，分页）。
func (q *Queries) RouteOpsRequests(ctx context.Context, arg RouteOpsRequestsParams) ([]RouteOpsRequestsRow, error) {
	rows, err := q.db.Query(ctx, routeOpsRequests,
		arg.RouteID,
		arg.FromTime,
		arg.ToTime,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RouteOpsRequestsRow
	for rows.Next() {
		var i RouteOpsRequestsRow
		if err := rows.Scan(
			&i.RequestID,
			&i.CreatedAt,
			&i.Status,
			&i.RequestedModelID,
			&i.FinalChannelID,
			&i.LatencyMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const routeOpsRequestsCount = `-- name: RouteOpsRequestsCount :one
SELECT COUNT(*) AS total
FROM request_records r
JOIN api_keys ak ON ak.id = r.api_key_id
WHERE ak.route_id = $1
  AND ($2::timestamptz IS NULL OR r.created_at >= $2::timestamptz)
  AND ($3::timestamptz IS NULL OR r.created_at < $3::timestamptz)
`

type RouteOpsRequestsCountParams struct {
	RouteID  int64
	FromTime pgtype.Timestamptz
	ToTime   pgtype.Timestamptz
}

func (q *Queries) RouteOpsRequestsCount(ctx context.Context, arg RouteOpsRequestsCountParams) (int64, error) {
	row := q.db.QueryRow(ctx, routeOpsRequestsCount, arg.RouteID, arg.FromTime, arg.ToTime)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const routeRuntimeChannelStats = `-- name: RouteRuntimeChannelStats :many
SELECT
    rc.channel_id,
    COUNT(DISTINCT rr.id) FILTER (
        WHERE rr.created_at >= $1::timestamptz - interval '1 minute'
          AND rr.final_channel_id = rc.channel_id
    )::bigint AS selected_1m,
    COUNT(DISTINCT rr.id) FILTER (
        WHERE rr.created_at >= $1::timestamptz - interval '5 minutes'
          AND rr.final_channel_id = rc.channel_id
    )::bigint AS selected_5m,
    COUNT(a.id) FILTER (
        WHERE a.created_at >= $1::timestamptz - interval '1 minute'
          AND a.channel_id = rc.channel_id
          AND a.attempt_index > 0
    )::bigint AS fallback_1m
FROM route_channels rc
LEFT JOIN request_records rr
  ON rr.route_id = rc.route_id
 AND rr.created_at >= $1::timestamptz - interval '5 minutes'
LEFT JOIN request_attempts a
  ON a.request_record_id = rr.id
 AND a.channel_id = rc.channel_id
WHERE rc.route_id = $2
GROUP BY rc.channel_id
ORDER BY rc.channel_id
`

type RouteRuntimeChannelStatsParams struct {
	ObservedAt pgtype.Timestamptz
	RouteID    int64
}

type RouteRuntimeChannelStatsRow struct {
	ChannelID  int64
	Selected1m int64
	Selected5m int64
	Fallback1m int64
}

// Recent final selections and fallback attempts for channels in one explicit route pool.
func (q *Queries) RouteRuntimeChannelStats(ctx context.Context, arg RouteRuntimeChannelStatsParams) ([]RouteRuntimeChannelStatsRow, error) {
	rows, err := q.db.Query(ctx, routeRuntimeChannelStats, arg.ObservedAt, arg.RouteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RouteRuntimeChannelStatsRow
	for rows.Next() {
		var i RouteRuntimeChannelStatsRow
		if err := rows.Scan(
			&i.ChannelID,
			&i.Selected1m,
			&i.Selected5m,
			&i.Fallback1m,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const routeRuntimePool = `-- name: RouteRuntimePool :many
SELECT
    rt.id AS route_id,
    rt.mode,
    rt.status AS route_status,
    c.id AS channel_id,
    c.name AS channel_name,
    c.status AS channel_status,
    c.credential_valid,
    (c.credential <> '')::boolean AS has_credential,
    (c.base_url <> '')::boolean AS has_base_url,
    c.protocol,
    c.adapter_key,
    c.priority,
    c.tpm_limit,
    c.concurrency_limit,
    p.id AS provider_id,
    p.name AS provider_name,
    p.status AS provider_status,
    (m.id IS NOT NULL)::boolean AS model_exists,
    COALESCE(m.status, '')::text AS model_status,
    COALESCE(cm.status, '')::text AS binding_status,
    (base.id IS NOT NULL)::boolean AS has_model_price,
    COALESCE((cost.id IS NOT NULL OR mult.id IS NOT NULL), false)::boolean AS has_channel_cost
FROM routes rt
JOIN route_channels rc ON rc.route_id = rt.id
JOIN channels c ON c.id = rc.channel_id
JOIN providers p ON p.id = c.provider_id
LEFT JOIN models m
  ON NULLIF($1::text, '') IS NOT NULL
 AND m.model_id = $1::text
LEFT JOIN channel_models cm ON cm.channel_id = c.id AND cm.model_id = m.id
LEFT JOIN LATERAL (
    SELECT mp.id
    FROM model_prices mp
    WHERE mp.model_id = m.id
      AND mp.status = 'enabled'
      AND mp.effective_from <= $2
      AND (mp.effective_to IS NULL OR mp.effective_to > $2)
    ORDER BY mp.effective_from DESC, mp.id DESC
    LIMIT 1
) base ON TRUE
LEFT JOIN LATERAL (
    SELECT cp.id
    FROM channel_prices cp
    WHERE cp.channel_id = c.id
      AND cp.model_id = m.id
      AND cp.status = 'enabled'
      AND cp.effective_from <= $2
      AND (cp.effective_to IS NULL OR cp.effective_to > $2)
    ORDER BY cp.effective_from DESC, cp.id DESC
    LIMIT 1
) cost ON TRUE
LEFT JOIN LATERAL (
    SELECT ccm.id
    FROM channel_cost_multipliers ccm
    WHERE ccm.channel_id = c.id
      AND (ccm.model_id = m.id OR ccm.model_id IS NULL)
      AND ccm.status = 'enabled'
      AND ccm.effective_from <= $2
      AND (ccm.effective_to IS NULL OR ccm.effective_to > $2)
    ORDER BY (ccm.model_id IS NULL) ASC, ccm.effective_from DESC, ccm.id DESC
    LIMIT 1
) mult ON TRUE
WHERE rt.id = $3
ORDER BY c.priority, c.id
`

type RouteRuntimePoolParams struct {
	ModelID string
	AtTime  pgtype.Timestamptz
	RouteID int64
}

type RouteRuntimePoolRow struct {
	RouteID          int64
	Mode             string
	RouteStatus      string
	ChannelID        int64
	ChannelName      string
	ChannelStatus    string
	CredentialValid  bool
	HasCredential    bool
	HasBaseUrl       bool
	Protocol         string
	AdapterKey       string
	Priority         int32
	TpmLimit         pgtype.Int4
	ConcurrencyLimit pgtype.Int4
	ProviderID       int64
	ProviderName     string
	ProviderStatus   string
	ModelExists      bool
	ModelStatus      string
	BindingStatus    string
	HasModelPrice    bool
	HasChannelCost   bool
}

// RouteRuntimePool returns every explicitly bound channel plus DB hard-filter facts.
func (q *Queries) RouteRuntimePool(ctx context.Context, arg RouteRuntimePoolParams) ([]RouteRuntimePoolRow, error) {
	rows, err := q.db.Query(ctx, routeRuntimePool, arg.ModelID, arg.AtTime, arg.RouteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RouteRuntimePoolRow
	for rows.Next() {
		var i RouteRuntimePoolRow
		if err := rows.Scan(
			&i.RouteID,
			&i.Mode,
			&i.RouteStatus,
			&i.ChannelID,
			&i.ChannelName,
			&i.ChannelStatus,
			&i.CredentialValid,
			&i.HasCredential,
			&i.HasBaseUrl,
			&i.Protocol,
			&i.AdapterKey,
			&i.Priority,
			&i.TpmLimit,
			&i.ConcurrencyLimit,
			&i.ProviderID,
			&i.ProviderName,
			&i.ProviderStatus,
			&i.ModelExists,
			&i.ModelStatus,
			&i.BindingStatus,
			&i.HasModelPrice,
			&i.HasChannelCost,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const routesOpsTable = `-- name: RoutesOpsTable :many

SELECT
    rt.id,
    rt.name,
    rt.mode,
    rt.status,
    rt.description,
    rt.price_ratio,
    rt.rpm_limit,
    rt.tpm_limit,
    rt.rpd_limit,
    rt.created_at,
    (SELECT COUNT(*) FROM api_keys kk WHERE kk.route_id = rt.id) AS bound_keys,
    (SELECT COUNT(*) FROM route_channels rc WHERE rc.route_id = rt.id) AS pool_channels,
    -- models_count（DEC-031）：池内可达且可解析成本的 distinct 模型（绝对覆盖 OR 基准价+价格倍率）。
    (
        SELECT COUNT(DISTINCT m.id)
        FROM models m
        JOIN channel_models cm ON cm.model_id = m.id AND cm.status = 'enabled'
        JOIN channels c ON c.id = cm.channel_id AND c.status = 'enabled'
        WHERE (
            EXISTS (
                SELECT 1 FROM channel_prices p
                WHERE p.channel_id = cm.channel_id AND p.model_id = cm.model_id AND p.status = 'enabled'
                  AND p.effective_from <= now() AND (p.effective_to IS NULL OR p.effective_to > now())
            )
            OR (
                EXISTS (
                    SELECT 1 FROM model_prices mp
                    WHERE mp.model_id = cm.model_id AND mp.status = 'enabled'
                      AND mp.effective_from <= now() AND (mp.effective_to IS NULL OR mp.effective_to > now())
                )
                AND EXISTS (
                    SELECT 1 FROM channel_cost_multipliers ccm
                    WHERE ccm.channel_id = cm.channel_id
                      AND (ccm.model_id = cm.model_id OR ccm.model_id IS NULL)
                      AND ccm.status = 'enabled'
                      AND ccm.effective_from <= now() AND (ccm.effective_to IS NULL OR ccm.effective_to > now())
                )
            )
        )
        AND cm.channel_id IN (SELECT channel_id FROM route_channels WHERE route_id = rt.id)
    ) AS models_count
FROM routes rt
WHERE ($1::text IS NULL OR rt.status = $1::text)
  AND ($2::text IS NULL OR rt.name ILIKE '%' || $2::text || '%')
ORDER BY
  CASE WHEN COALESCE($3::text, 'name') IN ('', 'name') AND COALESCE($4::bool, false) THEN rt.name END DESC NULLS LAST,
  CASE WHEN COALESCE($3::text, 'name') IN ('', 'name') AND NOT COALESCE($4::bool, false) THEN rt.name END ASC NULLS LAST,
  CASE WHEN $3::text = 'created_at' AND COALESCE($4::bool, false) THEN rt.created_at END DESC NULLS LAST,
  CASE WHEN $3::text = 'created_at' AND NOT COALESCE($4::bool, false) THEN rt.created_at END ASC NULLS LAST,
  CASE WHEN $3::text = 'bindings' AND COALESCE($4::bool, false) THEN (
        SELECT COUNT(*) FROM api_keys kk WHERE kk.route_id = rt.id
    ) END DESC NULLS LAST,
  CASE WHEN $3::text = 'bindings' AND NOT COALESCE($4::bool, false) THEN (
        SELECT COUNT(*) FROM api_keys kk WHERE kk.route_id = rt.id
    ) END ASC NULLS LAST,
  CASE WHEN $3::text = 'pool_channels' AND COALESCE($4::bool, false) THEN (
        SELECT COUNT(*) FROM route_channels rc WHERE rc.route_id = rt.id
    ) END DESC NULLS LAST,
  CASE WHEN $3::text = 'pool_channels' AND NOT COALESCE($4::bool, false) THEN (
        SELECT COUNT(*) FROM route_channels rc WHERE rc.route_id = rt.id
    ) END ASC NULLS LAST,
  CASE WHEN $3::text = 'models' AND COALESCE($4::bool, false) THEN (
        SELECT COUNT(DISTINCT m.id)
        FROM models m
        JOIN channel_models cm ON cm.model_id = m.id AND cm.status = 'enabled'
        JOIN channels c ON c.id = cm.channel_id AND c.status = 'enabled'
        WHERE (
            EXISTS (
                SELECT 1 FROM channel_prices p
                WHERE p.channel_id = cm.channel_id AND p.model_id = cm.model_id AND p.status = 'enabled'
                  AND p.effective_from <= now() AND (p.effective_to IS NULL OR p.effective_to > now())
            )
            OR (
                EXISTS (
                    SELECT 1 FROM model_prices mp
                    WHERE mp.model_id = cm.model_id AND mp.status = 'enabled'
                      AND mp.effective_from <= now() AND (mp.effective_to IS NULL OR mp.effective_to > now())
                )
                AND EXISTS (
                    SELECT 1 FROM channel_cost_multipliers ccm
                    WHERE ccm.channel_id = cm.channel_id
                      AND (ccm.model_id = cm.model_id OR ccm.model_id IS NULL)
                      AND ccm.status = 'enabled'
                      AND ccm.effective_from <= now() AND (ccm.effective_to IS NULL OR ccm.effective_to > now())
                )
            )
        )
        AND cm.channel_id IN (SELECT channel_id FROM route_channels WHERE route_id = rt.id)
    ) END DESC NULLS LAST,
  CASE WHEN $3::text = 'models' AND NOT COALESCE($4::bool, false) THEN (
        SELECT COUNT(DISTINCT m.id)
        FROM models m
        JOIN channel_models cm ON cm.model_id = m.id AND cm.status = 'enabled'
        JOIN channels c ON c.id = cm.channel_id AND c.status = 'enabled'
        WHERE (
            EXISTS (
                SELECT 1 FROM channel_prices p
                WHERE p.channel_id = cm.channel_id AND p.model_id = cm.model_id AND p.status = 'enabled'
                  AND p.effective_from <= now() AND (p.effective_to IS NULL OR p.effective_to > now())
            )
            OR (
                EXISTS (
                    SELECT 1 FROM model_prices mp
                    WHERE mp.model_id = cm.model_id AND mp.status = 'enabled'
                      AND mp.effective_from <= now() AND (mp.effective_to IS NULL OR mp.effective_to > now())
                )
                AND EXISTS (
                    SELECT 1 FROM channel_cost_multipliers ccm
                    WHERE ccm.channel_id = cm.channel_id
                      AND (ccm.model_id = cm.model_id OR ccm.model_id IS NULL)
                      AND ccm.status = 'enabled'
                      AND ccm.effective_from <= now() AND (ccm.effective_to IS NULL OR ccm.effective_to > now())
                )
            )
        )
        AND cm.channel_id IN (SELECT channel_id FROM route_channels WHERE route_id = rt.id)
    ) END ASC NULLS LAST,
  rt.name
LIMIT $6 OFFSET $5
`

type RoutesOpsTableParams struct {
	Status     pgtype.Text
	Search     pgtype.Text
	SortField  pgtype.Text
	SortDesc   pgtype.Bool
	PageOffset int32
	PageLimit  int32
}

type RoutesOpsTableRow struct {
	ID           int64
	Name         string
	Mode         string
	Status       string
	Description  pgtype.Text
	PriceRatio   pgtype.Numeric
	RpmLimit     pgtype.Int4
	TpmLimit     pgtype.Int4
	RpdLimit     pgtype.Int4
	CreatedAt    pgtype.Timestamptz
	BoundKeys    int64
	PoolChannels int64
	ModelsCount  int64
}

// §3.5 线路路由作战台只读运维聚合。
// 归因（线路必填 §3.1）：每条请求归属其 API Key 绑定的 api_keys.route_id（线路必填，无默认回落）。
// request 粒度。fallback：同 request 有 >1 次 attempt 且最终成功；no_channel：error_code 命中无可用渠道码。
// RoutesOpsTable 线路运维主表（分页）：静态配置 + 绑定/池/可达模型数；请求指标在详情页聚合。
func (q *Queries) RoutesOpsTable(ctx context.Context, arg RoutesOpsTableParams) ([]RoutesOpsTableRow, error) {
	rows, err := q.db.Query(ctx, routesOpsTable,
		arg.Status,
		arg.Search,
		arg.SortField,
		arg.SortDesc,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RoutesOpsTableRow
	for rows.Next() {
		var i RoutesOpsTableRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Mode,
			&i.Status,
			&i.Description,
			&i.PriceRatio,
			&i.RpmLimit,
			&i.TpmLimit,
			&i.RpdLimit,
			&i.CreatedAt,
			&i.BoundKeys,
			&i.PoolChannels,
			&i.ModelsCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const routesOpsTableCount = `-- name: RoutesOpsTableCount :one
SELECT COUNT(*) AS total
FROM routes rt
WHERE ($1::text IS NULL OR rt.status = $1::text)
  AND ($2::text IS NULL OR rt.name ILIKE '%' || $2::text || '%')
`

type RoutesOpsTableCountParams struct {
	Status pgtype.Text
	Search pgtype.Text
}

func (q *Queries) RoutesOpsTableCount(ctx context.Context, arg RoutesOpsTableCountParams) (int64, error) {
	row := q.db.QueryRow(ctx, routesOpsTableCount, arg.Status, arg.Search)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const updateRoute = `-- name: UpdateRoute :one
UPDATE routes
SET name = $1,
    mode = $2,
    status = $3,
    description = $4,
    price_ratio = $5,
    rpm_limit = $6,
    tpm_limit = $7,
    rpd_limit = $8,
    sticky_enabled = $9,
    updated_at = now()
WHERE id = $10
RETURNING id, name, mode, status, description, created_at, updated_at, price_ratio, rpm_limit, tpm_limit, rpd_limit, archived_at, sticky_enabled
`

type UpdateRouteParams struct {
	Name          string
	Mode          string
	Status        string
	Description   pgtype.Text
	PriceRatio    pgtype.Numeric
	RpmLimit      pgtype.Int4
	TpmLimit      pgtype.Int4
	RpdLimit      pgtype.Int4
	StickyEnabled pgtype.Bool
	ID            int64
}

// UpdateRoute 更新线路的名称/策略/启停/简介/售价倍率/线路级限流上限/会话粘性开关。
func (q *Queries) UpdateRoute(ctx context.Context, arg UpdateRouteParams) (Route, error) {
	row := q.db.QueryRow(ctx, updateRoute,
		arg.Name,
		arg.Mode,
		arg.Status,
		arg.Description,
		arg.PriceRatio,
		arg.RpmLimit,
		arg.TpmLimit,
		arg.RpdLimit,
		arg.StickyEnabled,
		arg.ID,
	)
	var i Route
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Mode,
		&i.Status,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PriceRatio,
		&i.RpmLimit,
		&i.TpmLimit,
		&i.RpdLimit,
		&i.ArchivedAt,
		&i.StickyEnabled,
	)
	return i, err
}
