// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: routing_traces.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countRouteRoutingDecisionTraces = `-- name: CountRouteRoutingDecisionTraces :one
SELECT COUNT(*) FROM routing_decision_traces WHERE route_id = $1
`

func (q *Queries) CountRouteRoutingDecisionTraces(ctx context.Context, routeID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countRouteRoutingDecisionTraces, routeID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteExpiredRoutingDecisionTraces = `-- name: DeleteExpiredRoutingDecisionTraces :execrows
DELETE FROM routing_decision_traces target
WHERE target.created_at < $1
  AND target.id IN (
      SELECT expired.id FROM routing_decision_traces expired
      WHERE expired.created_at < $1
      ORDER BY expired.created_at
      LIMIT $2
      FOR UPDATE SKIP LOCKED
  )
`

type DeleteExpiredRoutingDecisionTracesParams struct {
	Cutoff     pgtype.Timestamptz
	BatchLimit int32
}

func (q *Queries) DeleteExpiredRoutingDecisionTraces(ctx context.Context, arg DeleteExpiredRoutingDecisionTracesParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredRoutingDecisionTraces, arg.Cutoff, arg.BatchLimit)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getRoutingDecisionTraceByRequestID = `-- name: GetRoutingDecisionTraceByRequestID :one
SELECT t.id, t.request_record_id, t.route_id, t.mode, t.requested_model_id, t.protocol, t.endpoint, t.pool_size, t.candidate_count, t.sticky_channel_id, t.sticky_pinned, t.sticky_invalid, t.all_capacity_zero, t.margin_guard_triggered, t.abnormal, t.abnormal_reasons, t.candidate_scores, t.selected_order, t.fallback_chain, t.algorithm_version, t.sampled, t.created_at, t.updated_at, r.request_id, r.status AS request_status, r.final_channel_id
FROM routing_decision_traces t
JOIN request_records r ON r.id = t.request_record_id
WHERE r.request_id = $1
LIMIT 1
`

type GetRoutingDecisionTraceByRequestIDRow struct {
	ID                   int64
	RequestRecordID      int64
	RouteID              int64
	Mode                 string
	RequestedModelID     string
	Protocol             string
	Endpoint             string
	PoolSize             int32
	CandidateCount       int32
	StickyChannelID      pgtype.Int8
	StickyPinned         bool
	StickyInvalid        bool
	AllCapacityZero      bool
	MarginGuardTriggered bool
	Abnormal             bool
	AbnormalReasons      []string
	CandidateScores      []byte
	SelectedOrder        []int64
	FallbackChain        []byte
	AlgorithmVersion     string
	Sampled              bool
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
	RequestID            string
	RequestStatus        string
	FinalChannelID       pgtype.Int8
}

func (q *Queries) GetRoutingDecisionTraceByRequestID(ctx context.Context, requestID string) (GetRoutingDecisionTraceByRequestIDRow, error) {
	row := q.db.QueryRow(ctx, getRoutingDecisionTraceByRequestID, requestID)
	var i GetRoutingDecisionTraceByRequestIDRow
	err := row.Scan(
		&i.ID,
		&i.RequestRecordID,
		&i.RouteID,
		&i.Mode,
		&i.RequestedModelID,
		&i.Protocol,
		&i.Endpoint,
		&i.PoolSize,
		&i.CandidateCount,
		&i.StickyChannelID,
		&i.StickyPinned,
		&i.StickyInvalid,
		&i.AllCapacityZero,
		&i.MarginGuardTriggered,
		&i.Abnormal,
		&i.AbnormalReasons,
		&i.CandidateScores,
		&i.SelectedOrder,
		&i.FallbackChain,
		&i.AlgorithmVersion,
		&i.Sampled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RequestID,
		&i.RequestStatus,
		&i.FinalChannelID,
	)
	return i, err
}

const listRouteRoutingDecisionTraces = `-- name: ListRouteRoutingDecisionTraces :many
SELECT t.id, t.request_record_id, t.route_id, t.mode, t.requested_model_id, t.protocol, t.endpoint, t.pool_size, t.candidate_count, t.sticky_channel_id, t.sticky_pinned, t.sticky_invalid, t.all_capacity_zero, t.margin_guard_triggered, t.abnormal, t.abnormal_reasons, t.candidate_scores, t.selected_order, t.fallback_chain, t.algorithm_version, t.sampled, t.created_at, t.updated_at, r.request_id, r.status AS request_status, r.final_channel_id
FROM routing_decision_traces t
JOIN request_records r ON r.id = t.request_record_id
WHERE t.route_id = $1
ORDER BY t.created_at DESC
LIMIT $3 OFFSET $2
`

type ListRouteRoutingDecisionTracesParams struct {
	RouteID    int64
	PageOffset int32
	PageLimit  int32
}

type ListRouteRoutingDecisionTracesRow struct {
	ID                   int64
	RequestRecordID      int64
	RouteID              int64
	Mode                 string
	RequestedModelID     string
	Protocol             string
	Endpoint             string
	PoolSize             int32
	CandidateCount       int32
	StickyChannelID      pgtype.Int8
	StickyPinned         bool
	StickyInvalid        bool
	AllCapacityZero      bool
	MarginGuardTriggered bool
	Abnormal             bool
	AbnormalReasons      []string
	CandidateScores      []byte
	SelectedOrder        []int64
	FallbackChain        []byte
	AlgorithmVersion     string
	Sampled              bool
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
	RequestID            string
	RequestStatus        string
	FinalChannelID       pgtype.Int8
}

func (q *Queries) ListRouteRoutingDecisionTraces(ctx context.Context, arg ListRouteRoutingDecisionTracesParams) ([]ListRouteRoutingDecisionTracesRow, error) {
	rows, err := q.db.Query(ctx, listRouteRoutingDecisionTraces, arg.RouteID, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRouteRoutingDecisionTracesRow
	for rows.Next() {
		var i ListRouteRoutingDecisionTracesRow
		if err := rows.Scan(
			&i.ID,
			&i.RequestRecordID,
			&i.RouteID,
			&i.Mode,
			&i.RequestedModelID,
			&i.Protocol,
			&i.Endpoint,
			&i.PoolSize,
			&i.CandidateCount,
			&i.StickyChannelID,
			&i.StickyPinned,
			&i.StickyInvalid,
			&i.AllCapacityZero,
			&i.MarginGuardTriggered,
			&i.Abnormal,
			&i.AbnormalReasons,
			&i.CandidateScores,
			&i.SelectedOrder,
			&i.FallbackChain,
			&i.AlgorithmVersion,
			&i.Sampled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RequestID,
			&i.RequestStatus,
			&i.FinalChannelID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertRoutingDecisionTrace = `-- name: UpsertRoutingDecisionTrace :exec
INSERT INTO routing_decision_traces (
    request_record_id, route_id, mode, requested_model_id, protocol, endpoint,
    pool_size, candidate_count, sticky_channel_id, sticky_pinned, sticky_invalid,
    all_capacity_zero, margin_guard_triggered, abnormal,
    abnormal_reasons, candidate_scores, selected_order, fallback_chain,
    algorithm_version, sampled
) VALUES (
    $1, $2, $3,
    $4, $5, $6,
    $7, $8, $9,
    $10, $11, $12,
    $13, $14,
    $15, $16, $17,
    $18, $19, $20
)
ON CONFLICT (request_record_id) DO UPDATE SET
    pool_size = EXCLUDED.pool_size,
    candidate_count = EXCLUDED.candidate_count,
    sticky_channel_id = EXCLUDED.sticky_channel_id,
    sticky_pinned = EXCLUDED.sticky_pinned,
    sticky_invalid = EXCLUDED.sticky_invalid,
    all_capacity_zero = EXCLUDED.all_capacity_zero,
    margin_guard_triggered = EXCLUDED.margin_guard_triggered,
    abnormal = routing_decision_traces.abnormal OR EXCLUDED.abnormal,
    abnormal_reasons = ARRAY(SELECT DISTINCT unnest(routing_decision_traces.abnormal_reasons || EXCLUDED.abnormal_reasons)),
    candidate_scores = EXCLUDED.candidate_scores,
    selected_order = EXCLUDED.selected_order,
    fallback_chain = EXCLUDED.fallback_chain,
    sampled = routing_decision_traces.sampled OR EXCLUDED.sampled,
    updated_at = now()
`

type UpsertRoutingDecisionTraceParams struct {
	RequestRecordID      int64
	RouteID              int64
	Mode                 string
	RequestedModelID     string
	Protocol             string
	Endpoint             string
	PoolSize             int32
	CandidateCount       int32
	StickyChannelID      pgtype.Int8
	StickyPinned         bool
	StickyInvalid        bool
	AllCapacityZero      bool
	MarginGuardTriggered bool
	Abnormal             bool
	AbnormalReasons      []string
	CandidateScores      []byte
	SelectedOrder        []int64
	FallbackChain        []byte
	AlgorithmVersion     string
	Sampled              bool
}

func (q *Queries) UpsertRoutingDecisionTrace(ctx context.Context, arg UpsertRoutingDecisionTraceParams) error {
	_, err := q.db.Exec(ctx, upsertRoutingDecisionTrace,
		arg.RequestRecordID,
		arg.RouteID,
		arg.Mode,
		arg.RequestedModelID,
		arg.Protocol,
		arg.Endpoint,
		arg.PoolSize,
		arg.CandidateCount,
		arg.StickyChannelID,
		arg.StickyPinned,
		arg.StickyInvalid,
		arg.AllCapacityZero,
		arg.MarginGuardTriggered,
		arg.Abnormal,
		arg.AbnormalReasons,
		arg.CandidateScores,
		arg.SelectedOrder,
		arg.FallbackChain,
		arg.AlgorithmVersion,
		arg.Sampled,
	)
	return err
}
