// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: settlement_recovery_jobs.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimNextSettlementRecoveryJob = `-- name: ClaimNextSettlementRecoveryJob :one
WITH candidate AS (
    SELECT id
    FROM settlement_recovery_jobs
    WHERE settlement_recovery_jobs.attempt_count < settlement_recovery_jobs.max_attempts
      AND (
          (
              settlement_recovery_jobs.status = 'pending'
                  AND settlement_recovery_jobs.next_run_at <= $3
              )
              OR
          (
              settlement_recovery_jobs.status = 'running'
                  AND settlement_recovery_jobs.locked_until <= $3
              )
      )
    ORDER BY settlement_recovery_jobs.next_run_at ASC, settlement_recovery_jobs.id ASC
        FOR UPDATE SKIP LOCKED
    LIMIT 1
)
UPDATE settlement_recovery_jobs
SET
    status = 'running',
    attempt_count = attempt_count + 1,
    locked_by = $1,
    locked_until = $2,
    last_attempted_at = $3,
    updated_at = $3
WHERE settlement_recovery_jobs.id = (SELECT candidate.id FROM candidate)
RETURNING id, user_id, request_record_id, attempt_id, reservation_id, response_model_id, model_id, provider_id, channel_id, upstream_response_model, upstream_status_code, upstream_request_id, usage_prompt_tokens, usage_completion_tokens, usage_total_tokens, usage_cached_tokens, usage_reasoning_tokens, usage_source, price_id, currency, pricing_unit, input_price, output_price, cached_input_price, reasoning_output_price, formula_version, estimated_amount, authorized_amount, status, attempt_count, max_attempts, next_run_at, locked_by, locked_until, last_error_code, last_error_message, last_internal_error_detail, last_attempted_at, completed_at, created_at, updated_at
`

type ClaimNextSettlementRecoveryJobParams struct {
	LockedBy    pgtype.Text
	LockedUntil pgtype.Timestamptz
	NowAt       pgtype.Timestamptz
}

// ClaimNextSettlementRecoveryJob claim 一条到期 pending 或锁过期 running 的 recovery job。
func (q *Queries) ClaimNextSettlementRecoveryJob(ctx context.Context, arg ClaimNextSettlementRecoveryJobParams) (SettlementRecoveryJob, error) {
	row := q.db.QueryRow(ctx, claimNextSettlementRecoveryJob, arg.LockedBy, arg.LockedUntil, arg.NowAt)
	var i SettlementRecoveryJob
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RequestRecordID,
		&i.AttemptID,
		&i.ReservationID,
		&i.ResponseModelID,
		&i.ModelID,
		&i.ProviderID,
		&i.ChannelID,
		&i.UpstreamResponseModel,
		&i.UpstreamStatusCode,
		&i.UpstreamRequestID,
		&i.UsagePromptTokens,
		&i.UsageCompletionTokens,
		&i.UsageTotalTokens,
		&i.UsageCachedTokens,
		&i.UsageReasoningTokens,
		&i.UsageSource,
		&i.PriceID,
		&i.Currency,
		&i.PricingUnit,
		&i.InputPrice,
		&i.OutputPrice,
		&i.CachedInputPrice,
		&i.ReasoningOutputPrice,
		&i.FormulaVersion,
		&i.EstimatedAmount,
		&i.AuthorizedAmount,
		&i.Status,
		&i.AttemptCount,
		&i.MaxAttempts,
		&i.NextRunAt,
		&i.LockedBy,
		&i.LockedUntil,
		&i.LastErrorCode,
		&i.LastErrorMessage,
		&i.LastInternalErrorDetail,
		&i.LastAttemptedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSettlementRecoveryJob = `-- name: CreateSettlementRecoveryJob :one
INSERT INTO settlement_recovery_jobs (
    user_id,
    request_record_id,
    attempt_id,
    reservation_id,
    response_model_id,
    model_id,
    provider_id,
    channel_id,
    upstream_response_model,
    upstream_status_code,
    upstream_request_id,
    usage_prompt_tokens,
    usage_completion_tokens,
    usage_total_tokens,
    usage_cached_tokens,
    usage_reasoning_tokens,
    usage_source,
    price_id,
    currency,
    pricing_unit,
    input_price,
    output_price,
    cached_input_price,
    reasoning_output_price,
    formula_version,
    estimated_amount,
    authorized_amount,
    status,
    next_run_at
)
VALUES (
           $1,
           $2,
           $3,
           $4,
           $5,
           $6,
           $7,
           $8,
           $9,
           $10,
           $11,
           $12,
           $13,
           $14,
           $15,
           $16,
           $17,
           $18,
           $19,
           $20,
           $21,
           $22,
           $23,
           $24,
           $25,
           $26,
           $27,
           'pending',
           $28
       )
ON CONFLICT (request_record_id) DO UPDATE
SET updated_at = settlement_recovery_jobs.updated_at
WHERE settlement_recovery_jobs.user_id = EXCLUDED.user_id
  AND settlement_recovery_jobs.attempt_id = EXCLUDED.attempt_id
  AND settlement_recovery_jobs.reservation_id = EXCLUDED.reservation_id
  AND settlement_recovery_jobs.response_model_id = EXCLUDED.response_model_id
  AND settlement_recovery_jobs.model_id = EXCLUDED.model_id
  AND settlement_recovery_jobs.provider_id = EXCLUDED.provider_id
  AND settlement_recovery_jobs.channel_id = EXCLUDED.channel_id
  AND settlement_recovery_jobs.upstream_response_model = EXCLUDED.upstream_response_model
  AND settlement_recovery_jobs.upstream_status_code = EXCLUDED.upstream_status_code
  AND settlement_recovery_jobs.upstream_request_id IS NOT DISTINCT FROM EXCLUDED.upstream_request_id
  AND settlement_recovery_jobs.usage_prompt_tokens = EXCLUDED.usage_prompt_tokens
  AND settlement_recovery_jobs.usage_completion_tokens = EXCLUDED.usage_completion_tokens
  AND settlement_recovery_jobs.usage_total_tokens = EXCLUDED.usage_total_tokens
  AND settlement_recovery_jobs.usage_cached_tokens = EXCLUDED.usage_cached_tokens
  AND settlement_recovery_jobs.usage_reasoning_tokens = EXCLUDED.usage_reasoning_tokens
  AND settlement_recovery_jobs.usage_source = EXCLUDED.usage_source
  AND settlement_recovery_jobs.price_id = EXCLUDED.price_id
  AND settlement_recovery_jobs.currency = EXCLUDED.currency
  AND settlement_recovery_jobs.pricing_unit = EXCLUDED.pricing_unit
  AND settlement_recovery_jobs.input_price = EXCLUDED.input_price
  AND settlement_recovery_jobs.output_price = EXCLUDED.output_price
  AND settlement_recovery_jobs.cached_input_price IS NOT DISTINCT FROM EXCLUDED.cached_input_price
  AND settlement_recovery_jobs.reasoning_output_price IS NOT DISTINCT FROM EXCLUDED.reasoning_output_price
  AND settlement_recovery_jobs.formula_version = EXCLUDED.formula_version
  AND settlement_recovery_jobs.estimated_amount = EXCLUDED.estimated_amount
  AND settlement_recovery_jobs.authorized_amount = EXCLUDED.authorized_amount
RETURNING id, user_id, request_record_id, attempt_id, reservation_id, response_model_id, model_id, provider_id, channel_id, upstream_response_model, upstream_status_code, upstream_request_id, usage_prompt_tokens, usage_completion_tokens, usage_total_tokens, usage_cached_tokens, usage_reasoning_tokens, usage_source, price_id, currency, pricing_unit, input_price, output_price, cached_input_price, reasoning_output_price, formula_version, estimated_amount, authorized_amount, status, attempt_count, max_attempts, next_run_at, locked_by, locked_until, last_error_code, last_error_message, last_internal_error_detail, last_attempted_at, completed_at, created_at, updated_at
`

type CreateSettlementRecoveryJobParams struct {
	UserID                int64
	RequestRecordID       int64
	AttemptID             int64
	ReservationID         int64
	ResponseModelID       string
	ModelID               int64
	ProviderID            int64
	ChannelID             int64
	UpstreamResponseModel string
	UpstreamStatusCode    int32
	UpstreamRequestID     pgtype.Text
	UsagePromptTokens     int64
	UsageCompletionTokens int64
	UsageTotalTokens      int64
	UsageCachedTokens     int64
	UsageReasoningTokens  int64
	UsageSource           string
	PriceID               int64
	Currency              string
	PricingUnit           string
	InputPrice            pgtype.Numeric
	OutputPrice           pgtype.Numeric
	CachedInputPrice      pgtype.Numeric
	ReasoningOutputPrice  pgtype.Numeric
	FormulaVersion        string
	EstimatedAmount       pgtype.Numeric
	AuthorizedAmount      pgtype.Numeric
	NextRunAt             pgtype.Timestamptz
}

// CreateSettlementRecoveryJob 创建或读取一次请求的 settlement recovery job。
func (q *Queries) CreateSettlementRecoveryJob(ctx context.Context, arg CreateSettlementRecoveryJobParams) (SettlementRecoveryJob, error) {
	row := q.db.QueryRow(ctx, createSettlementRecoveryJob,
		arg.UserID,
		arg.RequestRecordID,
		arg.AttemptID,
		arg.ReservationID,
		arg.ResponseModelID,
		arg.ModelID,
		arg.ProviderID,
		arg.ChannelID,
		arg.UpstreamResponseModel,
		arg.UpstreamStatusCode,
		arg.UpstreamRequestID,
		arg.UsagePromptTokens,
		arg.UsageCompletionTokens,
		arg.UsageTotalTokens,
		arg.UsageCachedTokens,
		arg.UsageReasoningTokens,
		arg.UsageSource,
		arg.PriceID,
		arg.Currency,
		arg.PricingUnit,
		arg.InputPrice,
		arg.OutputPrice,
		arg.CachedInputPrice,
		arg.ReasoningOutputPrice,
		arg.FormulaVersion,
		arg.EstimatedAmount,
		arg.AuthorizedAmount,
		arg.NextRunAt,
	)
	var i SettlementRecoveryJob
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RequestRecordID,
		&i.AttemptID,
		&i.ReservationID,
		&i.ResponseModelID,
		&i.ModelID,
		&i.ProviderID,
		&i.ChannelID,
		&i.UpstreamResponseModel,
		&i.UpstreamStatusCode,
		&i.UpstreamRequestID,
		&i.UsagePromptTokens,
		&i.UsageCompletionTokens,
		&i.UsageTotalTokens,
		&i.UsageCachedTokens,
		&i.UsageReasoningTokens,
		&i.UsageSource,
		&i.PriceID,
		&i.Currency,
		&i.PricingUnit,
		&i.InputPrice,
		&i.OutputPrice,
		&i.CachedInputPrice,
		&i.ReasoningOutputPrice,
		&i.FormulaVersion,
		&i.EstimatedAmount,
		&i.AuthorizedAmount,
		&i.Status,
		&i.AttemptCount,
		&i.MaxAttempts,
		&i.NextRunAt,
		&i.LockedBy,
		&i.LockedUntil,
		&i.LastErrorCode,
		&i.LastErrorMessage,
		&i.LastInternalErrorDetail,
		&i.LastAttemptedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSettlementRecoveryJobByRequest = `-- name: GetSettlementRecoveryJobByRequest :one
SELECT id, user_id, request_record_id, attempt_id, reservation_id, response_model_id, model_id, provider_id, channel_id, upstream_response_model, upstream_status_code, upstream_request_id, usage_prompt_tokens, usage_completion_tokens, usage_total_tokens, usage_cached_tokens, usage_reasoning_tokens, usage_source, price_id, currency, pricing_unit, input_price, output_price, cached_input_price, reasoning_output_price, formula_version, estimated_amount, authorized_amount, status, attempt_count, max_attempts, next_run_at, locked_by, locked_until, last_error_code, last_error_message, last_internal_error_detail, last_attempted_at, completed_at, created_at, updated_at
FROM settlement_recovery_jobs
WHERE request_record_id = $1
`

// GetSettlementRecoveryJobByRequest 按请求 ID 读取 settlement recovery job。
func (q *Queries) GetSettlementRecoveryJobByRequest(ctx context.Context, requestRecordID int64) (SettlementRecoveryJob, error) {
	row := q.db.QueryRow(ctx, getSettlementRecoveryJobByRequest, requestRecordID)
	var i SettlementRecoveryJob
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RequestRecordID,
		&i.AttemptID,
		&i.ReservationID,
		&i.ResponseModelID,
		&i.ModelID,
		&i.ProviderID,
		&i.ChannelID,
		&i.UpstreamResponseModel,
		&i.UpstreamStatusCode,
		&i.UpstreamRequestID,
		&i.UsagePromptTokens,
		&i.UsageCompletionTokens,
		&i.UsageTotalTokens,
		&i.UsageCachedTokens,
		&i.UsageReasoningTokens,
		&i.UsageSource,
		&i.PriceID,
		&i.Currency,
		&i.PricingUnit,
		&i.InputPrice,
		&i.OutputPrice,
		&i.CachedInputPrice,
		&i.ReasoningOutputPrice,
		&i.FormulaVersion,
		&i.EstimatedAmount,
		&i.AuthorizedAmount,
		&i.Status,
		&i.AttemptCount,
		&i.MaxAttempts,
		&i.NextRunAt,
		&i.LockedBy,
		&i.LockedUntil,
		&i.LastErrorCode,
		&i.LastErrorMessage,
		&i.LastInternalErrorDetail,
		&i.LastAttemptedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markExhaustedSettlementRecoveryJobDead = `-- name: MarkExhaustedSettlementRecoveryJobDead :one
WITH candidate AS (
    SELECT id
    FROM settlement_recovery_jobs
    WHERE settlement_recovery_jobs.attempt_count >= settlement_recovery_jobs.max_attempts
      AND (
          (
              settlement_recovery_jobs.status = 'pending'
                  AND settlement_recovery_jobs.next_run_at <= $5
              )
              OR
          (
              settlement_recovery_jobs.status = 'running'
                  AND settlement_recovery_jobs.locked_until <= $5
              )
      )
    ORDER BY settlement_recovery_jobs.next_run_at ASC, settlement_recovery_jobs.id ASC
        FOR UPDATE SKIP LOCKED
    LIMIT 1
)
UPDATE settlement_recovery_jobs
SET
    status = 'dead',
    locked_by = NULL,
    locked_until = NULL,
    last_error_code = $1,
    last_error_message = $2,
    last_internal_error_detail = $3,
    completed_at = $4,
    updated_at = $4
WHERE settlement_recovery_jobs.id = (SELECT candidate.id FROM candidate)
RETURNING id, user_id, request_record_id, attempt_id, reservation_id, response_model_id, model_id, provider_id, channel_id, upstream_response_model, upstream_status_code, upstream_request_id, usage_prompt_tokens, usage_completion_tokens, usage_total_tokens, usage_cached_tokens, usage_reasoning_tokens, usage_source, price_id, currency, pricing_unit, input_price, output_price, cached_input_price, reasoning_output_price, formula_version, estimated_amount, authorized_amount, status, attempt_count, max_attempts, next_run_at, locked_by, locked_until, last_error_code, last_error_message, last_internal_error_detail, last_attempted_at, completed_at, created_at, updated_at
`

type MarkExhaustedSettlementRecoveryJobDeadParams struct {
	LastErrorCode           pgtype.Text
	LastErrorMessage        pgtype.Text
	LastInternalErrorDetail pgtype.Text
	CompletedAt             pgtype.Timestamptz
	NowAt                   pgtype.Timestamptz
}

// MarkExhaustedSettlementRecoveryJobDead 将到期且已耗尽自动尝试次数的 recovery job 标记为 dead。
func (q *Queries) MarkExhaustedSettlementRecoveryJobDead(ctx context.Context, arg MarkExhaustedSettlementRecoveryJobDeadParams) (SettlementRecoveryJob, error) {
	row := q.db.QueryRow(ctx, markExhaustedSettlementRecoveryJobDead,
		arg.LastErrorCode,
		arg.LastErrorMessage,
		arg.LastInternalErrorDetail,
		arg.CompletedAt,
		arg.NowAt,
	)
	var i SettlementRecoveryJob
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RequestRecordID,
		&i.AttemptID,
		&i.ReservationID,
		&i.ResponseModelID,
		&i.ModelID,
		&i.ProviderID,
		&i.ChannelID,
		&i.UpstreamResponseModel,
		&i.UpstreamStatusCode,
		&i.UpstreamRequestID,
		&i.UsagePromptTokens,
		&i.UsageCompletionTokens,
		&i.UsageTotalTokens,
		&i.UsageCachedTokens,
		&i.UsageReasoningTokens,
		&i.UsageSource,
		&i.PriceID,
		&i.Currency,
		&i.PricingUnit,
		&i.InputPrice,
		&i.OutputPrice,
		&i.CachedInputPrice,
		&i.ReasoningOutputPrice,
		&i.FormulaVersion,
		&i.EstimatedAmount,
		&i.AuthorizedAmount,
		&i.Status,
		&i.AttemptCount,
		&i.MaxAttempts,
		&i.NextRunAt,
		&i.LockedBy,
		&i.LockedUntil,
		&i.LastErrorCode,
		&i.LastErrorMessage,
		&i.LastInternalErrorDetail,
		&i.LastAttemptedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markSettlementRecoveryJobDead = `-- name: MarkSettlementRecoveryJobDead :one
UPDATE settlement_recovery_jobs
SET
    status = 'dead',
    locked_by = NULL,
    locked_until = NULL,
    last_error_code = $1,
    last_error_message = $2,
    last_internal_error_detail = $3,
    completed_at = $4,
    updated_at = $4
WHERE settlement_recovery_jobs.id = $5
  AND settlement_recovery_jobs.status = 'running'
  AND settlement_recovery_jobs.locked_by = $6
  AND settlement_recovery_jobs.locked_until = $7
  AND settlement_recovery_jobs.attempt_count = $8
RETURNING id, user_id, request_record_id, attempt_id, reservation_id, response_model_id, model_id, provider_id, channel_id, upstream_response_model, upstream_status_code, upstream_request_id, usage_prompt_tokens, usage_completion_tokens, usage_total_tokens, usage_cached_tokens, usage_reasoning_tokens, usage_source, price_id, currency, pricing_unit, input_price, output_price, cached_input_price, reasoning_output_price, formula_version, estimated_amount, authorized_amount, status, attempt_count, max_attempts, next_run_at, locked_by, locked_until, last_error_code, last_error_message, last_internal_error_detail, last_attempted_at, completed_at, created_at, updated_at
`

type MarkSettlementRecoveryJobDeadParams struct {
	LastErrorCode           pgtype.Text
	LastErrorMessage        pgtype.Text
	LastInternalErrorDetail pgtype.Text
	CompletedAt             pgtype.Timestamptz
	ID                      int64
	LockedBy                pgtype.Text
	LockedUntil             pgtype.Timestamptz
	AttemptCount            int32
}

// MarkSettlementRecoveryJobDead 将 running recovery job 标记为 dead，等待后台人工处理。
func (q *Queries) MarkSettlementRecoveryJobDead(ctx context.Context, arg MarkSettlementRecoveryJobDeadParams) (SettlementRecoveryJob, error) {
	row := q.db.QueryRow(ctx, markSettlementRecoveryJobDead,
		arg.LastErrorCode,
		arg.LastErrorMessage,
		arg.LastInternalErrorDetail,
		arg.CompletedAt,
		arg.ID,
		arg.LockedBy,
		arg.LockedUntil,
		arg.AttemptCount,
	)
	var i SettlementRecoveryJob
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RequestRecordID,
		&i.AttemptID,
		&i.ReservationID,
		&i.ResponseModelID,
		&i.ModelID,
		&i.ProviderID,
		&i.ChannelID,
		&i.UpstreamResponseModel,
		&i.UpstreamStatusCode,
		&i.UpstreamRequestID,
		&i.UsagePromptTokens,
		&i.UsageCompletionTokens,
		&i.UsageTotalTokens,
		&i.UsageCachedTokens,
		&i.UsageReasoningTokens,
		&i.UsageSource,
		&i.PriceID,
		&i.Currency,
		&i.PricingUnit,
		&i.InputPrice,
		&i.OutputPrice,
		&i.CachedInputPrice,
		&i.ReasoningOutputPrice,
		&i.FormulaVersion,
		&i.EstimatedAmount,
		&i.AuthorizedAmount,
		&i.Status,
		&i.AttemptCount,
		&i.MaxAttempts,
		&i.NextRunAt,
		&i.LockedBy,
		&i.LockedUntil,
		&i.LastErrorCode,
		&i.LastErrorMessage,
		&i.LastInternalErrorDetail,
		&i.LastAttemptedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markSettlementRecoveryJobRetry = `-- name: MarkSettlementRecoveryJobRetry :one
UPDATE settlement_recovery_jobs
SET
    status = 'pending',
    locked_by = NULL,
    locked_until = NULL,
    next_run_at = $1,
    last_error_code = $2,
    last_error_message = $3,
    last_internal_error_detail = $4,
    updated_at = $5
WHERE settlement_recovery_jobs.id = $6
  AND settlement_recovery_jobs.status = 'running'
  AND settlement_recovery_jobs.locked_by = $7
  AND settlement_recovery_jobs.locked_until = $8
  AND settlement_recovery_jobs.attempt_count = $9
  AND settlement_recovery_jobs.attempt_count < settlement_recovery_jobs.max_attempts
RETURNING id, user_id, request_record_id, attempt_id, reservation_id, response_model_id, model_id, provider_id, channel_id, upstream_response_model, upstream_status_code, upstream_request_id, usage_prompt_tokens, usage_completion_tokens, usage_total_tokens, usage_cached_tokens, usage_reasoning_tokens, usage_source, price_id, currency, pricing_unit, input_price, output_price, cached_input_price, reasoning_output_price, formula_version, estimated_amount, authorized_amount, status, attempt_count, max_attempts, next_run_at, locked_by, locked_until, last_error_code, last_error_message, last_internal_error_detail, last_attempted_at, completed_at, created_at, updated_at
`

type MarkSettlementRecoveryJobRetryParams struct {
	NextRunAt               pgtype.Timestamptz
	LastErrorCode           pgtype.Text
	LastErrorMessage        pgtype.Text
	LastInternalErrorDetail pgtype.Text
	UpdatedAt               pgtype.Timestamptz
	ID                      int64
	LockedBy                pgtype.Text
	LockedUntil             pgtype.Timestamptz
	AttemptCount            int32
}

// MarkSettlementRecoveryJobRetry 将 running recovery job 退回 pending 并设置下次重试时间。
func (q *Queries) MarkSettlementRecoveryJobRetry(ctx context.Context, arg MarkSettlementRecoveryJobRetryParams) (SettlementRecoveryJob, error) {
	row := q.db.QueryRow(ctx, markSettlementRecoveryJobRetry,
		arg.NextRunAt,
		arg.LastErrorCode,
		arg.LastErrorMessage,
		arg.LastInternalErrorDetail,
		arg.UpdatedAt,
		arg.ID,
		arg.LockedBy,
		arg.LockedUntil,
		arg.AttemptCount,
	)
	var i SettlementRecoveryJob
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RequestRecordID,
		&i.AttemptID,
		&i.ReservationID,
		&i.ResponseModelID,
		&i.ModelID,
		&i.ProviderID,
		&i.ChannelID,
		&i.UpstreamResponseModel,
		&i.UpstreamStatusCode,
		&i.UpstreamRequestID,
		&i.UsagePromptTokens,
		&i.UsageCompletionTokens,
		&i.UsageTotalTokens,
		&i.UsageCachedTokens,
		&i.UsageReasoningTokens,
		&i.UsageSource,
		&i.PriceID,
		&i.Currency,
		&i.PricingUnit,
		&i.InputPrice,
		&i.OutputPrice,
		&i.CachedInputPrice,
		&i.ReasoningOutputPrice,
		&i.FormulaVersion,
		&i.EstimatedAmount,
		&i.AuthorizedAmount,
		&i.Status,
		&i.AttemptCount,
		&i.MaxAttempts,
		&i.NextRunAt,
		&i.LockedBy,
		&i.LockedUntil,
		&i.LastErrorCode,
		&i.LastErrorMessage,
		&i.LastInternalErrorDetail,
		&i.LastAttemptedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markSettlementRecoveryJobSucceeded = `-- name: MarkSettlementRecoveryJobSucceeded :one
WITH updated AS (
    UPDATE settlement_recovery_jobs
    SET
        status = 'succeeded',
        locked_by = NULL,
        locked_until = NULL,
        completed_at = $1,
        updated_at = $1
    WHERE settlement_recovery_jobs.id = $2
      AND settlement_recovery_jobs.status IN ('pending', 'running')
    RETURNING id, user_id, request_record_id, attempt_id, reservation_id, response_model_id, model_id, provider_id, channel_id, upstream_response_model, upstream_status_code, upstream_request_id, usage_prompt_tokens, usage_completion_tokens, usage_total_tokens, usage_cached_tokens, usage_reasoning_tokens, usage_source, price_id, currency, pricing_unit, input_price, output_price, cached_input_price, reasoning_output_price, formula_version, estimated_amount, authorized_amount, status, attempt_count, max_attempts, next_run_at, locked_by, locked_until, last_error_code, last_error_message, last_internal_error_detail, last_attempted_at, completed_at, created_at, updated_at
)
SELECT id, user_id, request_record_id, attempt_id, reservation_id, response_model_id, model_id, provider_id, channel_id, upstream_response_model, upstream_status_code, upstream_request_id, usage_prompt_tokens, usage_completion_tokens, usage_total_tokens, usage_cached_tokens, usage_reasoning_tokens, usage_source, price_id, currency, pricing_unit, input_price, output_price, cached_input_price, reasoning_output_price, formula_version, estimated_amount, authorized_amount, status, attempt_count, max_attempts, next_run_at, locked_by, locked_until, last_error_code, last_error_message, last_internal_error_detail, last_attempted_at, completed_at, created_at, updated_at
FROM updated

UNION ALL

SELECT settlement_recovery_jobs.id, settlement_recovery_jobs.user_id, settlement_recovery_jobs.request_record_id, settlement_recovery_jobs.attempt_id, settlement_recovery_jobs.reservation_id, settlement_recovery_jobs.response_model_id, settlement_recovery_jobs.model_id, settlement_recovery_jobs.provider_id, settlement_recovery_jobs.channel_id, settlement_recovery_jobs.upstream_response_model, settlement_recovery_jobs.upstream_status_code, settlement_recovery_jobs.upstream_request_id, settlement_recovery_jobs.usage_prompt_tokens, settlement_recovery_jobs.usage_completion_tokens, settlement_recovery_jobs.usage_total_tokens, settlement_recovery_jobs.usage_cached_tokens, settlement_recovery_jobs.usage_reasoning_tokens, settlement_recovery_jobs.usage_source, settlement_recovery_jobs.price_id, settlement_recovery_jobs.currency, settlement_recovery_jobs.pricing_unit, settlement_recovery_jobs.input_price, settlement_recovery_jobs.output_price, settlement_recovery_jobs.cached_input_price, settlement_recovery_jobs.reasoning_output_price, settlement_recovery_jobs.formula_version, settlement_recovery_jobs.estimated_amount, settlement_recovery_jobs.authorized_amount, settlement_recovery_jobs.status, settlement_recovery_jobs.attempt_count, settlement_recovery_jobs.max_attempts, settlement_recovery_jobs.next_run_at, settlement_recovery_jobs.locked_by, settlement_recovery_jobs.locked_until, settlement_recovery_jobs.last_error_code, settlement_recovery_jobs.last_error_message, settlement_recovery_jobs.last_internal_error_detail, settlement_recovery_jobs.last_attempted_at, settlement_recovery_jobs.completed_at, settlement_recovery_jobs.created_at, settlement_recovery_jobs.updated_at
FROM settlement_recovery_jobs
WHERE settlement_recovery_jobs.id = $2
  AND settlement_recovery_jobs.status = 'succeeded'
  AND NOT EXISTS (SELECT 1 FROM updated)
`

type MarkSettlementRecoveryJobSucceededParams struct {
	CompletedAt pgtype.Timestamptz
	ID          int64
}

type MarkSettlementRecoveryJobSucceededRow struct {
	ID                      int64
	UserID                  int64
	RequestRecordID         int64
	AttemptID               int64
	ReservationID           int64
	ResponseModelID         string
	ModelID                 int64
	ProviderID              int64
	ChannelID               int64
	UpstreamResponseModel   string
	UpstreamStatusCode      int32
	UpstreamRequestID       pgtype.Text
	UsagePromptTokens       int64
	UsageCompletionTokens   int64
	UsageTotalTokens        int64
	UsageCachedTokens       int64
	UsageReasoningTokens    int64
	UsageSource             string
	PriceID                 int64
	Currency                string
	PricingUnit             string
	InputPrice              pgtype.Numeric
	OutputPrice             pgtype.Numeric
	CachedInputPrice        pgtype.Numeric
	ReasoningOutputPrice    pgtype.Numeric
	FormulaVersion          string
	EstimatedAmount         pgtype.Numeric
	AuthorizedAmount        pgtype.Numeric
	Status                  string
	AttemptCount            int32
	MaxAttempts             int32
	NextRunAt               pgtype.Timestamptz
	LockedBy                pgtype.Text
	LockedUntil             pgtype.Timestamptz
	LastErrorCode           pgtype.Text
	LastErrorMessage        pgtype.Text
	LastInternalErrorDetail pgtype.Text
	LastAttemptedAt         pgtype.Timestamptz
	CompletedAt             pgtype.Timestamptz
	CreatedAt               pgtype.Timestamptz
	UpdatedAt               pgtype.Timestamptz
}

// MarkSettlementRecoveryJobSucceeded 将 pending/running recovery job 标记为 succeeded。
func (q *Queries) MarkSettlementRecoveryJobSucceeded(ctx context.Context, arg MarkSettlementRecoveryJobSucceededParams) (MarkSettlementRecoveryJobSucceededRow, error) {
	row := q.db.QueryRow(ctx, markSettlementRecoveryJobSucceeded, arg.CompletedAt, arg.ID)
	var i MarkSettlementRecoveryJobSucceededRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RequestRecordID,
		&i.AttemptID,
		&i.ReservationID,
		&i.ResponseModelID,
		&i.ModelID,
		&i.ProviderID,
		&i.ChannelID,
		&i.UpstreamResponseModel,
		&i.UpstreamStatusCode,
		&i.UpstreamRequestID,
		&i.UsagePromptTokens,
		&i.UsageCompletionTokens,
		&i.UsageTotalTokens,
		&i.UsageCachedTokens,
		&i.UsageReasoningTokens,
		&i.UsageSource,
		&i.PriceID,
		&i.Currency,
		&i.PricingUnit,
		&i.InputPrice,
		&i.OutputPrice,
		&i.CachedInputPrice,
		&i.ReasoningOutputPrice,
		&i.FormulaVersion,
		&i.EstimatedAmount,
		&i.AuthorizedAmount,
		&i.Status,
		&i.AttemptCount,
		&i.MaxAttempts,
		&i.NextRunAt,
		&i.LockedBy,
		&i.LockedUntil,
		&i.LastErrorCode,
		&i.LastErrorMessage,
		&i.LastInternalErrorDetail,
		&i.LastAttemptedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
