// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: system.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const systemChannelHealth = `-- name: SystemChannelHealth :many

SELECT
    c.id AS channel_id,
    c.name,
    c.status,
    c.provider_id,
    COUNT(a.id) AS attempt_total,
    COUNT(a.id) FILTER (WHERE a.status = 'succeeded') AS attempt_succeeded,
    COUNT(a.id) FILTER (WHERE a.status = 'failed') AS attempt_failed,
    COUNT(a.id) FILTER (WHERE a.status = 'failed' AND a.fault_party = 'upstream') AS attempt_upstream_failed,
    COUNT(a.id) FILTER (WHERE a.status = 'canceled') AS attempt_canceled,
    MAX(a.created_at)::timestamptz AS last_attempt_at
FROM channels c
LEFT JOIN request_attempts a
    ON a.channel_id = c.id
    AND ($1::timestamptz IS NULL OR a.created_at >= $1::timestamptz)
    AND ($2::timestamptz IS NULL OR a.created_at < $2::timestamptz)
GROUP BY c.id, c.name, c.status, c.provider_id
ORDER BY attempt_failed DESC, attempt_total DESC, c.id
`

type SystemChannelHealthParams struct {
	FromTime pgtype.Timestamptz
	ToTime   pgtype.Timestamptz
}

type SystemChannelHealthRow struct {
	ChannelID             int64
	Name                  string
	Status                string
	ProviderID            int64
	AttemptTotal          int64
	AttemptSucceeded      int64
	AttemptFailed         int64
	AttemptUpstreamFailed int64
	AttemptCanceled       int64
	LastAttemptAt         pgtype.Timestamptz
}

// M8 系统 / 任务 / 健康（横切）只读聚合。纯只读、不引入新业务事实。
// channel 熔断为 gateway 进程内内存态（见 lifecycle/breaker.go），admin 跨进程读不到；
// 此处的 channel 健康从区间内 request_attempts 成功率派生，作为运营可观测的近似。
// SystemChannelHealth 按区间内 request_attempts 推导每个 channel 的健康明细（比 M9 看板更细：含失败数与最近尝试时间）。
// LEFT JOIN + 时间过滤放在 ON 条件，保留区间内零尝试的 channel（service 视为 no_data）。
func (q *Queries) SystemChannelHealth(ctx context.Context, arg SystemChannelHealthParams) ([]SystemChannelHealthRow, error) {
	rows, err := q.db.Query(ctx, systemChannelHealth, arg.FromTime, arg.ToTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SystemChannelHealthRow
	for rows.Next() {
		var i SystemChannelHealthRow
		if err := rows.Scan(
			&i.ChannelID,
			&i.Name,
			&i.Status,
			&i.ProviderID,
			&i.AttemptTotal,
			&i.AttemptSucceeded,
			&i.AttemptFailed,
			&i.AttemptUpstreamFailed,
			&i.AttemptCanceled,
			&i.LastAttemptAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
