// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ApiKey struct {
	ID         int64
	ProjectID  int64
	Name       string
	KeyPrefix  string
	KeyHash    string
	LastUsedAt pgtype.Timestamptz
	ExpiresAt  pgtype.Timestamptz
	DisabledAt pgtype.Timestamptz
	RevokedAt  pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type Channel struct {
	ID            int64
	ProviderID    int64
	Name          string
	BaseUrl       string
	CredentialRef string
	Status        string
	Priority      int32
	TimeoutMs     pgtype.Int4
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type ChannelModel struct {
	ID            int64
	ChannelID     int64
	ModelID       int64
	UpstreamModel string
	Status        string
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type LedgerBillingException struct {
	ID              int64
	UserID          int64
	RequestRecordID int64
	ReservationID   int64
	EventType       string
	ActualAmount    pgtype.Numeric
	CapturedAmount  pgtype.Numeric
	PlatformAmount  pgtype.Numeric
	Currency        string
	ReasonCode      string
	Reason          string
	CreatedAt       pgtype.Timestamptz
}

type LedgerEntry struct {
	ID              int64
	UserID          int64
	RequestRecordID pgtype.Int8
	EntryType       string
	Amount          pgtype.Numeric
	Currency        string
	BalanceBefore   pgtype.Numeric
	BalanceAfter    pgtype.Numeric
	IdempotencyKey  string
	Reason          string
	CreatedAt       pgtype.Timestamptz
}

type LedgerReservation struct {
	ID                   int64
	UserID               int64
	RequestRecordID      int64
	Currency             string
	Status               string
	AuthorizedAmount     pgtype.Numeric
	CapturedAmount       pgtype.Numeric
	ReleasedAmount       pgtype.Numeric
	EstimatedAmount      pgtype.Numeric
	CaptureLedgerEntryID pgtype.Int8
	IdempotencyKey       string
	Reason               string
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
	CapturedAt           pgtype.Timestamptz
	ReleasedAt           pgtype.Timestamptz
}

type Model struct {
	ID          int64
	ModelID     string
	DisplayName string
	OwnedBy     string
	Status      string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type Price struct {
	ID                   int64
	ModelID              int64
	Currency             string
	PricingUnit          string
	InputPrice           pgtype.Numeric
	OutputPrice          pgtype.Numeric
	CachedInputPrice     pgtype.Numeric
	ReasoningOutputPrice pgtype.Numeric
	Status               string
	EffectiveFrom        pgtype.Timestamptz
	EffectiveTo          pgtype.Timestamptz
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
}

type PriceSnapshot struct {
	ID                   int64
	RequestRecordID      int64
	PriceID              pgtype.Int8
	Currency             string
	PricingUnit          string
	InputPrice           pgtype.Numeric
	OutputPrice          pgtype.Numeric
	CachedInputPrice     pgtype.Numeric
	ReasoningOutputPrice pgtype.Numeric
	FormulaVersion       string
	CreatedAt            pgtype.Timestamptz
}

type Project struct {
	ID        int64
	UserID    int64
	Name      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type ProjectModelPolicy struct {
	ProjectID  int64
	ModelID    int64
	Visibility string
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type Provider struct {
	ID        int64
	Slug      string
	Name      string
	Adapter   string
	Status    string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type RequestAttempt struct {
	ID                    int64
	RequestRecordID       int64
	AttemptIndex          int32
	ProviderID            int64
	ChannelID             int64
	AdapterKey            string
	UpstreamModel         string
	UpstreamResponseModel pgtype.Text
	Status                string
	UpstreamStatusCode    pgtype.Int4
	UpstreamRequestID     pgtype.Text
	ErrorCode             pgtype.Text
	ErrorMessage          pgtype.Text
	InternalErrorDetail   pgtype.Text
	StartedAt             pgtype.Timestamptz
	CompletedAt           pgtype.Timestamptz
	CreatedAt             pgtype.Timestamptz
}

type RequestRecord struct {
	ID                  int64
	RequestID           string
	UserID              int64
	ProjectID           int64
	ApiKeyID            int64
	RequestedModelID    string
	ResponseModelID     pgtype.Text
	Stream              bool
	Status              string
	FinalProviderID     pgtype.Int8
	FinalChannelID      pgtype.Int8
	ErrorCode           pgtype.Text
	ErrorMessage        pgtype.Text
	InternalErrorDetail pgtype.Text
	StartedAt           pgtype.Timestamptz
	CompletedAt         pgtype.Timestamptz
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
}

type SchemaHealthCheck struct {
	ID        int64
	Name      string
	CreatedAt pgtype.Timestamptz
}

type UsageRecord struct {
	ID               int64
	RequestRecordID  int64
	PromptTokens     int64
	CompletionTokens int64
	TotalTokens      int64
	CachedTokens     int64
	ReasoningTokens  int64
	Source           string
	CreatedAt        pgtype.Timestamptz
}

type User struct {
	ID           int64
	Email        string
	PasswordHash string
	DisplayName  string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type UserBalance struct {
	ID              int64
	UserID          int64
	Currency        string
	Balance         pgtype.Numeric
	ReservedBalance pgtype.Numeric
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}
