// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: usage_records.sql

package sqlc

import (
	"context"
)

const createUsageRecord = `-- name: CreateUsageRecord :one
INSERT INTO usage_records (
    request_record_id,
    prompt_tokens,
    completion_tokens,
    total_tokens,
    cached_tokens,
    reasoning_tokens,
    source
)
VALUES (
           $1,
           $2,
           $3,
           $4,
           $5,
           $6,
           $7
       )
RETURNING
    id,
    request_record_id,
    prompt_tokens,
    completion_tokens,
    total_tokens,
    cached_tokens,
    reasoning_tokens,
    source,
    created_at
`

type CreateUsageRecordParams struct {
	RequestRecordID  int64
	PromptTokens     int64
	CompletionTokens int64
	TotalTokens      int64
	CachedTokens     int64
	ReasoningTokens  int64
	Source           string
}

// CreateUsageRecord 创建一次请求最终用于计费和审计的 usage 记录。
func (q *Queries) CreateUsageRecord(ctx context.Context, arg CreateUsageRecordParams) (UsageRecord, error) {
	row := q.db.QueryRow(ctx, createUsageRecord,
		arg.RequestRecordID,
		arg.PromptTokens,
		arg.CompletionTokens,
		arg.TotalTokens,
		arg.CachedTokens,
		arg.ReasoningTokens,
		arg.Source,
	)
	var i UsageRecord
	err := row.Scan(
		&i.ID,
		&i.RequestRecordID,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.TotalTokens,
		&i.CachedTokens,
		&i.ReasoningTokens,
		&i.Source,
		&i.CreatedAt,
	)
	return i, err
}

const getUsageRecordByRequest = `-- name: GetUsageRecordByRequest :one
SELECT
    id,
    request_record_id,
    prompt_tokens,
    completion_tokens,
    total_tokens,
    cached_tokens,
    reasoning_tokens,
    source,
    created_at
FROM usage_records
WHERE request_record_id = $1
`

// GetUsageRecordByRequest 按请求 ID 读取 usage 记录。
func (q *Queries) GetUsageRecordByRequest(ctx context.Context, requestRecordID int64) (UsageRecord, error) {
	row := q.db.QueryRow(ctx, getUsageRecordByRequest, requestRecordID)
	var i UsageRecord
	err := row.Scan(
		&i.ID,
		&i.RequestRecordID,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.TotalTokens,
		&i.CachedTokens,
		&i.ReasoningTokens,
		&i.Source,
		&i.CreatedAt,
	)
	return i, err
}
